# -*- coding: utf-8 -*-
# cities_data.py — Hudson: nearby-city landing pages. Edit copy here; build_cities.py renders.
CITY_SITE = {
 "base": "https://hudson.serenemedspas.com",
 "loc_short": "Hudson",
 "biz_name": "Serene Med Spa — Hudson",
 "tel": "tel:+13304605915", "tel_e164": "+1-330-460-5915", "phone": "(330) 460-5915",
 "addr1": "50 W Streetsboro St, Suite 2", "addr2": "Hudson, OH 44236",
 "address": {"@type":"PostalAddress","streetAddress":"50 W Streetsboro St, Suite 2","addressLocality":"Hudson","addressRegion":"OH","postalCode":"44236","addressCountry":"US"},
 "geo": {"@type":"GeoCoordinates","latitude":41.2401,"longitude":-81.4409},
 "geo_meta": '<meta name="geo.region" content="US-OH"><meta name="geo.placename" content="Hudson, Ohio"><meta name="geo.position" content="41.2401;-81.4409"><meta name="ICBM" content="41.2401, -81.4409">',
 "dest_q": "50+W+Streetsboro+St+Suite+2+Hudson+OH+44236",
 "hours": "Mon&ndash;Fri: 9 AM &ndash; 5 PM<br>Sat&ndash;Sun: By appointment",
 "hours_spec": [{"@type":"OpeningHoursSpecification","dayOfWeek":["Monday","Tuesday","Wednesday","Thursday","Friday"],"opens":"09:00","closes":"17:00"}],
 "hero_img": "lobby.jpg",
 "ntreat": 39,
 "promo": '<div class="promo">&#10024; <strong>New to Serene?</strong> Ask about our current first-visit specials &mdash; <a href="%s" target="_blank" rel="noopener">book a consultation</a> today &#10024;</div>' % BOOK,
 "steps": [
  ("Book online or call", "Pick a free consultation or go straight to a treatment on our online calendar. Same-week openings are common; tell us if you&rsquo;re coming from out of town and we&rsquo;ll stack your visits."),
  ("Park at the door", "We&rsquo;re at 50 W Streetsboro St (Route 303) in downtown Hudson with free parking right outside Suite 2 &mdash; no garage, no meters."),
  ("Meet your physician", "Dr. Shweta Arora or Dr. Robin Arora reviews your goals, your skin and your history, then builds a plan around your budget. Most consults take 20&ndash;30 minutes."),
  ("Treat the same day", "Botox, filler, SKINVIVE, facials and most laser treatments can be done at the consult if you&rsquo;re a candidate, so one drive covers both."),
 ],
}

# (slug, name, price line, blurb) — the six most searched treatments from Search Console for the Akron/Cleveland area
TREATMENTS = [
 ("botox","Botox &amp; Wrinkle Relaxers","From $11/unit","Botox, Dysport, Xeomin and Daxxify for frown lines, forehead lines and crow&rsquo;s feet &mdash; injected by physicians."),
 ("fillers","Dermal Fillers","From $500/syringe","The full Juv&eacute;derm family, Restylane and Radiesse for lips, cheeks, jawline, chin and under-eyes."),
 ("morpheus8","Morpheus8 RF Microneedling","$800 (3 for $2,100)","Tightens, smooths and rebuilds collagen on the face, neck and body with minimal downtime."),
 ("kybella","Kybella Double-Chin Treatment","$600/vial","The only FDA-approved injectable that permanently dissolves fat under the chin."),
 ("laser-hair-removal","Laser Hair Removal","Per area","Soprano Ice Platinum &mdash; virtually painless, safe for all skin tones, year-round."),
 ("hydrafacial","HydraFacial &amp; DiamondGlow","$150","30-minute, no-downtime facials that cleanse, extract and hydrate."),
 ("weight-loss","Medical Weight Loss","$149/visit","Physician-supervised semaglutide and tirzepatide programs with monthly check-ins."),
 ("iv-therapy","IV Therapy &amp; NAD+","From $149","Hydration, immune, energy and NAD+ infusions in our IV lounge."),
 ("lip-filler","Lip Filler","$500 (Mini Pout $300)","Natural, proportioned lips with Volbella, Ultra XC or Restylane Kysse."),
 ("thread-lift","PDO Thread Lift","From $500","Non-surgical lift for the jawline, cheeks and brows using dissolvable threads."),
 ("sculptra","Sculptra","$750/vial","Collagen stimulator for gradual, natural volume in the face and body."),
 ("chemical-peels","Chemical Peels","From $250","VI Peel and medical-grade peels for tone, texture, acne and melasma."),
]

CITIES = [
 {"slug":"med-spa-akron-oh","city":"Akron","city_state":"Akron, OH","also":["Fairlawn, OH","Tallmadge, OH","Bath, OH","Copley, OH"],
  "title":"Med Spa Near Akron, OH | Botox, Fillers & Laser | Serene",
  "desc":"Physician-led med spa 25 min from Akron: Botox $11/unit, Juvéderm fillers, Morpheus8, Kybella & laser hair removal in Hudson, OH. Free consults.",
  "h1":"Akron&rsquo;s physician-led med spa, 25 minutes up Route 8",
  "hero":"Serene Med Spa is the practice Akron patients drive to when they want doctors doing the injecting, published prices, and a calm office instead of a crowded chain. We&rsquo;re in downtown Hudson, a straight shot up Route 8.",
  "drive":"About 25 minutes",
  "introh2":"Why Akron patients come to Hudson for aesthetics",
  "introlead":"Akron has no shortage of places offering Botox. What&rsquo;s harder to find is a medical practice where a board-certified physician does your consultation <em>and</em> your treatment, at prices that are posted online before you ever walk in.",
  "intro":"<p>That&rsquo;s what Serene was built to be. Dr. Shweta Arora (anesthesiology, aesthetic medicine) and Dr. Robin Arora (internal medicine, nephrology) own the practice and see every patient personally. Botox is $11 a unit, filler is $500 a syringe, and the full list is on our <a href=\"/pricing/\">pricing page</a> &mdash; the same numbers whether you live in Highland Square, Fairlawn, Ellet or Firestone Park.</p><p>Patients from West Akron, North Hill and the University of Akron area tell us the trip is easier than crossing town at rush hour: Route 8 north to Route 303, then two minutes east into downtown Hudson, with free parking at the door. Many pair a visit with lunch or shopping on Hudson&rsquo;s First &amp; Main.</p><p>Because we&rsquo;re an <strong>Allergan Platinum</strong> practice and an Alma and InMode provider, you also get the complete toolbox in one place: Botox and Juv&eacute;derm, Morpheus8, Kybella, Soprano laser hair removal, Opus Plasma resurfacing, HydraFacial and medical weight loss &mdash; so your plan is built around your face, not around what a franchise happens to own.</p>",
  "treatments":["botox","fillers","morpheus8","kybella","laser-hair-removal","weight-loss"],
  "directions":"<p><strong>From downtown Akron (about 15 miles):</strong> take OH-8 North for roughly 12 miles, exit at OH-303 (Streetsboro Rd) and head east. We&rsquo;re at 50 W Streetsboro St, Suite 2, just before the Route 91 / Main St light in downtown Hudson.</p><p><strong>From Fairlawn / Copley / Bath:</strong> I-77 North to OH-8 North, then OH-303 East (about 25&ndash;30 minutes). <strong>From Ellet / Tallmadge:</strong> OH-91 North straight into Hudson (about 20 minutes) &mdash; we&rsquo;re at the corner of 91 and 303.</p>",
  "origin_q":"Akron,+OH",
  "faqs":[
   ("Is there a Serene Med Spa in Akron?","Not yet &mdash; our Ohio office is in Hudson, about 25 minutes north of downtown Akron via Route 8. We treat patients from every Akron neighborhood as well as Fairlawn, Tallmadge, Copley and Bath, and we also have a location in Barboursville, WV."),
   ("How much is Botox near Akron?","Botox, Xeomin and Daxxify are $11 per unit at Serene Med Spa Hudson; Dysport is $3.99 per Dysport unit. A typical frown-line treatment is 20 units ($220). There is no consultation fee, and Allē members can use their points here because we&rsquo;re an Allergan Platinum partner."),
   ("Who does the injections?","Board-certified physicians &mdash; Dr. Shweta Arora and Dr. Robin Arora &mdash; not a rotating injector. They do your consult, your treatment and your follow-up."),
   ("Can I get treated the same day as my consultation?","Usually yes. If you&rsquo;re a good candidate, Botox, filler, SKINVIVE, Kybella, facials and most laser treatments can be done at the consult visit so you only make one drive from Akron."),
   ("Do you offer evening or weekend appointments for people commuting from Akron?","We&rsquo;re open Monday&ndash;Friday 9&ndash;5 and see patients on Saturdays by appointment. Call (330) 460-5915 and we&rsquo;ll find a time that works with your commute."),
   ("Is parking free?","Yes. We&rsquo;re a street-level office at 50 W Streetsboro St with free parking right outside Suite 2 &mdash; no garage, no meters, no downtown Akron parking hunt."),
  ]},

 {"slug":"med-spa-stow-oh","city":"Stow","city_state":"Stow, OH","also":["Munroe Falls, OH","Silver Lake, OH","Kent, OH"],
  "title":"Med Spa Near Stow, OH | Botox & Fillers 12 Min Away | Serene",
  "desc":"Stow's closest physician-led med spa, 12 min up Route 91 in Hudson: Botox $11/unit, Juvéderm, Morpheus8, HydraFacial, laser hair removal. Free consults.",
  "h1":"Stow&rsquo;s closest physician-led med spa &mdash; 12 minutes up Darrow Road",
  "hero":"If you live in Stow, Munroe Falls or Silver Lake, Serene Med Spa is the doctor-run aesthetic practice next door. Straight up Route 91 into downtown Hudson, free parking at the door, and pricing you can read online before you book.",
  "drive":"About 12 minutes",
  "introh2":"The med spa Stow patients can reach on a lunch break",
  "introlead":"Stow sits right on our doorstep. Darrow Road (Route 91) runs from the Stow-Kent shopping area straight north into Hudson, and our office is at the corner where 91 meets Route 303 &mdash; about 12 minutes door to door.",
  "intro":"<p>That closeness matters more than it sounds. Botox and filler results are best maintained on a schedule &mdash; every 3&ndash;4 months for Botox, every 9&ndash;18 months for filler &mdash; and a quick 20-minute appointment is far easier to keep when the drive is shorter than the treatment. Our Stow patients often book a HydraFacial or a Botox touch-up between errands at Stow Community Center or the Kent State campus and are back in under an hour.</p><p>What you get for that short drive is a practice owned and run by two board-certified physicians, Dr. Shweta Arora and Dr. Robin Arora. They do every consultation and every injection themselves. Botox is $11 per unit, filler is $500 per syringe, HydraFacial and DiamondGlow are $150, and every other price is published on our <a href=\"/pricing/\">price list</a>.</p><p>As an Allergan Platinum partner we carry the full Juv&eacute;derm line, SKINVIVE and Kybella, plus Morpheus8, Ultherapy, Soprano laser hair removal, Opus Plasma, EMSCULPT NEO and a physician-supervised weight-loss program &mdash; the complete menu in one Hudson office instead of three different places around Stow and Cuyahoga Falls.</p>",
  "treatments":["botox","fillers","hydrafacial","morpheus8","laser-hair-removal","lip-filler"],
  "directions":"<p><strong>From Stow (about 6 miles):</strong> take Darrow Rd / OH-91 North through Hudson. At the OH-303 (Streetsboro St) light you&rsquo;re there &mdash; 50 W Streetsboro St, Suite 2, steps west of Main St, with parking out front.</p><p><strong>From Munroe Falls / Silver Lake:</strong> OH-91 North, about 15 minutes. <strong>From Kent:</strong> OH-43 North to OH-303 West, about 15 minutes.</p>",
  "origin_q":"Stow,+OH",
  "faqs":[
   ("How far is Serene Med Spa from Stow?","About 6 miles &mdash; roughly 12 minutes straight up Darrow Road (Route 91) to the corner of Route 303 in downtown Hudson. From Munroe Falls or Silver Lake it&rsquo;s closer to 15 minutes."),
   ("What does Botox cost near Stow?","$11 per unit for Botox, Xeomin and Daxxify (Dysport $3.99/unit). Frown lines are typically 20 units; a full upper face is 40&ndash;60 units. No consultation fee."),
   ("Can I come in on a lunch break?","Yes &mdash; Botox, SKINVIVE, a lip flip or a HydraFacial each take 20&ndash;40 minutes with no downtime, and parking is right outside the door. Book online and pick a midday slot."),
   ("Do you treat men?","Absolutely. Many of our Stow patients are men coming in for Botox, Kybella, laser hair removal, hair restoration or our men&rsquo;s wellness services."),
   ("Are the injectors doctors?","Yes. Dr. Shweta Arora (board-certified anesthesiologist, certified in aesthetic medicine) and Dr. Robin Arora (board-certified internal medicine) do all consultations and injections."),
   ("Do you have a rewards program?","Yes &mdash; Allē (Allergan) points for Botox, Juv&eacute;derm, SKINVIVE and Kybella, Xperience+ from Merz, and our own Serene membership. Ask at your first visit."),
  ]},

 {"slug":"med-spa-cuyahoga-falls-oh","city":"Cuyahoga Falls","city_state":"Cuyahoga Falls, OH","also":["Northampton, OH","Silver Lake, OH"],
  "title":"Med Spa Near Cuyahoga Falls, OH | Botox, Fillers & Morpheus8",
  "desc":"Cuyahoga Falls' physician-led med spa, 15 min away in Hudson: Botox $11/unit, Juvéderm fillers, Morpheus8, Kybella, HydraFacial. Doctors inject.",
  "h1":"Botox, fillers &amp; Morpheus8 for Cuyahoga Falls &mdash; 15 minutes away in Hudson",
  "hero":"From the Falls it&rsquo;s a quick hop up Route 8 to a med spa where board-certified physicians do the treating and prices are posted online. Serene Med Spa Hudson serves Cuyahoga Falls, Northampton and Silver Lake.",
  "drive":"About 15 minutes",
  "introh2":"A physician practice, not a franchise, just north of the Falls",
  "introlead":"Cuyahoga Falls patients tell us the same thing: they searched &ldquo;botox fillers cuyahoga falls&rdquo; and found chains and part-time injectors. They wanted a doctor. We&rsquo;re that practice, 15 minutes up Route 8 in downtown Hudson.",
  "intro":"<p>Serene Med Spa is owned by Dr. Shweta Arora and Dr. Robin Arora, both board-certified physicians. There is no separate &ldquo;injector&rdquo; &mdash; the doctor who examines your face is the doctor who treats it. We&rsquo;re an Allergan Platinum partner (top tier for Botox, Juv&eacute;derm, SKINVIVE and Kybella volume), an Ultherapy PRIME provider and an Alma and InMode practice, so the full range of treatments is under one roof.</p><p>Pricing is simple and public: Botox $11/unit, Juv&eacute;derm and Restylane $500/syringe, Morpheus8 $800 (three sessions $2,100), Kybella $600/vial, HydraFacial $150. See the full <a href=\"/pricing/\">price list</a>. Consultations are free, and if you&rsquo;re a candidate we can usually treat you at that first visit.</p><p>From Front Street, Portage Trail or State Road the drive is 15&ndash;18 minutes: Route 8 north to Route 303, east two minutes into Hudson, park at the door. Patients from Northampton and the Blossom / Cuyahoga Valley side come up Akron-Peninsula Rd or Route 8 the same way.</p>",
  "treatments":["botox","fillers","morpheus8","kybella","hydrafacial","chemical-peels"],
  "directions":"<p><strong>From downtown Cuyahoga Falls (about 9 miles):</strong> take OH-8 North to the OH-303 / Streetsboro Rd exit, turn east, and continue about 2 miles into downtown Hudson. We&rsquo;re at 50 W Streetsboro St, Suite 2, just before the Route 91 / Main St light.</p><p><strong>From State Rd / Graham Rd:</strong> Hudson Dr north to OH-303 East, about 15 minutes. <strong>From Northampton / Akron-Peninsula Rd:</strong> north to OH-303, then east &mdash; about 18 minutes.</p>",
  "origin_q":"Cuyahoga+Falls,+OH",
  "faqs":[
   ("Where is the closest med spa with physician injectors to Cuyahoga Falls?","Serene Med Spa in downtown Hudson, about 15 minutes north on Route 8. Both of our injectors are board-certified physicians and owners of the practice."),
   ("How much are Botox and fillers near Cuyahoga Falls?","Botox is $11 per unit and dermal fillers (Juv&eacute;derm, Restylane, Radiesse) are $500 per syringe at Serene Hudson. A three-syringe Juv&eacute;derm bundle is $1,400. Prices are published and the consultation is free."),
   ("Do you offer Morpheus8 near Cuyahoga Falls?","Yes. Morpheus8 RF microneedling is $800 per session or $2,100 for a series of three, performed in our Hudson office with topical numbing. It&rsquo;s our most requested skin-tightening treatment for Falls patients."),
   ("Is the drive from the Falls worth it for a 15-minute Botox appointment?","Our patients think so &mdash; you get a physician, published pricing and free parking at the door, and Route 8 makes it a 15-minute trip. Many combine it with a HydraFacial or a SKINVIVE treatment in the same visit."),
   ("Can I use my Allē points?","Yes. We&rsquo;re an Allergan Platinum partner, so Allē rewards apply to Botox, Juv&eacute;derm, SKINVIVE and Kybella. We can also enroll you at your visit."),
   ("Do you see patients from Silver Lake and Northampton?","Yes &mdash; both are 15&ndash;18 minutes away. We also serve Stow, Munroe Falls, Tallmadge and Akron."),
  ]},

 {"slug":"med-spa-twinsburg-oh","city":"Twinsburg","city_state":"Twinsburg, OH","also":["Reminderville, OH","Macedonia, OH","Northfield, OH"],
  "title":"Med Spa Near Twinsburg, OH | Physician Botox & Fillers",
  "desc":"Twinsburg's neighboring physician-led med spa, 12 min down Route 91 in Hudson: Botox $11/unit, Juvéderm, Kybella, laser hair removal, Morpheus8.",
  "h1":"Twinsburg&rsquo;s neighboring physician-led med spa &mdash; 12 minutes down Route 91",
  "hero":"Serene Med Spa is the doctor-owned aesthetic practice just south of Twinsburg in downtown Hudson. Board-certified physicians, published prices, the full Allergan and Alma menu, and free parking at the door.",
  "drive":"About 12 minutes",
  "introh2":"Why Twinsburg, Reminderville and Macedonia choose Serene",
  "introlead":"Route 91 connects Twinsburg&rsquo;s town square to Hudson&rsquo;s in about 12 minutes, which makes Serene the most convenient physician-run med spa for the Twinsburg, Reminderville, Macedonia and Northfield area.",
  "intro":"<p>Plenty of Twinsburg patients used to drive to Beachwood or Solon for a doctor-led practice. Serene brings that to Hudson: Dr. Shweta Arora and Dr. Robin Arora, both board-certified physicians, own the practice and personally perform every consultation and injection. We&rsquo;re an Allergan Platinum partner, an Ultherapy PRIME provider, and an Alma and InMode practice.</p><p>Every price is public. Botox is $11 per unit, filler $500 per syringe, Kybella $600 per vial, Morpheus8 $800, HydraFacial $150, and laser hair removal is priced per area with packages &mdash; see the <a href=\"/pricing/\">full price list</a>. Consults are free and can turn into treatment the same day.</p><p>The drive is simple: Route 91 (Darrow Rd) south from Twinsburg through the Route 82 intersection, into Hudson, and we&rsquo;re at the corner of 91 and Route 303 (Streetsboro St). From Macedonia or Northfield it&rsquo;s Route 8 south to 303 east, about 15 minutes.</p>",
  "treatments":["botox","fillers","kybella","laser-hair-removal","morpheus8","sculptra"],
  "directions":"<p><strong>From Twinsburg (about 7 miles):</strong> take OH-91 (Darrow Rd) South through the OH-82 light and continue into downtown Hudson. At OH-303 (Streetsboro St) turn west; we&rsquo;re steps away at 50 W Streetsboro St, Suite 2.</p><p><strong>From Reminderville / Aurora Rd:</strong> OH-82 West to OH-91 South, about 15 minutes. <strong>From Macedonia / Northfield:</strong> OH-8 South to OH-303 East, about 15 minutes.</p>",
  "origin_q":"Twinsburg,+OH",
  "faqs":[
   ("How far is Serene Med Spa from Twinsburg?","About 7 miles &mdash; roughly 12 minutes straight down Route 91 (Darrow Road) into downtown Hudson."),
   ("Are your injectors physicians?","Yes. Dr. Shweta Arora and Dr. Robin Arora are board-certified physicians who own the practice and perform every consultation and injection personally."),
   ("What does Botox cost near Twinsburg?","$11 per unit (Botox, Xeomin, Daxxify) and $3.99 per unit for Dysport. A typical frown-line treatment is 20 units. The consultation is free."),
   ("Do you do laser hair removal for Twinsburg patients?","Yes &mdash; with the Alma Soprano Ice Platinum, which is virtually painless and safe for all skin tones. Packages of six sessions are available; call for per-area pricing."),
   ("Can I book online?","Yes. Use the Book button on this page to choose a free consultation or a specific treatment on our live calendar."),
   ("Do you also serve Macedonia, Northfield and Reminderville?","Yes &mdash; all three are within 15 minutes. We also serve Aurora, Streetsboro, Solon and Stow."),
  ]},

 {"slug":"med-spa-solon-oh","city":"Solon","city_state":"Solon, OH","also":["Chagrin Falls, OH","Bainbridge, OH","Bedford, OH","Glenwillow, OH"],
  "title":"Med Spa Near Solon, OH | Physician-Led Botox & Fillers",
  "desc":"Solon & Chagrin Falls: a physician-led med spa 20 min away in Hudson with Botox $11/unit, Juvéderm fillers, Ultherapy, Morpheus8 & Kybella. Free consults.",
  "h1":"A physician-led med spa for Solon &amp; Chagrin Falls &mdash; 20 minutes away in Hudson",
  "hero":"Solon has plenty of options for aesthetics. Serene is the one where two board-certified physicians own the practice, do the injecting, and post every price online &mdash; 20 minutes south in downtown Hudson.",
  "drive":"About 20 minutes",
  "introh2":"Board-certified physicians, Solon-level expectations, Hudson prices",
  "introlead":"Patients from Solon, Chagrin Falls, Bainbridge and Glenwillow are used to high standards &mdash; and to Beachwood-level pricing. Serene Med Spa offers the physician-run experience at Hudson prices, about 20 minutes down Route 91 or Route 8.",
  "intro":"<p>Dr. Shweta Arora (board-certified anesthesiology, certified in aesthetic medicine) and Dr. Robin Arora (board-certified internal medicine) own Serene and see every patient. Because a physician does the work, we can offer the advanced end of the menu with confidence: Ultherapy (we&rsquo;re a PRIME provider), Morpheus8, Opus Plasma, Alma Hybrid laser resurfacing, PDO thread lifts, Sculptra and Kybella alongside everyday Botox and Juv&eacute;derm.</p><p>Pricing is published and consistent: Botox $11/unit, filler $500/syringe, Sculptra $750/vial, Morpheus8 $800, Ultherapy full face $2,600. See the <a href=\"/pricing/\">price list</a>. We&rsquo;re an Allergan Platinum partner, so Allē points apply.</p><p>Getting here from Solon is easy: Route 91 south through Twinsburg into Hudson (about 20 minutes), or Route 422 to Route 8 south to Route 303. Chagrin Falls and Bainbridge patients come down Route 306 to Route 82 west, then Route 91 south &mdash; about 25 minutes. Free parking is right outside Suite 2.</p>",
  "treatments":["botox","fillers","morpheus8","thread-lift","sculptra","kybella"],
  "directions":"<p><strong>From Solon (about 13 miles):</strong> take OH-91 (SOM Center Rd) South through Twinsburg and into Hudson. At OH-303 (Streetsboro St) turn west; we&rsquo;re steps away at 50 W Streetsboro St, Suite 2. Alternatively US-422 West to OH-8 South, exit OH-303 East.</p><p><strong>From Chagrin Falls / Bainbridge:</strong> OH-306 South to OH-82 West, then OH-91 South, about 25 minutes. <strong>From Bedford / Glenwillow:</strong> OH-8 South to OH-303 East, about 20 minutes.</p>",
  "origin_q":"Solon,+OH",
  "faqs":[
   ("How far is Serene Med Spa from Solon?","About 13 miles &mdash; roughly 20 minutes via Route 91 south through Twinsburg, or Route 422 to Route 8 south. Chagrin Falls and Bainbridge are about 25 minutes."),
   ("What does Botox cost compared with Solon or Beachwood?","Botox is $11 per unit at Serene Hudson, and every price is published online. Many Solon patients find that meaningfully lower than east-side pricing for the same product injected by a physician."),
   ("Do you offer Ultherapy near Solon?","Yes &mdash; Serene is an Ultherapy PRIME provider. Full face is $2,600, full face and neck $3,500, brow lift $950. Dr. Shweta Arora performs the treatment personally."),
   ("Who performs the injections?","Board-certified physicians Dr. Shweta Arora and Dr. Robin Arora. There are no rotating injectors."),
   ("Is the consultation really free?","Yes, always. You meet the physician, get a written plan with prices, and decide from there. If you&rsquo;re a candidate we can usually treat the same day."),
   ("Do you see patients from Chagrin Falls, Bainbridge and Bedford?","Yes. We regularly see patients from across the Chagrin Valley and the southeast Cleveland suburbs, as well as Twinsburg, Aurora and Hudson itself."),
  ]},

 {"slug":"med-spa-aurora-oh","city":"Aurora","city_state":"Aurora, OH","also":["Streetsboro, OH","Mantua, OH","Bainbridge, OH"],
  "title":"Med Spa Near Aurora, OH | Botox, Fillers & Laser | Serene",
  "desc":"Aurora & Streetsboro's physician-led med spa, 15 min away in Hudson: Botox $11/unit, Juvéderm fillers, laser hair removal, HydraFacial, Morpheus8.",
  "h1":"Aurora &amp; Streetsboro&rsquo;s physician-led med spa &mdash; 15 minutes west on Route 303",
  "hero":"Route 303 runs from Aurora and Streetsboro straight into downtown Hudson and right past our front door. Serene Med Spa is the doctor-owned practice where Portage County patients get Botox, fillers, laser and skin care with published prices.",
  "drive":"About 15 minutes",
  "introh2":"The med spa at the other end of Route 303",
  "introlead":"If you live in Aurora, Streetsboro or Mantua, you already know Route 303. Follow it west into Hudson and you&rsquo;ll find Serene at 50 W Streetsboro St &mdash; the practice Portage County patients choose for physician injectors and honest pricing.",
  "intro":"<p>Serene Med Spa is owned by Dr. Shweta Arora and Dr. Robin Arora, both board-certified physicians. They do every consultation and every injection. We&rsquo;re an Allergan Platinum partner, an Ultherapy PRIME provider, and an Alma and InMode practice, which means the full menu is here: Botox, the whole Juv&eacute;derm family, SKINVIVE, Kybella, Morpheus8, Opus Plasma, Soprano laser hair removal, HydraFacial, EMSCULPT NEO and physician-supervised weight loss.</p><p>Every price is public &mdash; Botox $11/unit, fillers $500/syringe, HydraFacial $150, Morpheus8 $800 &mdash; on our <a href=\"/pricing/\">price list</a>. Consultations are free and can become treatment the same day.</p><p>From Aurora it&rsquo;s about 15 minutes: Route 43 south to Route 303, then west into Hudson. From Streetsboro it&rsquo;s a straight 10-minute run west on 303 (past the Route 8 interchange, into downtown). Mantua and Garrettsville patients follow Route 82 or 303 west the same way. Free parking is at the door.</p>",
  "treatments":["botox","fillers","laser-hair-removal","hydrafacial","morpheus8","iv-therapy"],
  "directions":"<p><strong>From Aurora (about 8 miles):</strong> take OH-43 South to OH-303, turn right (west) and continue about 6 miles into downtown Hudson. We&rsquo;re at 50 W Streetsboro St, Suite 2, just past the OH-91 / Main St light. Or take OH-82 West to OH-91 South.</p><p><strong>From Streetsboro:</strong> OH-303 West, about 10 minutes. <strong>From Mantua / Garrettsville:</strong> OH-82 or OH-303 West, 20&ndash;25 minutes.</p>",
  "origin_q":"Aurora,+OH",
  "faqs":[
   ("How far is Serene Med Spa from Aurora?","About 8 miles &mdash; roughly 15 minutes via Route 43 to Route 303 West. Streetsboro is about 10 minutes, Mantua about 20."),
   ("What does Botox cost near Aurora?","$11 per unit for Botox, Xeomin and Daxxify; Dysport is $3.99 per unit. A frown-line treatment is usually 20 units. Consultations are free."),
   ("Are the injectors doctors?","Yes. Dr. Shweta Arora and Dr. Robin Arora are board-certified physicians who own the practice and do every consult and injection."),
   ("Do you offer laser hair removal for Aurora and Streetsboro patients?","Yes, with the Alma Soprano Ice Platinum &mdash; virtually painless and safe for all skin tones. Six-session packages are available; call for per-area pricing."),
   ("Can I combine treatments in one visit?","Yes. Many Aurora patients book Botox plus a HydraFacial or SKINVIVE together so one 15-minute drive covers everything."),
   ("Do you see patients from Streetsboro, Mantua and Garrettsville?","Yes &mdash; all of Portage County, plus Twinsburg, Solon, Stow and Kent."),
  ]},
]
