# journal_posts.py — GENERATED by the sereneblog build. Do not edit; add posts in the sereneblog repo.
JOURNAL = [
 {
  "slug": "hormone-optimization-barboursville-wv",
  "url": "https://blog.serenemedspas.com/hormone-optimization-barboursville-wv/",
  "title": "Hormone Imbalance in Barboursville &amp; Huntington: The Signs",
  "cat": "Hormone Optimization",
  "cat_link": "/#services",
  "excerpt": "Tired, foggy, or gaining weight around the middle that won&rsquo;t budge? Those changes often trace back to shifting hormones. Here are the signs to watch for &mdash; and how physician-supervised hormone optimization may help in the Tri-State.",
  "img": "https://blog.serenemedspas.com/img/serene-front-desk.jpg",
  "img_alt": "Reception area at Serene Med Spa, a Certified Bi&ouml;te Provider serving Barboursville and Huntington, WV",
  "date": "2026-09-05",
  "date_h": "September 5, 2026",
  "loc": "barboursville"
 },
 {
  "slug": "hormone-optimization-signs-symptoms",
  "url": "https://blog.serenemedspas.com/hormone-optimization-signs-symptoms/",
  "title": "Signs Your Hormones May Be Out of Balance",
  "cat": "Hormone Optimization",
  "cat_link": "/hormone-optimization/",
  "excerpt": "Tired, foggy, or gaining weight around the middle that won&rsquo;t budge? Those changes often trace back to shifting hormones. Here are the signs to watch for &mdash; and how physician-supervised hormone optimization may help.",
  "img": "https://blog.serenemedspas.com/img/serene-front-desk.jpg",
  "img_alt": "The reception area at Serene Med Spa, a Certified Biote Provider offering hormone optimization in Hudson, OH and Barboursville, WV",
  "date": "2026-09-05",
  "date_h": "September 5, 2026",
  "loc": "hudson"
 },
 {
  "slug": "iv-therapy-immune-support-fall",
  "url": "https://blog.serenemedspas.com/iv-therapy-immune-support-fall/",
  "title": "IV Therapy for Immune Support in Hudson &amp; Barboursville",
  "cat": "IV Therapy",
  "cat_link": "/iv-therapy/",
  "excerpt": "You can&rsquo;t control the season &mdash; but you can give your body better support heading into it. Here&rsquo;s how our $149 physician-led IV drips help you replenish, rehydrate, and support your immune health.",
  "img": "https://blog.serenemedspas.com/img/iv-therapy-blog.jpg",
  "img_alt": "A physician-supervised team member preparing a custom IV vitamin drip at Serene Med Spa",
  "date": "2026-08-24",
  "date_h": "August 24, 2026",
  "loc": "hudson"
 },
 {
  "slug": "male-lip-filler-juvederm-volbella",
  "url": "https://blog.serenemedspas.com/male-lip-filler-juvederm-volbella/",
  "title": "Male Lip Filler with Juv&eacute;derm Volbella",
  "cat": "Lip Filler",
  "cat_link": "/lip-filler/",
  "excerpt": "Lip filler is uncommon for men &mdash; and done well, rarer still. Here&rsquo;s how I added natural volume, corrected side-to-side asymmetry, and kept a masculine lip using Juv&eacute;derm Volbella.",
  "img": "https://blog.serenemedspas.com/img/ba-lip-volbella.jpg",
  "img_alt": "Lip Filler at Serene Med Spa",
  "date": "2026-08-21",
  "date_h": "August 21, 2026",
  "loc": "hudson"
 }
]
