# -*- coding: utf-8 -*-
# journal_block.py — "From the Journal" cross-links from service pages to blog.serenemedspas.com.
# Reads journal_posts.py (generated by the sereneblog build). Usage in gen_pages.py:
#   exec(open("journal_block.py").read())   ->   journal_section(slug, SITE_LOC)
import os as _os, json as _json
try:
    _ns = {}; exec(open("journal_posts.py", encoding="utf-8").read(), _ns); JOURNAL = _ns["JOURNAL"]
except Exception:
    JOURNAL = []

def journal_posts_for(slug, site_loc, limit=3):
    key = "/%s/" % slug.strip("/")
    hits = [p for p in JOURNAL if p["cat_link"] == key]
    if site_loc == "hudson":
        hits = [p for p in hits if p["loc"] == "hudson"]
    else:
        local = {p["cat_link"] for p in hits if p["loc"] == site_loc}
        hits = [p for p in hits if p["loc"] == site_loc or p["cat_link"] not in local]
    return hits[:limit]

def journal_section(slug, site_loc, limit=3):
    posts = journal_posts_for(slug, site_loc, limit)
    if not posts: return ""
    cards = "\n".join('''      <a class="blog-card reveal" href="%s"><div class="blog-thumb"><img loading="lazy" src="%s" alt="%s" width="%s" height="%s"></div><div class="blog-txt"><span class="blog-tag">%s</span><h3>%s</h3><p>%s</p><span class="blog-date">%s</span></div></a>'''
        % (p["url"], p["img"], p["img_alt"], p.get("w",1200), p.get("h",800), p["cat"], p["title"], p["excerpt"], p["date_h"]) for p in posts)
    return '''<section class="tint-mint" id="journal">
  <div class="wrap">
    <div class="section-head reveal"><div class="eyebrow">From the Serene Journal</div><h2>Read More From Dr. Arora</h2></div>
    <div class="blog-grid">
%s
    </div>
    <p style="text-align:center;margin-top:22px"><a class="btn btn-outline" href="https://blog.serenemedspas.com/">Visit The Serene Journal</a></p>
  </div>
</section>''' % cards
