# -*- coding: utf-8 -*-
# labs_data.py — content for the /labs/<test>/ guide pages. Identical in both repos.
# Location-neutral copy; build_labs.py adds the city. Avoid the bare token "OH".
ML = "https://medlineplus.gov/lab-tests/"
ES = ("Endocrine Society testosterone guideline (Bhasin et al., 2018)", "https://academic.oup.com/jcem/article/103/5/1715/4939465")
AUA = ("AUA testosterone deficiency guideline (Mulhall et al., 2018)", "https://www.auajournals.org/doi/10.1016/j.juro.2018.03.115")
WOMEN = ("Global consensus on testosterone therapy for women (Davis et al., 2019)", "https://academic.oup.com/jcem/article/104/10/4660/5556103")
BIOTIN = "If you take biotin (vitamin B7) or a hair, skin and nail supplement, tell us first. The FDA warns that high-dose biotin can interfere with some lab tests, including hormone and thyroid tests."

# label shown on the panel chips -> slug
CHIP_SLUG = {
 "CBC": "cbc", "CMP": "cmp",
 "Estradiol": "estradiol", "Estradiol (LC-MS/MS)": "estradiol",
 "FSH": "fsh", "LH": "lh",
 "Total Testosterone": "total-testosterone", "Total Testosterone (LC-MS/MS)": "total-testosterone",
 "Free Testosterone": "free-testosterone", "Free Testosterone (calculated)": "free-testosterone",
 "SHBG": "shbg", "TSH": "tsh", "Free T3": "free-t3", "Free T4": "free-t4",
 "TPO Antibodies": "tpo-antibodies", "Vitamin B12": "vitamin-b12", "Vitamin D (25-hydroxy)": "vitamin-d",
 "Ferritin": "ferritin", "PSA": "psa", "Prolactin": "prolactin",
}

TESTS = [
 dict(slug="cbc", name="CBC (Complete Blood Count)", seo="CBC Blood Test", short="CBC",
  lead="A complete blood count is one of the most common blood tests in medicine. It counts and sizes the cells in your blood and gives a quick picture of your overall health.",
  measures=["Red blood cells, which carry oxygen", "Hemoglobin, the oxygen-carrying protein", "Hematocrit, the percentage of your blood made up of red cells", "White blood cells, which fight infection", "Platelets, which help your blood clot", "Red cell size (MCV) and related indices"],
  why="A CBC screens for anemia, infection and other blood problems that can cause fatigue. It matters even more with hormone therapy: testosterone can raise red blood cell levels. The Endocrine Society recommends checking hematocrit before testosterone therapy, again at 3&ndash;6 months and then yearly, and pausing treatment if hematocrit rises above 54%.",
  high="A high red cell count or hematocrit can come from dehydration, smoking, sleep apnea, lung disease or testosterone therapy. A high white cell count often points to infection or inflammation.",
  low="Low hemoglobin or hematocrit means anemia, which can come from iron, B12 or folate deficiency, blood loss or chronic disease. Low white cells or platelets need further evaluation.",
  prep="No fasting is needed for a CBC on its own. If it&rsquo;s drawn with a CMP, your provider may ask you to fast.",
  faqs=[("Why do you check a CBC before hormone therapy?", "It screens for anemia and gives a baseline red blood cell level. Testosterone can raise red cell levels, so we compare later results to this baseline."),
        ("What hematocrit level is too high on testosterone?", "The Endocrine Society guideline recommends pausing testosterone therapy if hematocrit rises above 54% until it comes back down."),
        ("How often is a CBC repeated on testosterone?", "Guidelines recommend checking it at 3&ndash;6 months after starting and then yearly, or more often if your physician advises.")],
  sources=[("MedlinePlus: Complete Blood Count (CBC)", ML + "complete-blood-count-cbc/"), ES]),

 dict(slug="cmp", name="CMP (Comprehensive Metabolic Panel)", seo="CMP Blood Test", short="CMP",
  lead="A comprehensive metabolic panel checks 14 substances in your blood that show how your kidneys and liver are working, your blood sugar and your body&rsquo;s chemical balance.",
  measures=["Glucose (blood sugar)", "Kidney function: BUN and creatinine (used to estimate GFR)", "Liver function: ALT, AST, alkaline phosphatase and bilirubin", "Electrolytes: sodium, potassium, chloride and bicarbonate", "Calcium", "Albumin and total protein"],
  why="Before any hormone or wellness treatment, we want to know that your kidneys and liver, the organs that process medications, are healthy. The CMP also gives an early look at blood sugar. As a kidney specialist, Dr. Arora pays close attention to creatinine and GFR, because early kidney changes usually cause no symptoms.",
  high="High glucose can signal prediabetes or diabetes. High creatinine or BUN can point to reduced kidney function or dehydration. High liver enzymes can come from fatty liver, alcohol, medications or other liver conditions.",
  low="Low sodium, potassium or albumin can reflect medications, fluid balance, nutrition or other medical conditions, and are always interpreted with your history.",
  prep="You may be asked to fast (no food or drinks other than water) for several hours before the test so your glucose result is accurate.",
  faqs=[("Do I need to fast for a CMP?", "Often, yes. Fasting for several hours makes the glucose result more accurate. We&rsquo;ll tell you when you book your lab draw."),
        ("What does the CMP show about my kidneys?", "Creatinine and BUN show how well your kidneys filter waste, and creatinine is used to estimate your GFR, a standard measure of kidney function."),
        ("Why is a metabolic panel part of a hormone workup?", "It confirms your kidneys, liver and blood sugar are healthy before treatment and gives a baseline for future comparison.")],
  sources=[("MedlinePlus: Comprehensive Metabolic Panel (CMP)", ML + "comprehensive-metabolic-panel-cmp/")]),

 dict(slug="estradiol", name="Estradiol (E2)", seo="Estradiol Blood Test", short="Estradiol",
  lead="Estradiol is the main form of estrogen. Women and men both need it, for bones, brain, skin and sexual health.",
  measures=["The level of estradiol (E2) in your blood", "In our expanded panels, estradiol is measured by LC-MS/MS, a high-sensitivity method that is more accurate at the low levels seen in men and postmenopausal women"],
  why="In women, estradiol helps show where you are in the menopause transition and guides hormone dosing. In men, estradiol is made from testosterone. Too little can affect bone and libido, and too much can cause breast tenderness or growth. Checking it before and during treatment keeps your hormones in balance.",
  high="In women, high estradiol can reflect the menstrual cycle phase, certain ovarian conditions or hormone therapy. In men, high estradiol can come from higher testosterone levels, excess body fat or certain medications.",
  low="In women, low estradiol is expected after menopause and can cause hot flashes, vaginal dryness, poor sleep and bone loss. In men, very low estradiol can affect bone health and libido.",
  prep="For women who still have periods, your provider may ask you to test on a certain day of your cycle. " + BIOTIN,
  faqs=[("Why do men get estradiol tested?", "Men make estradiol from testosterone. Checking it helps keep treatment balanced and explains symptoms like breast tenderness or low libido."),
        ("What does LC-MS/MS mean?", "It&rsquo;s a laboratory method (liquid chromatography with tandem mass spectrometry) that measures low hormone levels more accurately than standard tests."),
        ("Can one estradiol test tell if I&rsquo;m in menopause?", "Not on its own. Estradiol varies a lot in perimenopause, so we read it together with FSH, your cycle history and your symptoms.")],
  sources=[("MedlinePlus: Estrogen Levels Test", ML + "estrogen-levels-test/")]),

 dict(slug="fsh", name="FSH (Follicle-Stimulating Hormone)", seo="FSH Blood Test", short="FSH",
  lead="FSH is a messenger hormone from the pituitary gland in your brain. It tells the ovaries or testes to do their job.",
  measures=["The level of follicle-stimulating hormone in your blood"],
  why="In women, FSH rises as the ovaries slow down, so it helps show whether you are in perimenopause or menopause. In men, FSH relates to sperm production and helps show whether a hormone problem starts in the testes or in the brain.",
  high="High FSH usually means the ovaries or testes aren&rsquo;t responding fully, as happens in menopause, primary ovarian insufficiency or testicular problems.",
  low="Low FSH can point to a problem with the pituitary gland or hypothalamus, the brain centers that control hormone production.",
  prep="Women who still have periods may be asked to test on a specific cycle day. " + BIOTIN,
  faqs=[("Does a high FSH mean I&rsquo;m in menopause?", "Often, but not always. FSH can swing during perimenopause, so we interpret it with estradiol, your age and your cycle history."),
        ("Why is FSH checked in hormone follow-up labs for women?", "It helps show how your body is responding to treatment alongside estradiol and your symptoms."),
        ("Do men need an FSH test?", "In some cases. It helps evaluate fertility and whether low testosterone starts in the testes or the pituitary.")],
  sources=[("MedlinePlus: Follicle-Stimulating Hormone (FSH) Levels Test", ML + "follicle-stimulating-hormone-fsh-levels-test/")]),

 dict(slug="lh", name="LH (Luteinizing Hormone)", seo="LH Blood Test", short="LH",
  lead="LH is a pituitary hormone. In men, it&rsquo;s the signal that tells the testes to make testosterone. In women, it triggers ovulation.",
  measures=["The level of luteinizing hormone in your blood"],
  why="For men with low testosterone, LH helps find the cause. If LH is high, the testes aren&rsquo;t responding (primary hypogonadism). If LH is low or normal, the signal from the brain may be the issue (secondary hypogonadism). That difference changes the workup and the treatment options.",
  high="High LH in men usually means the testes aren&rsquo;t making enough testosterone despite a strong signal. In women, LH rises around ovulation and after menopause.",
  low="Low LH can point to a pituitary or hypothalamus problem, and can also be seen with stress, extreme exercise, being underweight or outside testosterone use.",
  prep="No fasting is needed. " + BIOTIN,
  faqs=[("Why is LH in the men&rsquo;s expanded panel?", "It shows whether low testosterone starts in the testes or in the brain, which guides further testing and treatment."),
        ("Can testosterone therapy lower LH?", "Yes. Outside testosterone signals the brain to reduce LH, which is why LH is interpreted with your treatment history."),
        ("Do women get LH tested?", "Sometimes, mostly to evaluate cycles, ovulation or menopause.")],
  sources=[("MedlinePlus: Luteinizing Hormone (LH) Levels Test", ML + "luteinizing-hormone-lh-levels-test/"), AUA]),

 dict(slug="total-testosterone", name="Total Testosterone", seo="Total Testosterone Test", short="Total testosterone",
  lead="Total testosterone measures all the testosterone in your blood, both the part bound to proteins and the free part. It&rsquo;s the most common testosterone test.",
  measures=["Bound and free testosterone combined", "In our expanded panels, testosterone is measured by LC-MS/MS for better accuracy, especially at the lower levels found in women"],
  why="In men, it confirms whether testosterone is truly low. The American Urological Association recommends two early-morning tests on separate days, with 300 ng/dL as a reasonable cutoff, plus symptoms, before diagnosing low testosterone. During treatment, it shows whether levels stay in a healthy range. For women on testosterone, experts recommend a baseline level and repeat checks to avoid levels above the normal female range.",
  high="In men, high levels on treatment mean the dose may need adjusting. In women, high testosterone can come from conditions like PCOS or from treatment and may cause acne or unwanted hair growth.",
  low="In men, low testosterone with symptoms (low libido, fatigue, loss of muscle, low mood) may mean testosterone deficiency. In women, levels are naturally much lower and decline with age.",
  prep="Testosterone is highest in the morning, so we draw it early, usually between 7 and 10 a.m. " + BIOTIN,
  faqs=[("Why does testosterone need to be tested in the morning?", "Levels peak in the early morning and drop during the day, so morning tests give the most reliable result."),
        ("Is one low result enough to diagnose low testosterone?", "No. The AUA guideline recommends two early-morning tests on separate days, together with symptoms."),
        ("Why is testosterone checked in women?", "Women need testosterone too. It&rsquo;s checked before treatment and repeated during treatment to keep levels within the normal female range.")],
  sources=[("MedlinePlus: Testosterone Levels Test", ML + "testosterone-levels-test/"), AUA, ES, WOMEN]),

 dict(slug="free-testosterone", name="Free Testosterone", seo="Free Testosterone Test", short="Free testosterone",
  lead="Most testosterone in your blood is bound to proteins. Free testosterone is the small, unbound part your tissues can use right away.",
  measures=["Unbound (free) testosterone", "In our expanded panels it&rsquo;s calculated from total testosterone, SHBG and albumin, a widely used method"],
  why="Two people with the same total testosterone can feel very different, because the amount of binding protein (SHBG) differs. Free testosterone helps explain symptoms when total testosterone is borderline or SHBG is unusually high or low.",
  high="High free testosterone can come from treatment, low SHBG (often seen with insulin resistance or excess weight) or, in women, conditions like PCOS.",
  low="Low free testosterone with symptoms can point to testosterone deficiency even when total testosterone looks normal, especially when SHBG is high.",
  prep="Drawn in the morning with total testosterone. " + BIOTIN,
  faqs=[("What&rsquo;s the difference between total and free testosterone?", "Total includes all testosterone, bound and unbound. Free is only the unbound part that tissues can use directly."),
        ("Why is free testosterone &lsquo;calculated&rsquo;?", "It&rsquo;s estimated from total testosterone, SHBG and albumin, a standard and reliable approach."),
        ("Can my total testosterone be normal and free testosterone low?", "Yes, especially when SHBG is high. That&rsquo;s why we look at all three numbers together.")],
  sources=[("MedlinePlus: Testosterone Levels Test", ML + "testosterone-levels-test/"), ES]),

 dict(slug="shbg", name="SHBG (Sex Hormone-Binding Globulin)", seo="SHBG Blood Test", short="SHBG",
  lead="SHBG is a protein made by the liver that binds testosterone and estradiol in your blood and controls how much is available to your body.",
  measures=["The level of sex hormone-binding globulin in your blood"],
  why="SHBG explains why hormone numbers and symptoms don&rsquo;t always match. High SHBG ties up more hormone, so you may have symptoms even with a &ldquo;normal&rdquo; total testosterone. It&rsquo;s also used to calculate free testosterone.",
  high="SHBG tends to rise with age, higher estrogen, an overactive thyroid, liver conditions and some medications.",
  low="Low SHBG is often seen with insulin resistance, excess weight, an underactive thyroid and, in women, PCOS.",
  prep="No fasting is needed. " + BIOTIN,
  faqs=[("Why does SHBG matter for hormone therapy?", "It changes how much of your testosterone and estradiol is actually available, which helps your physician choose the right dose."),
        ("What lowers SHBG?", "Insulin resistance, excess weight, an underactive thyroid and some conditions like PCOS are common causes."),
        ("Is high SHBG bad?", "Not by itself, but it can mean less free hormone is available, which can explain symptoms.")],
  sources=[("MedlinePlus: SHBG Blood Test", ML + "shbg-blood-test/")]),

 dict(slug="tsh", name="TSH (Thyroid-Stimulating Hormone)", seo="TSH Thyroid Test", short="TSH",
  lead="TSH is made by the pituitary gland and tells your thyroid how much thyroid hormone to make. It&rsquo;s usually the first test for thyroid problems.",
  measures=["The level of thyroid-stimulating hormone in your blood"],
  why="An underactive thyroid causes fatigue, weight gain, feeling cold, brain fog and low mood, the same symptoms many people blame on sex hormones. Checking TSH first helps make sure we treat the right problem.",
  high="High TSH usually means your thyroid isn&rsquo;t making enough hormone (hypothyroidism), so the pituitary is signaling harder.",
  low="Low TSH usually means there&rsquo;s too much thyroid hormone (hyperthyroidism or too high a thyroid medication dose).",
  prep="No fasting is needed. If you take thyroid medication, ask whether to take it before or after your draw. " + BIOTIN,
  faqs=[("Why is a thyroid test part of a hormone panel?", "Thyroid problems cause many of the same symptoms as hormone imbalance, so we rule them out first."),
        ("What does a high TSH mean?", "Usually that the thyroid is underactive and the pituitary is pushing it to make more hormone."),
        ("Is TSH enough on its own?", "It&rsquo;s a strong first test. Free T4, free T3 and TPO antibodies add detail about how the thyroid is working and why.")],
  sources=[("MedlinePlus: TSH (Thyroid-Stimulating Hormone) Test", ML + "tsh-thyroid-stimulating-hormone-test/")]),

 dict(slug="free-t3", name="Free T3 (Triiodothyronine)", seo="Free T3 Thyroid Test", short="Free T3",
  lead="T3 is the most active thyroid hormone. Free T3 is the unbound part that can enter your cells and set your metabolism.",
  measures=["The level of unbound triiodothyronine (T3) in your blood"],
  why="Free T3 adds detail to TSH and free T4, especially when symptoms suggest a thyroid problem or when your thyroid is being treated. It&rsquo;s read together with the other thyroid tests, never alone.",
  high="High T3 can point to an overactive thyroid (hyperthyroidism) or too much thyroid medication.",
  low="Low T3 can be seen with an underactive thyroid, and also with serious illness, very low calorie intake or stress. Normal T3 alone doesn&rsquo;t rule out thyroid disease.",
  prep="No fasting is needed. " + BIOTIN,
  faqs=[("What&rsquo;s the difference between T3 and T4?", "T4 is the main hormone the thyroid makes, and the body converts it into T3, the more active form."),
        ("Why check free T3 if TSH is normal?", "It adds information when symptoms persist or when thyroid treatment is being adjusted."),
        ("Can diet affect T3?", "Yes. Very low calorie intake and significant illness can lower T3.")],
  sources=[("MedlinePlus: Triiodothyronine (T3) Tests", ML + "triiodothyronine-t3-tests/")]),

 dict(slug="free-t4", name="Free T4 (Thyroxine)", seo="Free T4 Thyroid Test", short="Free T4",
  lead="T4 (thyroxine) is the main hormone your thyroid makes. Free T4 is the unbound, active portion in your blood.",
  measures=["The level of unbound thyroxine (T4) in your blood"],
  why="Free T4 is paired with TSH to show whether the thyroid is underactive or overactive and whether the problem starts in the thyroid or the pituitary. A T4 test alone can&rsquo;t diagnose thyroid problems.",
  high="High free T4 can point to hyperthyroidism, including Graves&rsquo; disease, or too much thyroid medication.",
  low="Low free T4 can point to hypothyroidism, including Hashimoto&rsquo;s disease, or, less often, a pituitary problem.",
  prep="No fasting is needed. If you take thyroid medication, ask about timing. " + BIOTIN,
  faqs=[("Why test free T4 with TSH?", "Together they show whether the thyroid is under- or overactive and where the problem starts."),
        ("What does low free T4 with high TSH mean?", "That pattern usually means an underactive thyroid (hypothyroidism)."),
        ("Does thyroid medication change free T4?", "Yes. Free T4 is one of the tests used to fine-tune thyroid medication doses.")],
  sources=[("MedlinePlus: Thyroxine (T4) Test", ML + "thyroxine-t4-test/")]),

 dict(slug="tpo-antibodies", name="TPO Antibodies (Thyroid Peroxidase)", seo="TPO Antibody Test", short="TPO antibodies",
  lead="TPO antibodies are made when the immune system mistakenly targets the thyroid. They&rsquo;re the key marker for autoimmune thyroid disease.",
  measures=["Antibodies against thyroid peroxidase, an enzyme your thyroid uses to make hormone"],
  why="High TPO antibodies are a sign of Hashimoto&rsquo;s disease, the most common cause of an underactive thyroid, and they can show up before thyroid hormone levels change. Knowing this early helps your physician watch your thyroid more closely.",
  high="High TPO antibodies suggest autoimmune thyroid disease, most often Hashimoto&rsquo;s. The higher the level, the more likely an autoimmune thyroid condition.",
  low="A negative or low result makes autoimmune thyroid disease less likely, though it doesn&rsquo;t rule out every thyroid problem.",
  prep="No fasting is needed. " + BIOTIN,
  faqs=[("If my TPO antibodies are high, do I need treatment?", "Not always. If your thyroid hormone levels are normal, your physician may simply monitor them more closely."),
        ("Why is TPO only in the baseline panels?", "Antibody status doesn&rsquo;t usually change quickly, so it&rsquo;s most useful as a one-time or occasional check."),
        ("Is Hashimoto&rsquo;s common?", "Yes. It&rsquo;s the most common cause of hypothyroidism and is more common in women.")],
  sources=[("MedlinePlus: Thyroid Antibodies", ML + "thyroid-antibodies/")]),

 dict(slug="vitamin-b12", name="Vitamin B12", seo="Vitamin B12 Blood Test", short="Vitamin B12",
  lead="Vitamin B12 is needed to make healthy red blood cells and to keep your nerves and brain working well.",
  measures=["The level of vitamin B12 in your blood"],
  why="Low B12 causes fatigue, weakness, poor concentration, low mood and tingling in the hands and feet, symptoms that overlap with hormone imbalance. We check it so a simple deficiency isn&rsquo;t missed.",
  high="High B12 is usually from supplements or injections and is rarely a concern, though very high levels without supplements may need a closer look.",
  low="Low B12 can come from a diet low in animal foods, digestive conditions like celiac or Crohn&rsquo;s disease, weight-loss surgery or certain medications, including metformin and acid reducers.",
  prep="No fasting is usually needed. Tell us if you take B12 supplements or injections.",
  faqs=[("What are signs of low B12?", "Fatigue, weakness, numbness or tingling in the hands and feet, memory problems and mood changes."),
        ("Who is at risk for B12 deficiency?", "People who eat few animal foods, have digestive conditions, have had weight-loss surgery or take certain medications like metformin."),
        ("Do you offer B12 injections?", "Yes, Serene offers vitamin B12 injections when appropriate.")],
  sources=[("MedlinePlus: Vitamin B Test", ML + "vitamin-b-test/")]),

 dict(slug="vitamin-d", name="Vitamin D (25-Hydroxy)", seo="Vitamin D Blood Test", short="Vitamin D",
  lead="The 25-hydroxy vitamin D test is the best way to measure your body&rsquo;s vitamin D stores.",
  measures=["25-hydroxyvitamin D, the form the liver makes and the best marker of vitamin D status"],
  why="Vitamin D supports bone strength, muscle function and immune health, and low levels are common, especially in the winter months. Low vitamin D can add to fatigue and weakness, and it matters for bone health alongside hormones.",
  high="High levels are almost always from taking too much supplement and can be harmful, so doses should be guided by testing.",
  low="Low levels are common in people who get little sun, have darker skin, carry extra weight, have digestive, kidney or liver disease, or have had weight-loss surgery.",
  prep="No fasting is needed. Tell us if you take vitamin D supplements.",
  faqs=[("Why check vitamin D in a hormone panel?", "Vitamin D and hormones both affect bone, muscle and energy, so low vitamin D can add to symptoms and bone risk."),
        ("Can I just take vitamin D without testing?", "Moderate doses are common, but testing helps set the right dose and avoid taking too much."),
        ("Do you offer vitamin D injections?", "Yes, Serene offers vitamin D3 injections when appropriate.")],
  sources=[("MedlinePlus: Vitamin D Test", ML + "vitamin-d-test/")]),

 dict(slug="ferritin", name="Ferritin (Iron Stores)", seo="Ferritin Iron Test", short="Ferritin",
  lead="Ferritin is a protein that stores iron. A ferritin blood test shows how much iron your body has in reserve.",
  measures=["The level of ferritin, which reflects your stored iron"],
  why="Low iron stores can cause fatigue, shortness of breath, dizziness, restless legs and hair shedding, sometimes before anemia shows up on a CBC. That&rsquo;s why ferritin is part of the women&rsquo;s expanded baseline panel, since heavy periods are a common cause of low iron.",
  high="High ferritin can come from inflammation, liver disease, alcohol use, obesity, an overactive thyroid or iron overload conditions.",
  low="Low ferritin usually means low iron stores, often from heavy periods, low iron intake, pregnancy, blood loss or poor absorption.",
  prep="No fasting is usually needed unless it&rsquo;s drawn with other tests that require it.",
  faqs=[("Can low ferritin cause hair loss?", "Low iron stores are a common, treatable contributor to hair shedding in women."),
        ("Can my CBC be normal with low ferritin?", "Yes. Iron stores can drop before anemia appears on a CBC."),
        ("Why can ferritin be high?", "Inflammation is a common reason, so a high ferritin is read together with your history and other labs.")],
  sources=[("MedlinePlus: Ferritin Blood Test", ML + "ferritin-blood-test/")]),

 dict(slug="psa", name="PSA (Prostate-Specific Antigen)", seo="PSA Blood Test", short="PSA",
  lead="PSA is a protein made by the prostate. A PSA blood test is used to check prostate health.",
  measures=["The level of prostate-specific antigen in your blood"],
  why="Testosterone therapy isn&rsquo;t started without looking at prostate health. For many men 55 to 69, the Endocrine Society recommends a PSA check before starting testosterone and again 3&ndash;12 months later, with urology referral if PSA rises by more than 1.4 ng/mL in a year or is confirmed above 4 ng/mL.",
  high="A higher PSA can come from an enlarged prostate (BPH), prostate inflammation, a urinary infection, recent ejaculation or vigorous cycling, and sometimes prostate cancer. An elevated result needs follow-up, not panic.",
  low="A low PSA is generally reassuring. Some medications for an enlarged prostate lower PSA, which your physician takes into account.",
  prep="Avoid ejaculation and vigorous cycling for about 48 hours before the test if you can, and tell us about any prostate medications.",
  faqs=[("Why is PSA checked before testosterone therapy?", "It gives a baseline for prostate health so changes during treatment can be spotted early."),
        ("Does a high PSA mean cancer?", "Not necessarily. BPH, inflammation and infection are common causes. Your physician will guide next steps."),
        ("How often is PSA checked on testosterone?", "For many men 55 to 69, guidelines recommend a check 3&ndash;12 months after starting, then routine screening.")],
  sources=[("MedlinePlus: Prostate-Specific Antigen (PSA) Test", ML + "prostate-specific-antigen-psa-test/"), ES]),

 dict(slug="prolactin", name="Prolactin", seo="Prolactin Blood Test", short="Prolactin",
  lead="Prolactin is a hormone made by the pituitary gland. It&rsquo;s best known for milk production, but it affects sex hormones in both women and men.",
  measures=["The level of prolactin in your blood"],
  why="High prolactin can lower testosterone and libido and cause erectile dysfunction in men, so it&rsquo;s part of the men&rsquo;s expanded baseline panel. Finding it matters because the cause needs its own treatment.",
  high="Common causes include certain medications, an underactive thyroid, kidney disease and prolactinoma, a benign pituitary tumor. Symptoms can include low libido, erectile dysfunction, breast changes and, in women, irregular periods.",
  low="Low prolactin is uncommon and usually not a concern on its own.",
  prep="Prolactin can rise with stress, exercise or nipple stimulation, so a calm, rested morning draw is best. " + BIOTIN,
  faqs=[("Why check prolactin in men with low testosterone?", "High prolactin can suppress testosterone, so it needs to be ruled out before treating."),
        ("What causes high prolactin?", "Medications, an underactive thyroid, kidney disease and benign pituitary tumors are common causes."),
        ("What happens if my prolactin is high?", "Your physician may repeat the test and arrange further evaluation to find the cause.")],
  sources=[("MedlinePlus: Prolactin Levels", ML + "prolactin-levels/")]),
]
TEST_BY_SLUG = {t["slug"]: t for t in TESTS}
