# -*- coding: utf-8 -*-
# Opus Plasma (Alma) — both locations. Added Sept 2026 from Alma's Opus launch kit.
# Hudson-voice copy; the Barboursville build localizes it automatically (bv_localize.py).
# Appends to PAGES4 (defined in pages_data_new3.py, which loads before this file).
def _steps(a,b,c,d): return [("Consultation",a),("Treatment",b),("Results",c),("Maintenance",d)]

_OPUS_RESULTS = '''<section class="results" id="opus-results">
  <div class="wrap">
    <div class="section-head reveal"><div class="eyebrow">Before &amp; After</div><h2>Opus Plasma Results</h2><p>Real Opus Plasma patients after one to three treatments &mdash; eyes, mouth, cheeks, jawline, and the neck.</p></div>
    <div class="res-grid" style="grid-template-columns:repeat(3,1fr)">
      <figure class="res reveal"><img loading="lazy" src="/img/opus-neck-3tx.webp" alt="Opus Plasma before and after: crepey neck, after 3 treatments" width="920" height="323"><figcaption><b>Neck (&ldquo;Turkey Neck&rdquo;)</b><span>After 3 treatments</span></figcaption></figure>
      <figure class="res reveal"><img loading="lazy" src="/img/opus-neck-1tx.webp" alt="Opus Plasma before and after: neck lines and laxity, after 1 treatment" width="838" height="447"><figcaption><b>Neck Lines</b><span>After 1 treatment</span></figcaption></figure>
      <figure class="res reveal"><img loading="lazy" src="/img/opus-cheek-1tx.webp" alt="Opus Plasma before and after: cheek texture and fine lines, after 1 treatment" width="884" height="419"><figcaption><b>Cheek Texture</b><span>After 1 treatment</span></figcaption></figure>
      <figure class="res reveal"><img loading="lazy" src="/img/opus-jawline-2tx.webp" alt="Opus Plasma before and after: jawline and lower face, after 2 treatments" width="857" height="332"><figcaption><b>Jawline &amp; Lower Face</b><span>After 2 treatments</span></figcaption></figure>
      <figure class="res reveal"><img loading="lazy" src="/img/opus-mouth-2tx.webp" alt="Opus Plasma before and after: lines around the mouth, after 2 treatments" width="823" height="266"><figcaption><b>Around the Mouth</b><span>After 2 treatments</span></figcaption></figure>
      <figure class="res reveal"><img loading="lazy" src="/img/opus-eyes-1tx.webp" alt="Opus Plasma before and after: under-eye and crow's feet, after 1 treatment" width="855" height="222"><figcaption><b>Around the Eyes</b><span>After 1 treatment</span></figcaption></figure>
    </div>
    <p class="rev-note">Individual results may vary. Photos courtesy of Alma, Inc. and the treating physicians (Drs. Hsu, Saedi, Griffin; Haley Dermatology) &mdash; not Serene patients.</p>
  </div>
</section>
<section class="tint-mint" id="opus-vs-laser">
  <div class="wrap">
    <div class="section-head reveal"><div class="eyebrow">Plasma vs. Laser</div><h2>Why We Reach for Opus Plasma</h2></div>
    <div class="grid">
      <div class="card reveal"><div class="ico">&#10022;</div><h3>Same Science, New Energy</h3><p>Like fractional laser, Opus creates a grid of micro-injuries that trigger the skin to rebuild. The difference is the energy source: plasma, generated by radiofrequency, instead of light.</p></div>
      <div class="card reveal"><div class="ico">&#10022;</div><h3>Half the Downtime</h3><p>Plasma controls how long energy touches tissue, so there is far less collateral inflammation. A published study found Opus needed about 50% less downtime than fractional laser resurfacing.</p></div>
      <div class="card reveal"><div class="ico">&#10022;</div><h3>Dialed to Your Skin</h3><p>Energy goes up or down per pass, so the same device does a glow-up with a day of pinkness or a deeper resurfacing for etched lines and scars.</p></div>
      <div class="card reveal"><div class="ico">&#10022;</div><h3>Trouble Spots Welcome</h3><p>Neck, around the mouth, around the eyes, and the hands &mdash; the delicate areas that make many lasers nervous are where Opus shines.</p></div>
      <div class="card reveal"><div class="ico">&#10022;</div><h3>15-Minute Treatment</h3><p>Numbing cream goes on for about 30&ndash;45 minutes; the treatment itself is roughly 15 minutes for a full face.</p></div>
      <div class="card reveal"><div class="ico">&#10022;</div><h3>Pairs With Everything</h3><p>Opus layers well with Botox, filler, Skinvive, and PRP for a complete, natural-looking refresh.</p></div>
    </div>
  </div>
</section>'''

PAGES4 += [
{
 "slug":"opus-plasma","crumb":"Opus Plasma","area_kw":"Opus Plasma skin resurfacing",
 "title":"Opus Plasma Skin Resurfacing in Hudson, OH | Serene Med Spa",
 "desc":"Opus Plasma in Hudson, Ohio: fractional plasma resurfacing for wrinkles, texture, acne scars and neck lines, with about half the downtime of laser.",
 "ogtitle":"Opus Plasma Resurfacing in Hudson, OH","ogdesc":"Fractional plasma skin resurfacing for wrinkles, texture, scars, and neck lines — laser-level results with about half the downtime.",
 "proc_name":"Opus Plasma","proc_alt":"Fractional Plasma Radiofrequency Skin Resurfacing",
 "how":"Opus Plasma uses radiofrequency-generated plasma to create a controlled fractional micro-injury in the skin, stimulating the surrounding tissue to repair itself with new collagen, while precisely limiting energy-to-tissue contact time so recovery is roughly half that of fractional laser resurfacing.","body":"Face, Neck, Chest, Hands, Body",
 "eyebrow":"Opus Plasma &middot; Hudson, OH","h1":"Opus Plasma Skin Resurfacing in Hudson, Ohio",
 "hero":"Love laser results, hate laser downtime? Opus Plasma resurfaces wrinkles, texture, scars, and crepey neck skin with fractional plasma energy &mdash; about half the recovery of a laser peel.",
 "trust":["Half the Downtime of Laser","15-Minute Treatment","Face, Neck, Hands &amp; Body","Physician-Performed"],
 "introh2":"Love laser? Try plasma.",
 "introlead":"Fractional skin resurfacing has been the gold standard for repairing aging skin for decades &mdash; but the laser version can mean days or weeks of recovery. Opus Plasma delivers the same fractional-resurfacing science with a different energy source, plasma, that precisely controls how long energy touches the tissue. Less inflammation, faster healing, same collagen-rebuilding result.",
 "intropara":"At Serene Med Spa in Hudson, Opus Plasma is our go-to for skin tone and texture, fine lines and wrinkles, acne scars, stretch marks, and the neck. The treatment takes about 15 minutes after topical numbing, and most patients see 24&ndash;48 hours of mild to moderate redness and swelling at moderate settings &mdash; makeup can go on after a day. You&rsquo;ll notice improvement after one session; two to three treatments deliver the best results. Settings are matched to your Fitzpatrick skin type and individual results vary.",
 "treyebrow":"What It Treats","treh2":"Concerns Opus Plasma Targets",
 "cards":[
   ("Fine Lines &amp; Wrinkles","Soften lines around the eyes and mouth and smooth etched cheeks and forehead."),
   ("Crepey Neck &amp; Chest","Tighten and smooth the &ldquo;turkey neck&rdquo; and sun-crinkled d&eacute;colletage."),
   ("Acne Scars &amp; Texture","Resurface pitted scars, rough texture, and enlarged pores."),
   ("Sun Damage &amp; Tone","Even out blotchy, sun-weathered skin for a clearer, brighter look."),
   ("Stretch Marks &amp; Scars","Blend stretch marks and surgical scars on the body over a short series."),
   ("Hands","Smooth crepey, sun-spotted hands &mdash; one of the most requested Opus areas."),
 ],
 "steps":_steps(
   "We assess your skin, concerns, and downtime tolerance and choose a gentle glow-up setting or a deeper resurfacing plan.",
   "Topical numbing for 30&ndash;45 minutes, then about 15 minutes of treatment. You&rsquo;ll feel warmth; most patients tolerate it easily.",
   "24&ndash;48 hours of pinkness and mild swelling at moderate settings; makeup after a day. Skin looks fresher within a week and keeps improving for months as collagen rebuilds.",
   "Two to three sessions about a month apart give the best result, then a maintenance treatment once or twice a year."),
 "whyh2":"Why choose Serene for Opus Plasma in Hudson",
 "whypara":"Resurfacing results depend on the settings, and the settings depend on the person holding the handpiece. At Serene, Opus Plasma treatments are performed by physicians who match energy to your skin type, your concern, and how much downtime you can afford &mdash; not a one-size preset.",
 "faqh2":"Opus Plasma FAQ",
 "faqs":[
   ("What is Opus Plasma?","A fractional skin-resurfacing treatment that uses radiofrequency-generated plasma instead of laser light. It removes a small fraction of the skin in a micro-grid, prompting the surrounding skin to repair itself with new collagen &mdash; improving tone, texture, wrinkles, scars, and stretch marks."),
   ("How is it different from laser resurfacing?","Same fractional science, different energy. Plasma precisely controls energy-to-tissue contact time, which limits the collateral inflammation that drags out laser recovery. A clinical study found Opus needed about 50% less downtime than fractional laser resurfacing."),
   ("Does it hurt?","You&rsquo;ll feel heat. We apply topical numbing for 30&ndash;45 minutes first and most patients describe treatment as very tolerable. Deeper settings may feel warmer for a few minutes afterward."),
   ("What is the downtime?","At moderate settings, 24&ndash;48 hours of mild to moderate redness and swelling. Makeup can be worn after 24 hours. Aggressive settings for deep lines or scars mean a few more days of peeling."),
   ("How many treatments will I need?","You&rsquo;ll see improvement after one. Best results typically come from two to three treatments spaced about a month apart, followed by yearly maintenance."),
   ("Who is a good candidate?","Anyone from their 20s to their 90s with texture, tone, wrinkle, scar, or laxity concerns. Because the energy is adjustable, Opus works for a subtle glow-up as well as a serious resurfacing, and it can focus on the neck, around the mouth, and around the eyes."),
   ("Can it treat the body?","Yes &mdash; neck, chest, hands, stretch marks, and scars on the body are all common Opus areas."),
 ],
 "related":["morpheus8","botox","fillers"],
 "pricing_html":_OPUS_RESULTS,
 "ctah2":"Ready to resurface without the week off?",
 "ctapara":"Book an Opus Plasma consultation with our Hudson team and we&rsquo;ll match the treatment to your skin and your schedule.",
},
]
