# -*- coding: utf-8 -*-
def _steps(a,b,c,d): return [("Consultation",a),("Treatment",b),("Results",c),("Maintenance",d)]

PAGES3 = [
# ===== LASER SKIN RESURFACING (override laser-skin) =====
{
 "slug":"laser-skin","crumb":"Laser Skin Resurfacing","area_kw":"laser skin resurfacing",
 "title":"Laser Skin Resurfacing in Hudson, OH | CO2, MOXI &amp; More | Serene Med Spa",
 "desc":"Advanced laser skin resurfacing in Hudson, Ohio at Serene Med Spa — CO2, MOXI, Opus Plasma, Cool Peel & PICO Fractional to smooth texture, lines & sun damage. Book today.",
 "ogtitle":"Laser Skin Resurfacing in Hudson, OH","ogdesc":"Smooth texture, fine lines & sun damage with CO2, MOXI, Opus Plasma & PICO resurfacing in Hudson, Ohio.",
 "proc_name":"Laser Skin Resurfacing","proc_alt":"Fractional &amp; Ablative Laser Resurfacing",
 "how":"Fractional and non-ablative lasers deliver precise energy to the skin to remove damaged surface layers and stimulate new collagen for smoother, clearer, firmer-looking skin.","body":"Face, Neck, Chest",
 "eyebrow":"Laser Skin Resurfacing &middot; Hudson, OH","h1":"Laser Skin Resurfacing in Hudson, Ohio",
 "hero":"Smooth texture, soften lines, and erase years of sun damage — with advanced resurfacing lasers matched to your skin and downtime comfort level.",
 "trust":["Physician-Led","Multiple Laser Options","Collagen Renewal","Tailored Downtime"],
 "introh2":"Resurface, renew, and refine",
 "introlead":"Laser resurfacing removes damaged surface skin and jump-starts collagen, so fresh, smoother, more even skin can take its place. With several devices to choose from, we match the treatment to your skin, your goals, and how much downtime fits your life.",
 "intropara":"At Serene Med Spa in Hudson, we offer a full range of resurfacing options — from gentle, no-downtime treatments like MOXI and Cool Peel to deeper resurfacing with Fractional CO2, Opus Plasma, and PICO Fractional. Your physician selects the right device and depth for your skin type and concerns, whether that&rsquo;s fine lines, scarring, texture, or sun damage. A series may be recommended, and individual results vary.",
 "treyebrow":"What It Improves","treh2":"Concerns We Resurface",
 "cards":[
   ("Fine Lines &amp; Wrinkles","Smooth early lines and refresh crepey, aging skin."),
   ("Texture &amp; Scarring","Refine rough texture and soften the look of acne scars."),
   ("Sun Damage","Fade sun spots and years of accumulated UV damage."),
   ("Enlarged Pores","Refine the look of pores for a smoother surface."),
   ("Dullness","Reveal fresh, radiant skin as the surface renews."),
   ("Skin Laxity","Stimulate collagen to support firmer-looking skin."),
 ],
 "steps":_steps(
   "We assess your skin type and concerns and choose the resurfacing laser and depth that fit your goals and downtime.",
   "After numbing as needed, the laser is passed over the treatment area in a comfortable, in-office session.",
   "Downtime depends on the device — from a day of glow to several days of flaking or redness — then smoother, fresher skin emerges.",
   "Some treatments are one-and-done; others build best over a series. We&rsquo;ll plan your schedule and sun protection."),
 "whyh2":"Why choose Serene for laser resurfacing in Hudson",
 "whypara":"Resurfacing results — and safety — depend on matching the right laser and settings to your skin. At Serene, every treatment is physician-selected and supervised, so you get meaningful results appropriate for your skin, right here in Hudson.",
 "faqh2":"Laser Resurfacing FAQ",
 "faqs":[
   ("Which laser is right for me?","It depends on your skin and goals. We offer options from gentle (MOXI, Cool Peel) to deeper (CO2, Opus Plasma, PICO Fractional), and your physician will recommend the best match."),
   ("How much downtime is there?","It varies by device — from none to several days of redness and flaking. We&rsquo;ll tell you exactly what to expect before you book."),
   ("How many treatments will I need?","Some resurfacing is a single session; other approaches build best over a series. We&rsquo;ll tailor a plan to your goals."),
   ("Does it hurt?","We numb the skin as needed and keep you comfortable. Most people tolerate treatment well."),
   ("Is it safe for my skin tone?","Suitability varies by skin type and device. Your physician will evaluate your skin and choose the safest, most effective option for you."),
 ],
 "related":["opus-plasma","harmony-bio-boost","morpheus8"],
 "ctah2":"Ready for smoother, renewed skin?",
 "ctapara":"Book a laser resurfacing consultation with our Hudson physicians and get matched to the right treatment.",
},
# ===== CHIN FILLER =====
{
 "slug":"chin-filler","crumb":"Chin Filler","area_kw":"chin enhancement",
 "title":"Chin Filler in Hudson, OH | Balance &amp; Profile | Serene Med Spa",
 "desc":"Physician-injected chin filler in Hudson, Ohio at Serene Med Spa. Add projection, balance a weak or receding chin, and refine your profile — no surgery. Book today.",
 "ogtitle":"Chin Filler in Hudson, OH","ogdesc":"Balance and project the chin with physician-injected filler in Hudson, Ohio. Refine your profile. Book today.",
 "proc_name":"Chin Filler","proc_alt":"Chin Augmentation with Dermal Filler",
 "how":"A board-certified physician injects dermal filler in the chin to add projection, balance the lower face, and improve the profile.","body":"Chin, Lower Face",
 "eyebrow":"Chin Filler &middot; Hudson, OH","h1":"Chin Filler in Hudson, Ohio",
 "hero":"Balance your profile and strengthen a soft or receding chin — non-surgically — with physician-injected chin filler.",
 "trust":["Physician-Injected","Better Profile","Non-Surgical","Natural Balance"],
 "introh2":"A balanced profile, no surgery",
 "introlead":"The chin anchors your lower face and profile. Chin filler adds subtle projection and definition to balance a weak or receding chin — improving harmony from every angle.",
 "intropara":"At Serene Med Spa in Hudson, our board-certified physicians use filler to strengthen the chin, improve the jaw-to-neck transition, and bring balance to your features — often pairing beautifully with jawline filler. Results are immediate, settle over a week or two, and typically last several months to over a year; individual results vary.",
 "treyebrow":"What Chin Filler Can Do","treh2":"Ways We Enhance",
 "cards":[
   ("Add Projection","Strengthen a soft or receding chin for better balance."),
   ("Refine the Profile","Improve harmony of the chin, lips, and nose in profile."),
   ("Define the Jaw-to-Neck Line","Smooth the transition from chin to neck."),
   ("Balance the Face","Bring proportion to the lower face and overall features."),
   ("Soften a Chin Crease","Ease a deep mental crease below the lip."),
   ("Pairs with Jawline","Combine with jawline filler for a fully sculpted lower face."),
 ],
 "steps":_steps(
   "We study your profile and goals and plan placement for a balanced, natural result.",
   "Filler is injected with numbing for comfort. Appointments take about 30 minutes.",
   "You&rsquo;ll see improved balance right away, with final results settling over one to two weeks.",
   "Chin filler often lasts several months to over a year. We&rsquo;ll plan simple maintenance."),
 "whyh2":"Why choose Serene for chin filler in Hudson",
 "whypara":"Profile balancing takes an understanding of proportion and facial harmony. At Serene, your treatment is performed by board-certified physicians who sculpt for natural balance — right here in Hudson.",
 "faqh2":"Chin Filler FAQ",
 "faqs":[
   ("What does chin filler do?","It adds projection and definition to a soft or receding chin, improving balance and profile without surgery."),
   ("Is it better than a chin implant?","Filler is non-surgical, immediate, and adjustable — a great option to enhance or preview added projection. We&rsquo;ll discuss what suits your goals."),
   ("How long does it last?","Typically several months to over a year, depending on the product. Maintenance keeps your result consistent."),
   ("Is it reversible?","Hyaluronic-acid chin fillers can be dissolved if needed, adding an extra layer of flexibility and safety."),
   ("Is there downtime?","Mild swelling or bruising is possible for a few days. Most people return to their routine right away."),
 ],
 "related":["fillers","botox","morpheus8"],
 "ctah2":"Ready to balance your profile?",
 "ctapara":"Book a chin filler consultation with our Hudson physicians for a naturally balanced result.",
},
# ===== SKINVIVE =====
{
 "slug":"skinvive","crumb":"Skinvive","area_kw":"skin-boosting hydration",
 "title":"SkinVive in Hudson, OH | Injectable Skin Hydration | Serene Med Spa",
 "desc":"SkinVive by Juvéderm in Hudson, Ohio at Serene Med Spa — injectable microdroplets that smooth and hydrate the cheeks for a lasting, dewy glow. Book today.",
 "ogtitle":"SkinVive in Hudson, OH","ogdesc":"Smooth, hydrate, and add glow to the cheeks with SkinVive injectable microdroplets in Hudson, Ohio.",
 "proc_name":"SkinVive","proc_alt":"Injectable Hyaluronic-Acid Skin Booster",
 "how":"A board-certified physician injects microdroplets of smooth hyaluronic acid just beneath the skin of the cheeks to improve smoothness and hydration.","body":"Cheeks, Face",
 "eyebrow":"SkinVive &middot; Hudson, OH","h1":"SkinVive in Hudson, Ohio",
 "hero":"A lit-from-within glow that lasts — SkinVive microdroplet injections smooth and deeply hydrate the skin, without adding volume.",
 "trust":["Physician-Injected","Lasting Hydration","Not a Volumizer","Natural Glow"],
 "introh2":"Hydration and glow, from within",
 "introlead":"SkinVive isn&rsquo;t a filler for volume — it&rsquo;s an injectable skin booster. Tiny microdroplets of smooth hyaluronic acid improve the skin&rsquo;s smoothness and hydration for a fresh, dewy glow that lasts.",
 "intropara":"At Serene Med Spa in Hudson, SkinVive is perfect for anyone who wants glass-skin radiance without changing their facial shape. Our physicians place microdroplets across the cheeks to boost smoothness and hydration you can see and feel. Results build over a couple of weeks and can last for months; individual results vary.",
 "treyebrow":"What SkinVive Does","treh2":"Why People Love It",
 "cards":[
   ("Deep Hydration","Boost the skin&rsquo;s hydration for a healthy, dewy look."),
   ("Smoother Texture","Improve cheek smoothness for a polished finish."),
   ("Lit-From-Within Glow","That coveted &lsquo;glass skin&rsquo; radiance."),
   ("No Added Volume","Enhance skin quality without changing your shape."),
   ("Long-Lasting","Results can last for months from a single treatment."),
   ("Pairs With Everything","A beautiful complement to Botox, filler, and skincare."),
 ],
 "steps":_steps(
   "We confirm SkinVive is right for your goals and skin.",
   "Microdroplets are injected across the cheeks with numbing for comfort — a quick appointment.",
   "Glow and smoothness build over about two weeks as hydration improves.",
   "Results can last for months. We&rsquo;ll plan a simple refresh to maintain your glow."),
 "whyh2":"Why choose Serene for SkinVive in Hudson",
 "whypara":"Skin boosters are all about subtle, natural quality — exactly the kind of refined result our physicians specialize in. At Serene, your SkinVive treatment is physician-injected for a safe, glowing outcome, right here in Hudson.",
 "faqh2":"SkinVive FAQ",
 "faqs":[
   ("Is SkinVive a filler?","Not in the usual sense — it&rsquo;s a skin booster. Instead of adding volume, it improves the skin&rsquo;s smoothness and hydration for a natural glow."),
   ("How long does it last?","Results can last for months from a single treatment. We&rsquo;ll recommend when to refresh."),
   ("When will I see results?","Hydration and glow build over about two weeks after treatment."),
   ("Is there downtime?","Minimal — you may have tiny bumps or mild redness that settle quickly. Most people return to their day right away."),
   ("Can I combine it with other treatments?","Yes — SkinVive pairs beautifully with Botox, filler, and your skincare routine for an overall refresh."),
 ],
 "related":["fillers","botox","morpheus8"],
 "ctah2":"Ready to glow?",
 "ctapara":"Book a SkinVive consultation with our Hudson physicians for lasting hydration and radiance.",
},
# ===== KYBELLA =====
{
 "slug":"kybella","crumb":"Kybella","area_kw":"double-chin fat reduction",
 "title":"Kybella in Hudson, OH | Double-Chin Fat Reduction | Serene Med Spa",
 "desc":"Kybella injections in Hudson, Ohio at Serene Med Spa — an FDA-approved treatment that permanently reduces submental (double-chin) fat without surgery. Book today.",
 "ogtitle":"Kybella in Hudson, OH","ogdesc":"Permanently reduce double-chin fat with FDA-approved Kybella injections in Hudson, Ohio. Book today.",
 "proc_name":"Kybella","proc_alt":"Deoxycholic Acid Injection for Submental Fat",
 "how":"A physician injects deoxycholic acid into the fat beneath the chin, where it destroys fat cells that are then cleared by the body over the following weeks.","body":"Submental (Under Chin)",
 "eyebrow":"Kybella &middot; Hudson, OH","h1":"Kybella in Hudson, Ohio",
 "hero":"Reduce a double chin for good — without surgery. FDA-approved Kybella injections permanently destroy fat beneath the chin.",
 "trust":["FDA-Approved","Permanent Fat Reduction","Non-Surgical","Physician-Injected"],
 "introh2":"Say goodbye to the double chin",
 "introlead":"Kybella is an FDA-approved injectable that targets submental fullness — the &lsquo;double chin.&rsquo; Its active ingredient destroys fat cells, which the body clears away, so once they&rsquo;re gone, they&rsquo;re gone.",
 "intropara":"At Serene Med Spa in Hudson, Kybella offers a non-surgical way to sculpt beneath the chin. Because it permanently reduces fat cells in the treated area, results are lasting once you reach your goal. Most people need a small series of sessions spaced a few weeks apart. Treatment is physician-administered, and individual results vary.",
 "treyebrow":"What to Know","treh2":"Is Kybella Right for You?",
 "cards":[
   ("Targets the Double Chin","Specifically treats fat beneath the chin (submental fullness)."),
   ("Permanent Results","Destroyed fat cells don&rsquo;t return once cleared by the body."),
   ("No Surgery","A non-surgical alternative to liposuction for this area."),
   ("Quick Appointments","A series of short injection sessions, a few weeks apart."),
   ("Physician-Administered","Placed precisely by our board-certified physicians."),
   ("Pairs With Contouring","Combine with skin tightening for a fully sculpted result."),
 ],
 "steps":_steps(
   "We assess the fat beneath your chin and confirm Kybella is a good fit, then plan your number of sessions.",
   "A series of small injections is placed under the chin. Each session is quick.",
   "Some swelling under the chin is expected for several days as fat cells are cleared over the following weeks.",
   "Most people need a few sessions spaced weeks apart. Once you reach your goal, results are lasting."),
 "whyh2":"Why choose Serene for Kybella in Hudson",
 "whypara":"Precise placement and honest candidacy assessment matter with Kybella. At Serene, your treatment is administered by board-certified physicians who&rsquo;ll set realistic expectations and plan the right number of sessions — right here in Hudson.",
 "faqh2":"Kybella FAQ",
 "faqs":[
   ("Is Kybella permanent?","Yes — it destroys fat cells in the treated area, and once your body clears them they don&rsquo;t return. Maintaining a stable weight preserves your result."),
   ("How many sessions will I need?","Most people need a small series spaced a few weeks apart. We&rsquo;ll estimate your number at the consultation based on the amount of fat."),
   ("Is there downtime?","Expect swelling under the chin for several days after each session, and sometimes tenderness or firmness. Most people manage normal activities."),
   ("Does it hurt?","There can be some stinging during injection and swelling afterward. We take steps to keep you comfortable."),
   ("Am I a candidate?","Kybella is best for submental (under-chin) fat with decent skin quality. Our physicians will confirm it&rsquo;s the right option for you."),
 ],
 "related":["fillers","weight-loss","morpheus8"],
 "ctah2":"Ready to lose the double chin?",
 "ctapara":"Book a Kybella consultation with our Hudson physicians and sculpt beneath the chin — no surgery.",
},
# ===== PHOTOFACIAL (BBL/IPL) =====
{
 "slug":"photofacial","crumb":"Photofacial (BBL &amp; IPL)","area_kw":"BBL and IPL photofacials",
 "title":"Photofacial (BBL &amp; IPL) in Hudson, OH | Sun Damage &amp; Redness | Serene Med Spa",
 "desc":"BBL & IPL photofacials in Hudson, Ohio at Serene Med Spa — clear sun spots, redness, and rosacea-prone skin for a brighter, more even complexion. Book today.",
 "ogtitle":"Photofacial (BBL & IPL) in Hudson, OH","ogdesc":"Clear sun spots, redness & uneven tone with BBL and IPL photofacials in Hudson, Ohio. Book today.",
 "proc_name":"Photofacial","proc_alt":"BBL &amp; IPL Intense Pulsed Light Therapy",
 "how":"Broadband and intense pulsed light target excess pigment and redness in the skin, breaking them up so the body can clear them for a clearer, more even complexion.","body":"Face, Neck, Chest, Hands",
 "eyebrow":"BBL &amp; IPL Photofacial &middot; Hudson, OH","h1":"Photofacials in Hudson, Ohio",
 "hero":"Clear sun spots, redness, and uneven tone for a brighter, more even complexion — with BBL and IPL light therapy, little downtime.",
 "trust":["Little Downtime","Sun Damage &amp; Redness","Brighter Tone","Physician-Led"],
 "introh2":"Even, clear, radiant skin",
 "introlead":"A photofacial uses broadband (BBL) or intense pulsed light (IPL) to target the excess pigment and redness that make skin look aged or blotchy — clearing sun spots and calming redness for a brighter, more even complexion.",
 "intropara":"At Serene Med Spa in Hudson, photofacials are a favorite for sun-damaged and redness-prone skin. The light gently targets brown spots and broken-looking capillaries, which fade as your skin clears them over the following days. There&rsquo;s little downtime, a series delivers the best results, and individual results vary.",
 "treyebrow":"What It Treats","treh2":"Concerns We Target",
 "cards":[
   ("Sun &amp; Age Spots","Clear brown spots and freckling from years of sun exposure."),
   ("Facial Redness","Calm diffuse redness and the look of rosacea-prone skin."),
   ("Broken Capillaries","Reduce the appearance of small visible vessels."),
   ("Uneven Tone","Even out blotchy, mottled complexions."),
   ("Dullness","Restore a brighter, clearer, more radiant look."),
   ("Chest &amp; Hands","Treat sun damage beyond the face, too."),
 ],
 "steps":_steps(
   "We assess your skin and concerns and confirm a photofacial (BBL or IPL) is the right fit.",
   "The device is passed over the skin, delivering pulses of light with cooling for comfort.",
   "Brown spots may darken briefly then flake away, and redness fades over the following days.",
   "A series spaced a few weeks apart delivers the best results. We&rsquo;ll plan maintenance and sun protection."),
 "whyh2":"Why choose Serene for photofacials in Hudson",
 "whypara":"Light-based treatments should be matched to your skin type and concerns for safety and results. At Serene, photofacials are physician-supervised and tailored to you, right here in Hudson.",
 "faqh2":"Photofacial FAQ",
 "faqs":[
   ("What&rsquo;s the difference between BBL and IPL?","Both are light therapies that target pigment and redness; BBL is an advanced broadband platform. We&rsquo;ll choose the best option for your skin and goals."),
   ("Is there downtime?","Little — brown spots may darken and flake for a few days, and mild redness can occur. Most people return to their routine right away."),
   ("How many treatments will I need?","A series usually delivers the best results, then periodic maintenance keeps your skin clear. We&rsquo;ll tailor a plan."),
   ("Does it hurt?","Most people describe a quick, warm snap with each pulse. Cooling helps keep treatment comfortable."),
   ("Is it right for my skin tone?","Light therapies aren&rsquo;t suitable for every skin type. Our physicians will assess your skin and recommend the safest, most effective option."),
 ],
 "related":["harmony-bio-boost","morpheus8","fillers"],
 "ctah2":"Ready for clearer, even skin?",
 "ctapara":"Book a photofacial consultation with our Hudson team and fade sun damage and redness.",
},
# ===== LASER TATTOO REMOVAL =====
{
 "slug":"laser-tattoo-removal","crumb":"Laser Tattoo Removal","area_kw":"laser tattoo removal",
 "title":"Laser Tattoo Removal in Hudson, OH | PICO Technology | Serene Med Spa",
 "desc":"Laser tattoo removal in Hudson, Ohio at Serene Med Spa using advanced PICO laser technology to fade unwanted ink safely over a series of sessions. Book today.",
 "ogtitle":"Laser Tattoo Removal in Hudson, OH","ogdesc":"Fade unwanted ink with advanced PICO laser tattoo removal in Hudson, Ohio. Physician-led. Book today.",
 "proc_name":"Laser Tattoo Removal","proc_alt":"Picosecond Laser Tattoo Removal",
 "how":"A picosecond laser delivers ultra-short pulses that shatter tattoo ink into tiny particles the body gradually clears over a series of sessions.","body":"Body, Face",
 "eyebrow":"Laser Tattoo Removal &middot; Hudson, OH","h1":"Laser Tattoo Removal in Hudson, Ohio",
 "hero":"Fade or fully remove unwanted ink with advanced PICO laser technology — safely and precisely, over a series of sessions.",
 "trust":["PICO Technology","For Most Ink Colors","Physician-Led","Gradual &amp; Safe"],
 "introh2":"Rethink that ink",
 "introlead":"Modern picosecond (PICO) lasers shatter tattoo ink into tiny particles your body clears naturally — fading unwanted tattoos more effectively and with fewer sessions than older lasers.",
 "intropara":"At Serene Med Spa in Hudson, we use advanced PICO technology to remove or fade tattoos of various sizes and colors. Because your body clears the ink gradually, removal happens over a series of sessions spaced several weeks apart. The number of sessions depends on the tattoo&rsquo;s size, age, colors, and ink depth; individual results vary.",
 "treyebrow":"What to Know","treh2":"Tattoo Removal at Serene",
 "cards":[
   ("Full Removal or Fading","Erase a tattoo completely or fade it for a cover-up."),
   ("Many Ink Colors","PICO technology addresses a range of colors, including stubborn ones."),
   ("All Sizes","From tiny script to larger pieces — priced by size."),
   ("Gradual &amp; Controlled","Ink clears over a series for a safe, steady result."),
   ("Physician-Led Care","Treatment overseen by our board-certified physicians."),
   ("Aftercare Support","We guide your healing between every session."),
 ],
 "steps":_steps(
   "We evaluate your tattoo&rsquo;s size, colors, and age, and estimate the number of sessions.",
   "The PICO laser is passed over the tattoo with cooling and comfort measures; sessions are quick.",
   "The area heals over the following days, and the ink fades gradually between sessions.",
   "Sessions are spaced several weeks apart to let your body clear the ink. We&rsquo;ll guide aftercare throughout."),
 "whyh2":"Why choose Serene for tattoo removal in Hudson",
 "whypara":"Safe, effective tattoo removal depends on the right laser and settings for your skin and ink. At Serene, removal is physician-led with advanced PICO technology, for controlled, careful results — right here in Hudson.",
 "faqh2":"Laser Tattoo Removal FAQ",
 "faqs":[
   ("How many sessions will it take?","It depends on the tattoo&rsquo;s size, age, colors, and ink depth — often several sessions spaced weeks apart. We&rsquo;ll give you an estimate at your consultation."),
   ("Does it hurt?","Most people describe a snapping sensation. We use cooling and comfort measures, and the area is numbed as needed."),
   ("Can all colors be removed?","PICO technology addresses many colors, including some that were historically difficult. We&rsquo;ll assess your specific ink."),
   ("Is there downtime?","The area may be red, swollen, or blistered for several days after each session. We&rsquo;ll provide complete aftercare instructions."),
   ("Will it leave a scar?","When performed properly with good aftercare, scarring is uncommon, though results vary. We prioritize safe, careful treatment."),
 ],
 "related":["morpheus8","botox","fillers"],
 "ctah2":"Ready to remove that tattoo?",
 "ctapara":"Book a laser tattoo removal consultation with our Hudson team for a safe, PICO-powered plan.",
},
# ===== LASER NAIL FUNGUS =====
{
 "slug":"laser-nail-fungus","crumb":"Laser Nail Fungus","area_kw":"laser nail fungus treatment",
 "title":"Laser Nail Fungus Treatment in Hudson, OH | Clearer Toenails | Serene Med Spa",
 "desc":"Laser toenail fungus treatment in Hudson, Ohio at Serene Med Spa — a quick, no-downtime option to help improve the appearance of fungal toenails. Book today.",
 "ogtitle":"Laser Nail Fungus Treatment in Hudson, OH","ogdesc":"A quick, no-downtime laser option to help improve fungal toenail appearance in Hudson, Ohio. Book today.",
 "proc_name":"Laser Nail Fungus Treatment","proc_alt":"Laser Treatment for Onychomycosis",
 "how":"Laser energy is applied to the nail and nail bed to target the fungus associated with nail infection, supporting clearer, healthier-looking nail growth over time.","body":"Toenails",
 "eyebrow":"Laser Nail Fungus Treatment &middot; Hudson, OH","h1":"Laser Nail Fungus Treatment in Hudson, Ohio",
 "hero":"A quick, no-downtime laser option to help improve the appearance of stubborn fungal toenails — no messy topicals or oral medication required.",
 "trust":["No Downtime","Quick Sessions","No Medication","Physician-Led"],
 "introh2":"Toward clearer, healthier-looking nails",
 "introlead":"Fungal toenails are stubborn and slow to improve. Laser treatment targets the fungus in and around the nail, supporting clearer, healthier-looking nail growth over time — without topicals or oral medication.",
 "intropara":"At Serene Med Spa in Hudson, laser nail treatment is a simple, no-downtime option for discolored, thickened fungal toenails. Because nails grow slowly, visible improvement appears gradually as the healthy nail grows out, and a series of sessions is usually recommended. Results vary from person to person, and we&rsquo;ll set honest expectations at your visit.",
 "treyebrow":"What to Know","treh2":"Laser Nail Treatment",
 "cards":[
   ("Targets the Fungus","Laser energy targets the fungus associated with nail infection."),
   ("No Downtime","Return to your day right after a quick session."),
   ("No Pills or Polishes","An alternative to oral antifungals and daily topicals."),
   ("Thick, Discolored Nails","For yellowed, thickened, brittle-looking toenails."),
   ("Gradual Improvement","Clearer nail appears as the healthy nail grows out."),
   ("Physician-Led","Treatment overseen by our medical team."),
 ],
 "steps":_steps(
   "We examine your nails, discuss your history, and confirm laser treatment is a reasonable option for you.",
   "Laser energy is applied to the affected toenails in a quick, comfortable session with no downtime.",
   "Because nails grow slowly, improvement appears gradually as healthy nail grows in over the following months.",
   "A series of sessions is usually recommended, along with good nail and footwear hygiene to support results."),
 "whyh2":"Why choose Serene for laser nail treatment in Hudson",
 "whypara":"Fungal nails need realistic expectations and consistent care. At Serene, treatment is physician-led with honest guidance on what laser can and can&rsquo;t do, and how to support your results — right here in Hudson.",
 "faqh2":"Laser Nail Fungus FAQ",
 "faqs":[
   ("Does laser cure nail fungus?","Laser can help improve the appearance of fungal nails and support clearer growth, but results vary and it isn&rsquo;t guaranteed. We&rsquo;ll set honest expectations for your case."),
   ("How soon will I see results?","Because nails grow slowly, visible improvement appears gradually over months as the healthy nail grows in."),
   ("How many sessions will I need?","A series of sessions is usually recommended. We&rsquo;ll outline a plan at your consultation."),
   ("Is there downtime?","None — the treatment is quick and you can return to your day right away."),
   ("Does it hurt?","Most people feel only a warming sensation during treatment and tolerate it well."),
 ],
 "related":["morpheus8","botox","fillers"],
 "ctah2":"Ready for clearer toenails?",
 "ctapara":"Book a laser nail fungus consultation with our Hudson team and get an honest, tailored plan.",
},
# ===== MEDICAL FACIALS =====
{
 "slug":"medical-facials","crumb":"Medical Facials","area_kw":"medical-grade facials",
 "title":"Medical Facials in Hudson, OH | Acne, Dermaplane &amp; More | Serene Med Spa",
 "desc":"Medical-grade facials in Hudson, Ohio at Serene Med Spa — acne facials, classic facials, dermaplaning, microdermabrasion & more for healthy, glowing skin. Book today.",
 "ogtitle":"Medical Facials in Hudson, OH","ogdesc":"Acne facials, dermaplaning, microdermabrasion & more medical-grade facials in Hudson, Ohio. Book today.",
 "proc_name":"Medical Facial","proc_alt":"Medical-Grade Facial &amp; Skincare Treatment",
 "how":"A trained provider cleanses, exfoliates, extracts, and treats the skin with medical-grade products and techniques customized to your skin type and goals.","body":"Face, Neck",
 "eyebrow":"Medical Facials &middot; Hudson, OH","h1":"Medical Facials in Hudson, Ohio",
 "hero":"Healthy, glowing skin starts here — medical-grade facials customized to your skin, from deep-cleansing acne facials to dermaplaning and microdermabrasion.",
 "trust":["Medical-Grade","Customized to You","Relaxing &amp; Effective","No Downtime"],
 "introh2":"Facials with real skin-health benefits",
 "introlead":"A medical facial goes beyond pampering — combining professional cleansing, exfoliation, and medical-grade products to genuinely improve your skin, all in a relaxing treatment.",
 "intropara":"At Serene Med Spa in Hudson, our facial menu is customized to your skin. Choose a deep-cleansing acne facial, a smoothing dermaplane, resurfacing microdermabrasion, or a nourishing classic facial — each tailored to your goals with no downtime. Regular facials keep your skin clear, smooth, and glowing, and pair perfectly with your injectable and laser plan.",
 "treyebrow":"Our Facial Menu","treh2":"Facials We Offer",
 "cards":[
   ("Acne Facial","Deep-cleanse and clarify breakout-prone, congested skin."),
   ("Classic Facial","A relaxing, customized cleanse, exfoliation, and hydration."),
   ("Dermaplane","Gently remove dead skin and peach fuzz for a smooth, glowing finish."),
   ("Microdermabrasion","Resurface the skin&rsquo;s surface for brighter, smoother texture."),
   ("Pumpkin Enzyme &amp; More","Enzyme and specialty facials for extra brightening and renewal."),
   ("High-Frequency &amp; Add-Ons","Boost your facial with targeted treatments for your skin."),
 ],
 "steps":_steps(
   "We look at your skin and goals and recommend the facial (or combination) that fits best.",
   "You relax while your provider cleanses, exfoliates, extracts, and treats your skin with medical-grade products.",
   "Skin looks instantly clearer, smoother, and more radiant — with no downtime.",
   "Regular facials, often monthly, keep your skin healthy, clear, and glowing over time."),
 "whyh2":"Why choose Serene for facials in Hudson",
 "whypara":"A great facial should improve your skin, not just feel nice. At Serene, our facials use medical-grade products in a physician-led practice, and connect to the rest of your skincare plan — right here in Hudson.",
 "faqh2":"Medical Facials FAQ",
 "faqs":[
   ("Which facial should I choose?","It depends on your skin and goals — acne, dullness, texture, or maintenance. Your provider will recommend the right facial or combination at your visit."),
   ("Is there downtime?","No — medical facials are gentle and you can return to your day (or evening out) right away with glowing skin."),
   ("How often should I get a facial?","Many people enjoy a facial monthly to maintain clear, healthy skin. We&rsquo;ll suggest a rhythm for your skin."),
   ("What is dermaplaning?","It gently removes dead skin and fine &lsquo;peach fuzz&rsquo; for an instantly smooth, glowing finish and better product absorption."),
   ("Are facials good for acne?","Yes — our acne facials deep-cleanse and clarify congested skin, and we can build them into an overall acne plan."),
 ],
 "related":["morpheus8","fillers","botox"],
 "ctah2":"Ready to glow?",
 "ctapara":"Book a facial with our Hudson team and give your skin a medical-grade refresh.",
},
# ===== HYPERPIGMENTATION & MELASMA =====
{
 "slug":"hyperpigmentation","crumb":"Hyperpigmentation &amp; Melasma","area_kw":"pigmentation and melasma care",
 "title":"Hyperpigmentation &amp; Melasma Treatment in Hudson, OH | Serene Med Spa",
 "desc":"Physician-led hyperpigmentation & melasma treatment in Hudson, Ohio at Serene Med Spa — a customized plan to fade dark spots and even your tone safely. Book today.",
 "ogtitle":"Hyperpigmentation & Melasma Treatment in Hudson, OH","ogdesc":"Fade dark spots and even your tone with a customized, physician-led pigmentation plan in Hudson, Ohio.",
 "proc_name":"Hyperpigmentation Treatment","proc_alt":"Melasma &amp; Pigmentation Correction",
 "how":"A physician designs a customized plan — which may combine medical-grade topicals, chemical peels, and appropriate laser or light therapy — to reduce excess pigment and even the skin tone.","body":"Face, Neck, Chest, Hands",
 "eyebrow":"Hyperpigmentation &amp; Melasma &middot; Hudson, OH","h1":"Hyperpigmentation &amp; Melasma Treatment in Hudson, Ohio",
 "hero":"Fade dark spots, melasma, and uneven tone with a customized, physician-led plan — done safely, because pigmentation is easy to make worse if treated wrong.",
 "trust":["Physician-Led","Customized Plan","Safe for Your Skin","Real, Lasting Results"],
 "introh2":"An even, clear complexion — done right",
 "introlead":"Dark spots, melasma, and uneven tone are among the most common — and most tricky — skin concerns. The wrong treatment can make pigment worse, which is why a customized, physician-led plan matters.",
 "intropara":"At Serene Med Spa in Hudson, we treat pigmentation with a tailored combination that may include medical-grade topicals, chemical peels, and carefully chosen laser or light therapy — always matched to your skin type. Melasma in particular is a chronic, manageable condition rather than a one-time fix, so consistency and sun protection are essential. Results build over time, and individual results vary.",
 "treyebrow":"What We Address","treh2":"Pigment Concerns We Treat",
 "cards":[
   ("Sun &amp; Age Spots","Fade brown spots from years of sun exposure."),
   ("Melasma","Manage stubborn, hormone-related patches with a careful plan."),
   ("Post-Acne Marks","Improve dark marks left behind after breakouts."),
   ("Uneven Tone","Even out blotchy, mottled complexions."),
   ("Custom Combinations","Topicals, peels, and light therapy chosen for your skin."),
   ("Sun-Smart Maintenance","A plan to protect your results long-term."),
 ],
 "steps":_steps(
   "We assess the type and cause of your pigmentation and your skin type, then design a safe, customized plan.",
   "Your plan may combine medical-grade topicals, peels, and carefully selected laser or light treatments over time.",
   "Pigment fades gradually as your plan takes effect — with careful attention to not overtreating.",
   "Pigmentation, especially melasma, needs ongoing maintenance and daily sun protection to keep results."),
 "whyh2":"Why choose Serene for pigmentation care in Hudson",
 "whypara":"Pigmentation is one of the easiest concerns to worsen with the wrong approach. At Serene, your plan is physician-led and matched to your skin type for safe, effective, lasting improvement — right here in Hudson.",
 "faqh2":"Hyperpigmentation &amp; Melasma FAQ",
 "faqs":[
   ("Can melasma be cured?","Melasma is a chronic, manageable condition rather than a one-time cure. With a careful plan and sun protection, we can significantly improve and control it."),
   ("How is pigmentation treated?","Usually a combination — medical-grade topicals, chemical peels, and carefully chosen laser or light therapy — customized to your skin type and the type of pigment."),
   ("Why does the wrong treatment make it worse?","Aggressive heat or lasers can trigger more pigment in some skin types. That&rsquo;s why physician-led, skin-type-appropriate care matters so much."),
   ("How long until I see results?","Pigment fades gradually over weeks to months. Consistency with your plan and sun protection is key."),
   ("Do I really need sunscreen?","Absolutely — daily sun protection is essential to fade pigment and prevent it from returning. We&rsquo;ll recommend the right products."),
 ],
 "related":["harmony-bio-boost","morpheus8","fillers"],
 "ctah2":"Ready for a clearer, even complexion?",
 "ctapara":"Book a pigmentation consultation with our Hudson physicians for a safe, customized plan.",
},
# ===== EVOLVE X =====
{
 "slug":"evolve-x","crumb":"Evolve X","area_kw":"non-invasive body contouring",
 "title":"Evolve X in Hudson, OH | Non-Invasive Body Contouring | Serene Med Spa",
 "desc":"Evolve X body contouring in Hudson, Ohio at Serene Med Spa — non-invasive radiofrequency and muscle stimulation to tighten skin, tone muscle & refine your figure. Book today.",
 "ogtitle":"Evolve X in Hudson, OH","ogdesc":"Tighten, tone & refine with non-invasive Evolve X body contouring in Hudson, Ohio. No downtime. Book today.",
 "proc_name":"Evolve X","proc_alt":"Non-Invasive Radiofrequency Body Remodeling",
 "how":"Evolve X uses radiofrequency energy and electrical muscle stimulation to tighten skin and tone muscle in targeted body areas without surgery.","body":"Abdomen, Thighs, Buttocks, Arms, Flanks",
 "eyebrow":"Evolve X &middot; Body Contouring &middot; Hudson, OH","h1":"Evolve X in Hudson, Ohio",
 "hero":"Tighten skin, tone muscle, and refine your figure — no surgery, no needles, no downtime — with the all-in-one Evolve X body platform.",
 "trust":["Non-Invasive","No Downtime","Tighten &amp; Tone","Hands-Free"],
 "introh2":"Contour and tighten, hands-free",
 "introlead":"Evolve X is an advanced, non-invasive body platform that combines radiofrequency skin tightening with muscle-toning energy — remodeling and refining targeted areas while you relax.",
 "intropara":"At Serene Med Spa in Hudson, Evolve X treats areas like the abdomen, thighs, buttocks, and arms to firm loose skin and tone the underlying muscle — all hands-free and without downtime. It&rsquo;s a great complement to a healthy lifestyle and pairs well with our other body treatments. Results build over a series of sessions, and individual results vary.",
 "treyebrow":"Where It Works","treh2":"Areas We Treat",
 "cards":[
   ("Abdomen","Tighten skin and tone the core for a firmer midsection."),
   ("Thighs","Smooth and firm the inner and outer thighs."),
   ("Buttocks","Tone and firm for a smoother, lifted look."),
   ("Arms","Firm the upper arms for a more toned appearance."),
   ("Flanks","Refine the sides of the waist."),
   ("Skin &amp; Muscle Together","Tighten skin and tone muscle in one hands-free session."),
 ],
 "steps":_steps(
   "We review your goals and target areas and design an Evolve X plan for you.",
   "Applicators are placed on the treatment area; you relax during the comfortable, hands-free session.",
   "Skin firms and muscle tones gradually over the weeks following your sessions; results vary.",
   "A series delivers the best results, with periodic maintenance to keep your figure refined."),
 "whyh2":"Why choose Serene for Evolve X in Hudson",
 "whypara":"Body treatments work best with realistic goals and a thoughtful plan. At Serene, Evolve X is physician-led and tailored to you, with honest guidance on what to expect — right here in Hudson.",
 "faqh2":"Evolve X FAQ",
 "faqs":[
   ("Is Evolve X a weight-loss treatment?","No — it tightens skin and tones muscle in targeted areas to refine your figure, and complements a healthy lifestyle rather than replacing weight loss."),
   ("Is there downtime?","None — Evolve X is non-invasive and hands-free, so most people return to their day right away."),
   ("How many sessions will I need?","A series usually delivers the best results. We&rsquo;ll recommend a plan for your goals and areas."),
   ("How is it different from EMSCULPT NEO?","Both are non-invasive body treatments; Evolve X combines skin tightening with muscle toning across larger areas. We&rsquo;ll help you choose or combine them."),
   ("When will I see results?","Results build gradually over the weeks after your sessions as skin firms and muscle tones."),
 ],
 "related":["weight-loss","morpheus8","fillers"],
 "ctah2":"Ready to tighten and tone?",
 "ctapara":"Book an Evolve X consultation with our Hudson team and refine your figure — no downtime.",
},
# ===== BODYTITE =====
{
 "slug":"bodytite","crumb":"BodyTite","area_kw":"minimally invasive body contouring",
 "title":"BodyTite in Hudson, OH | Minimally-Invasive Laser Lipo | Serene Med Spa",
 "desc":"BodyTite in Hudson, Ohio at Serene Med Spa — minimally-invasive radiofrequency-assisted liposuction that reduces fat and tightens skin with less downtime than surgery. Book today.",
 "ogtitle":"BodyTite in Hudson, OH","ogdesc":"Reduce fat and tighten skin with minimally-invasive BodyTite in Hudson, Ohio — physician-performed. Book today.",
 "proc_name":"BodyTite","proc_alt":"Radiofrequency-Assisted Liposuction",
 "how":"BodyTite uses radiofrequency energy delivered through a small cannula to melt and remove fat while simultaneously tightening the overlying skin, through tiny incisions under local anesthesia.","body":"Abdomen, Flanks, Arms, Thighs, Back",
 "eyebrow":"BodyTite &middot; Laser Lipo &middot; Hudson, OH","h1":"BodyTite in Hudson, Ohio",
 "hero":"Reduce stubborn fat AND tighten skin at the same time — with minimally-invasive BodyTite, physician-performed, with far less downtime than traditional surgery.",
 "trust":["Fat + Skin Tightening","Minimally Invasive","Physician-Performed","Less Downtime"],
 "introh2":"Fat reduction with skin tightening",
 "introlead":"BodyTite is a minimally-invasive body contouring procedure that uses radiofrequency energy to melt and remove fat while tightening the skin above it — addressing something traditional liposuction can&rsquo;t: loose skin.",
 "intropara":"At Serene Med Spa in Hudson, BodyTite is performed by our physicians through tiny incisions under local anesthesia, targeting stubborn areas like the abdomen, flanks, arms, and thighs. Because it tightens as it reduces fat, results look smooth and refined. It involves some recovery and compression garments; candidacy is determined at consultation, and individual results vary.",
 "treyebrow":"Where It Works","treh2":"Areas We Contour",
 "cards":[
   ("Abdomen","Reduce stubborn belly fat and tighten the overlying skin."),
   ("Flanks &amp; Back","Sculpt the waistline and smooth the back."),
   ("Arms","Reduce upper-arm fullness and firm loose skin."),
   ("Thighs","Refine and tighten the inner and outer thighs."),
   ("Fat + Skin Together","Tightens skin as it removes fat — unlike traditional lipo."),
   ("Natural, Smooth Results","Refined contours performed by our physicians."),
 ],
 "steps":_steps(
   "Your physician evaluates your areas and skin, reviews the procedure and recovery, and confirms candidacy.",
   "Under local anesthesia, radiofrequency energy melts and removes fat while tightening skin through tiny incisions.",
   "You&rsquo;ll wear a compression garment and have some swelling and downtime; contours refine over the following weeks and months.",
   "Skin continues to tighten over several months. We provide full aftercare and follow-up."),
 "whyh2":"Why choose Serene for BodyTite in Hudson",
 "whypara":"BodyTite is a medical procedure that belongs in skilled physician hands. At Serene, it&rsquo;s physician-performed with careful candidacy assessment and honest guidance on recovery and results — right here in Hudson.",
 "faqh2":"BodyTite FAQ",
 "faqs":[
   ("Is BodyTite surgery?","It&rsquo;s a minimally-invasive procedure done through tiny incisions under local anesthesia — less invasive than traditional surgery, but still a medical procedure with recovery."),
   ("How is it different from liposuction?","Traditional liposuction only removes fat; BodyTite also tightens the skin using radiofrequency, which helps avoid the loose skin lipo can leave behind."),
   ("What is the downtime?","Expect swelling, bruising, and a compression garment for a period after treatment. Your physician will review your specific recovery."),
   ("When will I see results?","You&rsquo;ll notice contour changes early, with skin tightening and final results developing over several months."),
   ("Am I a candidate?","BodyTite suits people with stubborn fat and mild-to-moderate skin laxity. Your physician will confirm at consultation."),
 ],
 "related":["weight-loss","morpheus8","fillers"],
 "ctah2":"Ready to reduce fat and tighten skin?",
 "ctapara":"Book a BodyTite consultation with our Hudson physicians to see if it&rsquo;s right for you.",
},
# ===== FACETITE =====
{
 "slug":"facetite","crumb":"FaceTite","area_kw":"minimally invasive facial contouring",
 "title":"FaceTite in Hudson, OH | Minimally-Invasive Facial Contouring | Serene Med Spa",
 "desc":"FaceTite in Hudson, Ohio at Serene Med Spa — minimally-invasive radiofrequency contouring that tightens skin and refines the lower face & neck without a facelift. Book today.",
 "ogtitle":"FaceTite in Hudson, OH","ogdesc":"Tighten and refine the lower face & neck with minimally-invasive FaceTite in Hudson, Ohio. Book today.",
 "proc_name":"FaceTite","proc_alt":"Radiofrequency-Assisted Facial Contraction",
 "how":"FaceTite delivers radiofrequency energy beneath the skin through a tiny entry point to melt small fat pockets and tighten the skin of the lower face and neck under local anesthesia.","body":"Lower Face, Jawline, Neck",
 "eyebrow":"FaceTite &middot; Hudson, OH","h1":"FaceTite in Hudson, Ohio",
 "hero":"Tighten a softening jawline and neck without a facelift — minimally-invasive FaceTite delivers dramatic contraction with far less downtime than surgery.",
 "trust":["Facelift Alternative","Minimally Invasive","Physician-Performed","Less Downtime"],
 "introh2":"Lift and tighten — without a facelift",
 "introlead":"FaceTite offers powerful skin tightening for the lower face and neck through a tiny entry point, using radiofrequency to contract skin and melt small fat pockets — results that approach surgery, without the scars.",
 "intropara":"At Serene Med Spa in Hudson, FaceTite is performed by our physicians under local anesthesia to refine the jawline, jowls, and neck. It&rsquo;s ideal for patients with mild-to-moderate laxity who want more than a non-invasive device can offer, but aren&rsquo;t ready for a facelift. There&rsquo;s some downtime; results develop over months, and individual results vary.",
 "treyebrow":"Where It Works","treh2":"Areas We Tighten",
 "cards":[
   ("Jowls","Firm and refine early jowling along the jawline."),
   ("Jawline","Sharpen and tighten a softening jaw."),
   ("Neck","Tighten loose skin and refine the neck contour."),
   ("Under-Chin","Reduce small fat pockets and tighten beneath the chin."),
   ("Facelift Alternative","Meaningful tightening without surgical incisions."),
   ("Physician-Performed","Delivered by our board-certified physicians."),
 ],
 "steps":_steps(
   "Your physician evaluates your skin laxity and goals and confirms FaceTite is the right option.",
   "Under local anesthesia, radiofrequency energy is delivered beneath the skin through a tiny entry point.",
   "Expect some swelling and downtime; tightening develops over the following weeks and months.",
   "Skin continues to firm over several months. We provide complete aftercare and follow-up."),
 "whyh2":"Why choose Serene for FaceTite in Hudson",
 "whypara":"FaceTite is an advanced procedure requiring physician skill and judgment. At Serene, it&rsquo;s physician-performed with careful candidacy and honest expectations — right here in Hudson.",
 "faqh2":"FaceTite FAQ",
 "faqs":[
   ("Is FaceTite a facelift?","No — it&rsquo;s a minimally-invasive alternative that tightens skin through a tiny entry point under local anesthesia, with far less downtime than a surgical facelift."),
   ("What&rsquo;s the downtime?","Expect swelling and some downtime after treatment. Your physician will review your specific recovery timeline."),
   ("Who is a good candidate?","People with mild-to-moderate laxity of the lower face and neck who want more than non-invasive devices offer. Your physician will confirm."),
   ("When will I see results?","You&rsquo;ll see early improvement, with tightening continuing to develop over several months."),
   ("Can it be combined with other treatments?","Yes — it&rsquo;s often paired with other treatments for a comprehensive result. We&rsquo;ll design your plan."),
 ],
 "related":["morpheus8","fillers","botox"],
 "ctah2":"Ready to tighten — without a facelift?",
 "ctapara":"Book a FaceTite consultation with our Hudson physicians to see if it&rsquo;s right for you.",
},
# ===== FORMA =====
{
 "slug":"forma","crumb":"Forma Skin Tightening","area_kw":"non-invasive skin tightening",
 "title":"Forma Skin Tightening in Hudson, OH | No-Downtime RF | Serene Med Spa",
 "desc":"Forma skin tightening in Hudson, Ohio at Serene Med Spa — comfortable, no-downtime radiofrequency that firms and smooths the face & neck over a series. Book today.",
 "ogtitle":"Forma Skin Tightening in Hudson, OH","ogdesc":"Firm and smooth the face & neck with no-downtime Forma radiofrequency in Hudson, Ohio. Book today.",
 "proc_name":"Forma Skin Tightening","proc_alt":"Non-Invasive Radiofrequency Skin Tightening",
 "how":"Forma delivers controlled radiofrequency heat to the deeper layers of the skin to stimulate collagen and tighten the face and neck without downtime.","body":"Face, Jawline, Neck, Under-Eye",
 "eyebrow":"Forma Skin Tightening &middot; Hudson, OH","h1":"Forma Skin Tightening in Hudson, Ohio",
 "hero":"A warm, relaxing treatment that firms and smooths the face and neck — no needles, no downtime — with results that build over a series.",
 "trust":["No Downtime","Comfortable &amp; Relaxing","Stimulates Collagen","Physician-Led"],
 "introh2":"Firmer, smoother skin — comfortably",
 "introlead":"Forma uses gentle, controlled radiofrequency heat to stimulate collagen deep in the skin, firming and smoothing the face and neck. It feels like a warm massage, with zero downtime.",
 "intropara":"At Serene Med Spa in Hudson, Forma is a favorite for a natural, non-invasive lift — great for the jawline, jowls, neck, and delicate under-eye area. Because it works by building collagen, results appear gradually and improve with a series of sessions. It&rsquo;s comfortable, requires no downtime, and pairs well with injectables and other treatments; individual results vary.",
 "treyebrow":"Where It Works","treh2":"Areas We Tighten",
 "cards":[
   ("Jawline &amp; Jowls","Firm and refine a softening lower face."),
   ("Neck","Smooth and tighten loose skin on the neck."),
   ("Under-Eye","Gently firm the delicate skin around the eyes."),
   ("Forehead &amp; Brow","Support a smoother, more lifted upper face."),
   ("Overall Firmness","Build collagen for firmer, smoother skin over time."),
   ("Zero Downtime","Relax during treatment and return to your day."),
 ],
 "steps":_steps(
   "We assess your skin and goals and plan a Forma series for the areas you want to firm.",
   "A handpiece delivers comfortable, warming radiofrequency across the treatment area — like a warm massage.",
   "Skin feels tighter soon after, with firming that builds over the following weeks as collagen forms.",
   "A series delivers the best results, followed by periodic maintenance to keep your skin firm."),
 "whyh2":"Why choose Serene for Forma in Hudson",
 "whypara":"Non-invasive tightening rewards consistency and a good plan. At Serene, Forma is physician-led and tailored to your skin, with realistic guidance on results — right here in Hudson.",
 "faqh2":"Forma FAQ",
 "faqs":[
   ("Does Forma hurt?","No — most people find it deeply relaxing, like a warm massage. There are no needles and no downtime."),
   ("How many sessions will I need?","Because it works by building collagen, a series usually delivers the best results, then periodic maintenance keeps them."),
   ("Is there downtime?","None — you can return to your day right away, sometimes with a healthy flush that quickly fades."),
   ("When will I see results?","Skin can feel tighter soon after, with firming continuing to build over the weeks following each session."),
   ("How is it different from FaceTite?","Forma is non-invasive with no downtime and builds gradually; FaceTite is a minimally-invasive procedure with stronger, faster tightening. We&rsquo;ll help you choose."),
 ],
 "related":["morpheus8","fillers","botox"],
 "ctah2":"Ready for firmer, smoother skin?",
 "ctapara":"Book a Forma consultation with our Hudson team for comfortable, no-downtime tightening.",
},
# ===== LIPOSUCTION & FAT TRANSFER =====
{
 "slug":"liposuction","crumb":"Liposuction &amp; Fat Transfer","area_kw":"liposuction and fat transfer",
 "title":"Liposuction with Fat Transfer in Hudson, OH | Serene Med Spa",
 "desc":"Physician-performed liposuction with fat transfer in Hudson, Ohio at Serene Med Spa — remove stubborn fat and restore volume where you want it. Book a consultation.",
 "ogtitle":"Liposuction with Fat Transfer in Hudson, OH","ogdesc":"Remove stubborn fat and restore volume with physician-performed liposuction & fat transfer in Hudson, Ohio.",
 "proc_name":"Liposuction with Fat Transfer","proc_alt":"Liposuction and Autologous Fat Grafting",
 "how":"A physician removes stubborn fat from targeted areas via liposuction and can purify and reinject a portion of that fat to restore volume elsewhere.","body":"Abdomen, Flanks, Thighs, Arms, Face",
 "eyebrow":"Liposuction &amp; Fat Transfer &middot; Hudson, OH","h1":"Liposuction with Fat Transfer in Hudson, Ohio",
 "hero":"Remove stubborn fat where you don&rsquo;t want it — and restore natural volume where you do — with physician-performed liposuction and fat transfer.",
 "trust":["Physician-Performed","Sculpt + Restore","Uses Your Own Fat","Personalized Plan"],
 "introh2":"Sculpt one area, restore another",
 "introlead":"Liposuction permanently removes stubborn pockets of fat that resist diet and exercise. With fat transfer, a portion of that fat can be purified and reinjected to restore natural volume elsewhere — sculpting and replenishing in one plan.",
 "intropara":"At Serene Med Spa in Hudson, liposuction with fat transfer is performed by our physicians for stubborn areas like the abdomen, flanks, and thighs, with the option to restore volume where age or weight changes have taken it. This is a medical procedure with recovery and compression garments. Candidacy and approach are determined at consultation, and individual results vary.",
 "treyebrow":"What It Can Do","treh2":"Sculpt &amp; Restore",
 "cards":[
   ("Abdomen &amp; Flanks","Remove stubborn belly and waistline fat for a smoother contour."),
   ("Thighs","Refine and slim the inner and outer thighs."),
   ("Arms","Reduce upper-arm fullness."),
   ("Restore Volume","Reinject purified fat to replenish areas that have lost fullness."),
   ("Natural Results","Uses your own fat — no synthetic implants."),
   ("Personalized Plan","Tailored to your body and goals by our physicians."),
 ],
 "steps":_steps(
   "Your physician evaluates your areas and goals, reviews the procedure and recovery, and confirms candidacy.",
   "Stubborn fat is removed via liposuction; if you&rsquo;re transferring fat, it&rsquo;s purified and reinjected to restore volume.",
   "Expect swelling, bruising, and compression garments during recovery; contours refine over the following weeks and months.",
   "Final results develop over several months. We provide full aftercare and follow-up throughout."),
 "whyh2":"Why choose Serene for liposuction in Hudson",
 "whypara":"Liposuction and fat transfer are medical procedures that require physician skill and judgment. At Serene, they&rsquo;re physician-performed with careful candidacy assessment and honest guidance — right here in Hudson.",
 "faqh2":"Liposuction &amp; Fat Transfer FAQ",
 "faqs":[
   ("Is the fat removal permanent?","The fat cells removed during liposuction don&rsquo;t return. Maintaining a stable weight preserves your results."),
   ("What is fat transfer?","A portion of your own removed fat is purified and reinjected to restore natural volume in another area — no synthetic implants."),
   ("What is the recovery like?","Expect swelling, bruising, and compression garments for a period. Your physician will review your specific recovery at consultation."),
   ("Is it a weight-loss procedure?","No — it sculpts stubborn areas and refines contour; it&rsquo;s not a substitute for overall weight loss."),
   ("Am I a candidate?","Candidacy depends on your health, areas, and goals. Your physician will confirm whether it&rsquo;s right for you at consultation."),
 ],
 "related":["weight-loss","morpheus8","fillers"],
 "ctah2":"Ready to sculpt and restore?",
 "ctapara":"Book a liposuction & fat transfer consultation with our Hudson physicians to build your plan.",
},
# ===== LIPOMELT (RED LIGHT) =====
{
 "slug":"lipomelt","crumb":"Lipomelt (Red Light)","area_kw":"red light body contouring",
 "title":"Lipomelt Red Light Therapy in Hudson, OH | Non-Invasive Slimming | Serene Med Spa",
 "desc":"Lipomelt red light therapy in Hudson, Ohio at Serene Med Spa — a relaxing, non-invasive light treatment to support inch loss and body contouring. Book today.",
 "ogtitle":"Lipomelt Red Light Therapy in Hudson, OH","ogdesc":"Relaxing, non-invasive Lipomelt red light body contouring in Hudson, Ohio. No downtime. Book today.",
 "proc_name":"Lipomelt Red Light Therapy","proc_alt":"Low-Level Light Therapy for Body Contouring",
 "how":"Pads emitting specific wavelengths of red and near-infrared light are placed on the body to support the release of stored contents from fat cells as part of a healthy-lifestyle plan.","body":"Abdomen, Thighs, Hips, Arms",
 "eyebrow":"Lipomelt &middot; Red Light Therapy &middot; Hudson, OH","h1":"Lipomelt Red Light Therapy in Hudson, Ohio",
 "hero":"A relaxing, non-invasive light treatment to support inch loss and body contouring — no needles, no downtime, no discomfort.",
 "trust":["Non-Invasive","No Downtime","Relaxing","Lifestyle Complement"],
 "introh2":"Effortless, relaxing body support",
 "introlead":"Lipomelt uses specific wavelengths of red and near-infrared light, delivered through comfortable pads, to support your body-contouring goals — all while you simply relax.",
 "intropara":"At Serene Med Spa in Hudson, Lipomelt is a gentle, non-invasive option that complements a healthy diet, exercise, and your other body treatments. It&rsquo;s completely comfortable with no downtime. Lipomelt supports body-contouring goals as part of a healthy lifestyle rather than acting as a weight-loss treatment on its own; a series works best and individual results vary.",
 "treyebrow":"What to Know","treh2":"Lipomelt at Serene",
 "cards":[
   ("Abdomen &amp; Waist","Support contouring around the midsection."),
   ("Thighs &amp; Hips","Target common trouble zones."),
   ("Arms","Support toning of the upper arms."),
   ("Completely Relaxing","Simply rest while the light pads do the work."),
   ("No Downtime","Return to your day right after your session."),
   ("Lifestyle Complement","Best paired with healthy habits and other body treatments."),
 ],
 "steps":_steps(
   "We review your goals and confirm Lipomelt fits your body-contouring plan.",
   "Comfortable light pads are placed on the target areas while you relax for the session.",
   "Best results come with a series alongside healthy habits; results build over time and vary by person.",
   "We&rsquo;ll recommend a session schedule and lifestyle tips to support and maintain your results."),
 "whyh2":"Why choose Serene for Lipomelt in Hudson",
 "whypara":"We&rsquo;ll always be honest about what a treatment can and can&rsquo;t do. At Serene, Lipomelt is offered as a supportive, non-invasive complement to a healthy lifestyle and your other body treatments — right here in Hudson.",
 "faqh2":"Lipomelt FAQ",
 "faqs":[
   ("Is Lipomelt a weight-loss treatment?","No — it&rsquo;s a supportive body-contouring treatment that works best alongside a healthy diet, exercise, and your other treatments."),
   ("Is there downtime?","None — Lipomelt is completely non-invasive and relaxing, and you can return to your day right away."),
   ("How many sessions will I need?","A series delivers the best results. We&rsquo;ll recommend a schedule based on your goals."),
   ("Does it hurt?","Not at all — most people find it warm and relaxing."),
   ("When will I see results?","Results build gradually over a series and are best supported by healthy habits. Individual results vary."),
 ],
 "related":["weight-loss","morpheus8","fillers"],
 "ctah2":"Ready for a relaxing body boost?",
 "ctapara":"Book a Lipomelt session with our Hudson team and support your body-contouring goals.",
},
# ===== PEPTIDE THERAPY =====
{
 "slug":"peptide-therapy","crumb":"Peptide Therapy","area_kw":"peptide and vitamin therapy",
 "title":"Peptide Therapy &amp; Vitamin Injections in Hudson, OH | Serene Med Spa",
 "desc":"Physician-supervised peptide therapy & vitamin injections in Hudson, Ohio at Serene Med Spa — personalized wellness support with B12, NAD+, Sermorelin & more. Book today.",
 "ogtitle":"Peptide Therapy in Hudson, OH","ogdesc":"Physician-supervised peptide therapy & vitamin injections in Hudson, Ohio. Personalized wellness. Book today.",
 "proc_name":"Peptide Therapy","proc_alt":"Peptide &amp; Vitamin Injection Wellness",
 "how":"After evaluation, a physician develops a personalized, medically supervised plan using peptides and vitamin injections selected for your wellness goals where clinically appropriate.","body":"Systemic",
 "eyebrow":"Peptide Therapy &amp; Vitamin Injections &middot; Hudson, OH","h1":"Peptide Therapy in Hudson, Ohio",
 "hero":"Personalized, physician-supervised peptide and vitamin injection therapies to support your energy, recovery, and overall wellness goals.",
 "trust":["Physician-Supervised","Personalized Plans","Quality Products","Ongoing Guidance"],
 "introh2":"Targeted wellness, physician-guided",
 "introlead":"Peptides and vitamin injections have become popular tools for supporting energy, recovery, metabolism, and overall wellness. Done right, they&rsquo;re personalized and physician-supervised — not one-size-fits-all.",
 "intropara":"At Serene Med Spa in Hudson, peptide therapy begins with an evaluation so your plan fits your goals and health. We offer options such as B12, NAD+, Sermorelin, BPC-157, glutathione, and more, selected where clinically appropriate and monitored by our physicians. These therapies support general wellness goals; they are individualized medical care, and appropriateness and results depend on your health and are determined with your physician.",
 "treyebrow":"Common Goals","treh2":"How People Use It",
 "cards":[
   ("Energy &amp; Vitality","Support everyday energy and combat fatigue."),
   ("Recovery &amp; Performance","Support recovery and active-lifestyle goals."),
   ("Metabolism &amp; Wellness","Support metabolic and overall wellness goals."),
   ("Skin, Hair &amp; Glow","Options like glutathione for beauty-from-within support."),
   ("Cognitive Support","Options such as NAD+ for wellness and vitality."),
   ("Personalized Protocols","Selected and dosed for you by our physicians."),
 ],
 "steps":_steps(
   "We review your goals and health history and, where appropriate, recommend a personalized peptide or vitamin plan.",
   "Your physician selects and doses your therapy; many options are quick in-office or at-home injections.",
   "We monitor how you feel and adjust your plan over time for a safe, effective approach.",
   "Peptide and vitamin therapy is often ongoing. We provide regular follow-up and guidance."),
 "whyh2":"Why choose Serene for peptide therapy in Hudson",
 "whypara":"Peptide and vitamin therapies should be individualized and physician-supervised — never guesswork. At Serene, your plan is guided by board-certified physicians who&rsquo;ll be honest about what&rsquo;s appropriate for you, right here in Hudson.",
 "faqh2":"Peptide Therapy FAQ",
 "faqs":[
   ("What are peptides?","Peptides are short chains of amino acids used to support various wellness goals. We offer selected options where clinically appropriate under physician supervision."),
   ("Is it physician-supervised?","Yes — at Serene, peptide and vitamin therapies are evaluated, selected, and monitored by our board-certified physicians as individualized care."),
   ("What options do you offer?","Options include B12, NAD+, Sermorelin, BPC-157, glutathione, and more — chosen based on your goals and health."),
   ("Are results guaranteed?","No — these therapies support general wellness goals, and results are individual and depend on your health. Your physician will set realistic expectations."),
   ("How do I start?","It begins with a consultation to review your goals and health, so we can recommend an appropriate, personalized plan."),
 ],
 "related":["weight-loss","iv-therapy","hormone-optimization"] if False else ["weight-loss","morpheus8","botox"],
 "ctah2":"Ready to support your wellness goals?",
 "ctapara":"Book a peptide therapy consultation with our Hudson physicians for a personalized, guided plan.",
},
# ===== MENS SEXUAL WELLNESS =====
{
 "slug":"mens-sexual-wellness","crumb":"Men's Sexual Wellness","area_kw":"men's sexual wellness care",
 "title":"Men's Sexual Wellness in Hudson, OH | Alma Duo &amp; P-Renew PRP | Serene Med Spa",
 "desc":"Physician-led men's sexual wellness in Hudson, Ohio at Serene Med Spa — discreet, non-surgical options including Alma Duo acoustic wave therapy and P-Renew PRP (also known as the P-Shot&reg;). Book today.",
 "ogtitle":"Men's Sexual Wellness in Hudson, OH","ogdesc":"Discreet, physician-led men's sexual wellness in Hudson, Ohio — Alma Duo & P-Renew PRP. Book today.",
 "proc_name":"Men's Sexual Wellness","proc_alt":"Acoustic Wave Therapy &amp; PRP Treatments",
 "how":"After a private consultation, a physician may recommend options such as Alma Duo acoustic wave therapy or PRP-based treatments to support men's sexual wellness where appropriate.","body":"Men's Health",
 "eyebrow":"Men's Sexual Wellness &middot; Hudson, OH","h1":"Men's Sexual Wellness in Hudson, Ohio",
 "hero":"Discreet, physician-led options to support men's sexual wellness and confidence — non-surgical, drug-free approaches in a comfortable, private setting.",
 "trust":["Physician-Led","Discreet &amp; Private","Non-Surgical","Personalized"],
 "introh2":"Confidential, physician-led care",
 "introlead":"Concerns around sexual wellness are common and deserve real, discreet medical care. We offer non-surgical, drug-free options that support men&rsquo;s sexual wellness and confidence — always in a private, judgment-free setting.",
 "intropara":"At Serene Med Spa in Hudson, men&rsquo;s sexual wellness options include Alma Duo acoustic wave therapy and P-Renew PRP &mdash; our physician-administered platelet-rich plasma (PRP) treatment, also known as the P-Shot&reg; &mdash; selected after a private consultation. Our board-certified physicians will discuss your goals and whether these options are appropriate for you. These treatments aim to support wellness; candidacy and results are individual and determined with your physician.",
 "treyebrow":"Our Options","treh2":"How We Can Help",
 "cards":[
   ("Alma Duo","Non-invasive acoustic wave therapy in a quick, comfortable session."),
   ("P-Renew PRP","Our physician-administered PRP treatment using components from your own blood &mdash; also known as the P-Shot&reg;."),
   ("Non-Surgical","Drug-free, non-surgical approaches to support wellness."),
   ("Private &amp; Discreet","Care in a comfortable, judgment-free environment."),
   ("Physician-Led","Guided by our board-certified physicians."),
   ("Personalized","A plan based on your goals and health."),
 ],
 "steps":_steps(
   "We start with a private, judgment-free consultation to understand your goals and health.",
   "If appropriate, your physician recommends options such as Alma Duo or P-Renew PRP and explains what to expect.",
   "Treatments are typically quick and comfortable; some approaches build over a series of sessions.",
   "We&rsquo;ll plan any follow-up and maintenance and remain available for your questions."),
 "whyh2":"Why choose Serene for men's wellness in Hudson",
 "whypara":"Sexual wellness deserves discreet, honest, physician-led care. At Serene, your consultation and treatment are private and guided by board-certified physicians who&rsquo;ll be candid about what&rsquo;s appropriate for you — right here in Hudson.",
 "faqh2":"Men's Sexual Wellness FAQ",
 "faqs":[
   ("What options do you offer?","Options include Alma Duo acoustic wave therapy and P-Renew PRP &mdash; our PRP-based treatment, also known as the P-Shot&reg; &mdash; recommended after a private consultation based on your needs."),
   ("Is it discreet?","Absolutely — your consultation and care are private and judgment-free. Your comfort and confidentiality are a priority."),
   ("Is it surgical?","No — these are non-surgical, drug-free approaches. Your physician will explain each option and what to expect."),
   ("What is P-Renew PRP (also known as the P-Shot&reg;)?","It&rsquo;s our physician-administered treatment using platelet-rich plasma (PRP) drawn from your own blood. Your physician will discuss whether it&rsquo;s appropriate for you."),
   ("Will it work for me?","Candidacy and results are individual. Our physicians will give you an honest assessment during your consultation."),
 ],
 "related":["alma-duo","hormone-optimization","weight-loss"] if False else ["weight-loss","morpheus8","botox"],
 "ctah2":"Ready to talk, privately?",
 "ctapara":"Book a discreet men's sexual wellness consultation with our Hudson physicians.",
},
# ===== WOMENS SEXUAL WELLNESS =====
{
 "slug":"womens-sexual-wellness","crumb":"Women's Sexual Wellness","area_kw":"women's sexual wellness care",
 "title":"Women's Sexual Wellness in Hudson, OH | V-Renew PRP, VTone &amp; More | Serene Med Spa",
 "desc":"Physician-led women's sexual wellness in Hudson, Ohio at Serene Med Spa — discreet, non-surgical options including V-Renew PRP (also known as the O-Shot&reg;), VTone, FormaV and Morpheus8 V. Book today.",
 "ogtitle":"Women's Sexual Wellness in Hudson, OH","ogdesc":"Discreet, physician-led women's sexual wellness in Hudson, Ohio — V-Renew PRP, VTone, FormaV. Book today.",
 "proc_name":"Women's Sexual Wellness","proc_alt":"Vaginal Wellness &amp; Rejuvenation Treatments",
 "how":"After a private consultation, a physician may recommend options such as V-Renew PRP (a platelet-rich plasma treatment also known as the O-Shot&reg;), VTone, FormaV, or Morpheus8 V to support women's intimate wellness where appropriate.","body":"Women's Health",
 "eyebrow":"Women's Sexual Wellness &middot; Hudson, OH","h1":"Women's Sexual Wellness in Hudson, Ohio",
 "hero":"Discreet, physician-led options to support intimate wellness, comfort, and confidence — non-surgical approaches in a private, judgment-free setting.",
 "trust":["Physician-Led","Discreet &amp; Private","Non-Surgical","Personalized"],
 "introh2":"Comfortable, confidential, physician-led",
 "introlead":"Intimate wellness concerns — from comfort and confidence to changes after childbirth or menopause — are common and deserve real, discreet medical care. We offer non-surgical options that support women&rsquo;s intimate wellness in a private setting.",
 "intropara":"At Serene Med Spa in Hudson, women&rsquo;s sexual wellness options include V-Renew PRP &mdash; our physician-administered platelet-rich plasma (PRP) treatment, also known as the O-Shot&reg; &mdash; along with VTone, FormaV, and Morpheus8 V, selected after a private consultation. Our board-certified physicians will discuss your goals and whether these options are appropriate for you. These treatments aim to support wellness; candidacy and results are individual and determined with your physician.",
 "treyebrow":"Our Options","treh2":"How We Can Help",
 "cards":[
   ("V-Renew PRP","Our physician-administered PRP treatment using components from your own blood &mdash; also known as the O-Shot&reg;."),
   ("VTone","Intravaginal muscle stimulation to support pelvic-floor tone."),
   ("FormaV &amp; Morpheus8 V","Radiofrequency-based options to support intimate wellness."),
   ("After Childbirth or Menopause","Support for changes many women experience."),
   ("Private &amp; Discreet","Care in a comfortable, judgment-free environment."),
   ("Physician-Led","Guided by our board-certified physicians."),
 ],
 "steps":_steps(
   "We start with a private, judgment-free consultation to understand your goals and health.",
   "If appropriate, your physician recommends options such as V-Renew PRP, VTone, or FormaV and explains what to expect.",
   "Treatments are typically comfortable; some approaches build over a series of sessions.",
   "We&rsquo;ll plan any follow-up and maintenance and remain available for your questions."),
 "whyh2":"Why choose Serene for women's wellness in Hudson",
 "whypara":"Intimate wellness deserves discreet, honest, physician-led care. At Serene, your consultation and treatment are private and guided by board-certified physicians who&rsquo;ll be candid about what&rsquo;s appropriate for you — right here in Hudson.",
 "faqh2":"Women's Sexual Wellness FAQ",
 "faqs":[
   ("What options do you offer?","Options include V-Renew PRP &mdash; our PRP-based treatment, also known as the O-Shot&reg; &mdash; along with VTone, FormaV, and Morpheus8 V, recommended after a private consultation based on your needs."),
   ("Is it discreet?","Absolutely — your consultation and care are private and judgment-free. Your comfort and confidentiality are a priority."),
   ("Is it surgical?","No — these are non-surgical approaches. Your physician will explain each option and what to expect."),
   ("What is V-Renew PRP (also known as the O-Shot&reg;)?","It&rsquo;s our physician-administered treatment using platelet-rich plasma (PRP) drawn from your own blood. Your physician will discuss whether it&rsquo;s appropriate for you."),
   ("Will it work for me?","Candidacy and results are individual. Our physicians will give you an honest assessment during your consultation."),
 ],
 "related":["alma-duo","hormone-optimization","weight-loss"] if False else ["weight-loss","morpheus8","botox"],
 "ctah2":"Ready to talk, privately?",
 "ctapara":"Book a discreet women's sexual wellness consultation with our Hudson physicians.",
},
# ===== SPIDER VEINS =====
{
 "slug":"spider-veins","crumb":"Spider Vein Treatment","area_kw":"spider vein treatment",
 "title":"Spider Vein Treatment in Hudson, OH | Sclerotherapy (Asclera) | Serene Med Spa",
 "desc":"Spider vein treatment in Hudson, Ohio at Serene Med Spa — physician-performed sclerotherapy with Asclera to fade unwanted leg veins. Book your consultation today.",
 "ogtitle":"Spider Vein Treatment in Hudson, OH","ogdesc":"Fade unwanted leg veins with physician-performed sclerotherapy (Asclera) in Hudson, Ohio. Book today.",
 "proc_name":"Spider Vein Treatment","proc_alt":"Sclerotherapy with Asclera",
 "how":"A physician injects a sclerosing solution (Asclera) into spider and small reticular veins, causing them to collapse and fade as the body reabsorbs them over the following weeks.","body":"Legs",
 "eyebrow":"Spider Vein Treatment &middot; Hudson, OH","h1":"Spider Vein Treatment in Hudson, Ohio",
 "hero":"Fade unwanted spider veins and feel confident in your skin again — with physician-performed sclerotherapy using Asclera.",
 "trust":["Physician-Performed","Little Downtime","Proven Sclerotherapy","Confidence-Boosting"],
 "introh2":"Smoother, clearer legs",
 "introlead":"Spider veins — those small red, blue, or purple veins on the legs — are harmless but can affect your confidence. Sclerotherapy with Asclera is a proven, physician-performed treatment that fades them over time.",
 "intropara":"At Serene Med Spa in Hudson, our physicians inject Asclera directly into spider and small reticular veins, causing them to collapse and gradually fade as your body reabsorbs them. Treatment is quick with little downtime, though a series is sometimes needed for the best clearance. Compression may be recommended afterward, and individual results vary.",
 "treyebrow":"What to Know","treh2":"Sclerotherapy at Serene",
 "cards":[
   ("Spider Veins","Fade small red, blue, and purple veins on the legs."),
   ("Small Reticular Veins","Treat the slightly larger feeder veins as appropriate."),
   ("Physician-Performed","Injected precisely by our board-certified physicians."),
   ("Little Downtime","Return to most activities right away, with some guidance."),
   ("Gradual Fading","Veins collapse and fade over the following weeks."),
   ("Confidence Back","Feel comfortable showing your legs again."),
 ],
 "steps":_steps(
   "We examine your veins and health history and confirm sclerotherapy is a good option for you.",
   "Asclera is injected into the target veins in a quick, in-office session.",
   "Treated veins collapse and fade over the following weeks as your body reabsorbs them.",
   "Compression may be recommended afterward, and a series is sometimes needed for the best result."),
 "whyh2":"Why choose Serene for spider vein treatment in Hudson",
 "whypara":"Sclerotherapy is a medical treatment best performed by experienced physicians. At Serene, it&rsquo;s physician-performed with careful assessment and honest expectations — right here in Hudson.",
 "faqh2":"Spider Vein Treatment FAQ",
 "faqs":[
   ("What is sclerotherapy?","It&rsquo;s a proven treatment in which a solution (Asclera) is injected into spider veins, causing them to collapse and fade as your body reabsorbs them."),
   ("How many treatments will I need?","Many people need a series for the best clearance, depending on how many veins are present. We&rsquo;ll estimate at your consultation."),
   ("Is there downtime?","Little — most people return to their day, though we may recommend compression and avoiding certain activities briefly."),
   ("Does it hurt?","Most people feel only minor stinging during injection. The treatment is quick and well tolerated."),
   ("When will I see results?","Treated veins fade gradually over the following weeks. Some veins may need more than one session."),
 ],
 "related":["weight-loss","morpheus8","fillers"],
 "ctah2":"Ready for clearer legs?",
 "ctapara":"Book a spider vein consultation with our Hudson physicians and fade unwanted veins.",
},
{
 "slug":"ultherapy",
 "title":"Ultherapy in Hudson, OH | Ultrasound Skin Lifting | Serene Med Spa",
 "desc":"Ultherapy PRIME in Hudson, Ohio at Serene Med Spa — non-invasive ultrasound that lifts the brow, chin & neck and smooths the décolleté, with no downtime. Book today.",
 "ogtitle":"Ultherapy in Hudson, OH",
 "ogdesc":"Non-invasive ultrasound lifting of the brow, chin & neck in Hudson, Ohio. No surgery, no downtime. Book today.",
 "proc_name":"Ultherapy",
 "proc_alt":"Micro-Focused Ultrasound Skin Lifting",
 "how":"Ultherapy uses micro-focused ultrasound energy to stimulate collagen deep in the skin, lifting and tightening the brow, chin, and neck and improving lines on the décolleté, guided by real-time ultrasound imaging.",
 "body":"Brow, Chin, Neck, Décolleté",
 "crumb":"Ultherapy",
 "eyebrow":"Ultherapy PRIME &middot; Hudson, OH",
 "h1":"Ultherapy in Hudson, Ohio",
 "hero":"The FDA-cleared treatment that lifts and tightens the brow, chin, and neck using ultrasound &mdash; no surgery, no downtime, and results that build naturally over time.",
 "trust":["FDA-Cleared Lifting","No Surgery, No Downtime","Builds Your Own Collagen","Physician-Led"],
 "introh2":"Lift and tighten &mdash; without surgery",
 "introlead":"Ultherapy is the gold standard in non-invasive lifting. Using micro-focused ultrasound, it stimulates your body&rsquo;s own collagen deep beneath the surface to lift the brow, chin, and neck and smooth the décolleté.",
 "intropara":"Because Ultherapy uses ultrasound imaging, your provider can actually see the layers of tissue being treated &mdash; so energy goes precisely where it does the most good. Most people need just one session, with no downtime, and results that develop gradually over two to three months and can last a year or more.",
 "treyebrow":"Where It Works",
 "treh2":"What Ultherapy Lifts",
 "cards":[
   ("Brow","A subtle lift that opens and refreshes the eyes."),
   ("Under the Chin","Tighten and define a softening jawline and submental area."),
   ("Neck","Firm loose, crepey skin for a smoother, more lifted neck."),
   ("Décolleté","Soften lines and wrinkles on the chest."),
 ],
 "steps":[
   ("Consultation","We assess your skin laxity and goals to confirm Ultherapy is right for you and map your treatment areas."),
   ("Ultrasound Imaging","Real-time imaging lets your provider see beneath the skin and target the ideal depth precisely."),
   ("Treatment","Focused ultrasound is delivered to stimulate collagen. Most sessions take 30&ndash;90 minutes depending on the area."),
   ("Results","Skin lifts and tightens gradually over two to three months as new collagen forms &mdash; and can last a year or more."),
 ],
 "whyh2":"Why choose Serene for Ultherapy in Hudson",
 "whypara":"Ultherapy at Serene is physician-led, performed by our medical team on the advanced Ultherapy PRIME platform &mdash; the newest evolution of the gold standard in non-invasive lifting. We take the time to confirm you&rsquo;re a good candidate, set honest expectations, and deliver a natural-looking lift tailored to your face.",
 "faqh2":"Ultherapy FAQ",
 "faqs":[
   ("Is Ultherapy surgery?","No. Ultherapy is completely non-invasive &mdash; no incisions and no downtime. It uses focused ultrasound to lift and tighten from within by stimulating your own collagen."),
   ("Who is a good candidate?","Ultherapy works best for people with mild to moderate skin laxity who want a natural lift without surgery. At your consultation we&rsquo;ll assess your skin and tell you honestly whether it&rsquo;s right for you; more advanced laxity may need more than one session or a different approach."),
   ("Does it hurt?","You may feel brief warmth or tingling as the energy is delivered &mdash; a sign that collagen-building has begun. Comfort is improved on the Ultherapy PRIME platform, and we take steps to keep you comfortable throughout."),
   ("When will I see results?","Some lifting can appear early, but the full effect develops gradually over two to three months as your body builds new collagen. Results can last a year or more."),
   ("How many treatments will I need?","Most people achieve their result in a single session. Depending on your skin we may suggest a touch-up, and an annual maintenance treatment helps preserve your lift."),
   ("Is there any downtime?","No. Most people return to their day right away. You may have mild redness or slight swelling that settles quickly."),
 ],
 "related":["morpheus8","fillers","botox"],
 "area_kw":"non-surgical skin lifting",
 "ctah2":"Ready to lift and tighten &mdash; without surgery?",
 "ctapara":"Book an Ultherapy consultation with our Hudson physicians and see if the gold standard in non-invasive lifting is right for you.",
 "pricing_html":'''<section id="pricing" class="tint-blush">
  <div class="wrap">
    <div class="ult-cred reveal">
      <img src="/img/badges/ultherapy-prime.png" alt="Ultherapy PRIME" class="badge-wide">
      <img src="/img/badges/merz-bronze-preferred.png" alt="Merz Aesthetics Bronze Preferred Partner" class="badge-round">
      <p>Serene Med Spa is a <strong>Merz Aesthetics Bronze Preferred Partner</strong> and an authorized <strong>Ultherapy PRIME</strong> provider. Every treatment earns <a href="/xperience-rewards/">Xperience+ points</a>.</p>
    </div>
    <div class="section-head reveal"><div class="eyebrow">Investment</div><h2>Ultherapy Pricing &mdash; Hudson</h2><p>One session, priced by the area you want to lift. Financing is available, and your consultation is always complimentary.</p></div>
    <div class="grid">
      <div class="card reveal"><div class="ico">&#10022;</div><h3>Full Face + Neck</h3><p><strong>$3,500</strong><br>Our signature full lift</p></div>
      <div class="card reveal"><div class="ico">&#10022;</div><h3>Full Face</h3><p><strong>$2,600</strong></p></div>
      <div class="card reveal"><div class="ico">&#10022;</div><h3>Lower Face + Neck</h3><p><strong>$2,800</strong></p></div>
      <div class="card reveal"><div class="ico">&#10022;</div><h3>Lower Face &middot; Jowls</h3><p><strong>$1,900</strong></p></div>
      <div class="card reveal"><div class="ico">&#10022;</div><h3>Neck / Under-Chin</h3><p><strong>$1,600</strong></p></div>
      <div class="card reveal"><div class="ico">&#10022;</div><h3>Brow Lift</h3><p><strong>$950</strong></p></div>
      <div class="card reveal"><div class="ico">&#10022;</div><h3>Décolleté</h3><p><strong>$500</strong> add-on</p></div>
    </div>
    <div class="prose reveal" style="text-align:center;max-width:680px;margin:32px auto 0">
      <p>&#10024; <strong>Founding Patient offer:</strong> Full Face + Neck for <strong>$2,799</strong> for our first 20 Ultherapy patients &mdash; limited time. Use code <strong>ULTFOUNDER</strong> when you book online, or mention it at your visit. Ask about monthly financing to spread the cost.</p>
    <p style="margin-top:18px"><a class="btn" href="https://booking.mangomint.com/serenemedspa?serviceId=340" target="_blank" rel="noopener">Book Ultherapy PRIME &mdash; $250 deposit</a> <a class="btn btn-outline" href="https://booking.mangomint.com/serenemedspa?serviceId=322" target="_blank" rel="noopener">Book a Free Consultation</a></p>
    </div>
  </div>
</section>''',
},
]
