# -*- coding: utf-8 -*-
def _steps(a,b,c,d): return [("Consultation",a),("Treatment",b),("Results",c),("Maintenance",d)]

PAGES2 = [
# ---------------- LIP FILLER ----------------
{
 "slug":"lip-filler","crumb":"Lip Filler","area_kw":"lip enhancement",
 "title":"Lip Filler in Hudson, OH | Natural Lip Enhancement | Serene Med Spa",
 "desc":"Physician-injected lip filler in Hudson, Ohio at Serene Med Spa. Add subtle volume, shape, and hydration with natural-looking results. Book your consultation today.",
 "ogtitle":"Lip Filler in Hudson, OH","ogdesc":"Natural, physician-injected lip filler in Hudson, Ohio. Subtle volume and beautiful shape. Book today.",
 "proc_name":"Lip Filler","proc_alt":"Lip Augmentation with Hyaluronic Acid",
 "how":"A board-certified physician injects hyaluronic-acid filler into the lips to add subtle volume, definition, and hydration.","body":"Lips",
 "eyebrow":"Lip Filler &middot; Hudson, OH","h1":"Lip Filler in Hudson, Ohio",
 "hero":"Soft, kissable volume and beautiful shape &mdash; never overdone. Physician-injected lip filler tailored to your natural features.",
 "trust":["Physician-Injected","Natural-Looking","Subtle or Bold","Reversible"],
 "introh2":"Enhance your lips, keep them yours",
 "introlead":"Lip filler uses smooth hyaluronic-acid gels to add volume, balance, and definition to the lips &mdash; with results that can be as subtle or as noticeable as you like.",
 "intropara":"At Serene Med Spa in Hudson, your lips are treated by our board-certified physicians, who take an artful, conservative approach. We shape and hydrate rather than overfill, keeping your smile balanced and natural. Because hyaluronic-acid fillers are temporary and reversible, you stay in control of your look; results typically last several months and individual results vary.",
 "treyebrow":"What Lip Filler Can Do","treh2":"Ways We Enhance",
 "cards":[
   ("Subtle Volume","Add soft fullness for lips that look naturally plump and hydrated."),
   ("Better Definition","Refine the lip border and cupid&rsquo;s bow for a crisp, elegant shape."),
   ("Balance &amp; Symmetry","Even out lips that are naturally uneven or thinning with age."),
   ("Smooth Fine Lines","Soften the vertical lip lines that can form over time."),
   ("Hydration &amp; Sheen","Filler draws in moisture for a healthy, dewy look."),
   ("The &lsquo;Lip Flip&rsquo; Combo","Pair with a touch of Botox to gently roll the upper lip outward."),
 ],
 "steps":_steps(
   "We talk through the shape and volume you want, and design a plan that suits your face and smile.",
   "Filler is placed precisely, with numbing for comfort. Most appointments take about 30 minutes.",
   "You&rsquo;ll see results right away, with final shape settling over a week or two as any minor swelling resolves.",
   "Hyaluronic-acid lip filler typically lasts several months. We&rsquo;ll help you plan simple touch-ups."),
 "whyh2":"Why choose Serene for lip filler in Hudson",
 "whypara":"Beautiful lips are about proportion, not just volume. At Serene, your treatment is performed by board-certified physicians &mdash; Dr. Robin Arora and Dr. Shweta Arora &mdash; who prioritize natural, balanced results and your comfort, right here in Hudson.",
 "faqh2":"Lip Filler FAQ",
 "faqs":[
   ("Will my lips look overdone?","No &mdash; our physicians take a conservative approach and can start subtle. We build gradually so your results look natural and balanced."),
   ("Does lip filler hurt?","We use numbing to keep you comfortable, and most fillers contain a local anesthetic. Most patients tolerate it very well."),
   ("How long does it last?","Hyaluronic-acid lip filler typically lasts several months, then gradually fades. Maintenance touch-ups keep your look consistent."),
   ("Is it reversible?","Yes. Hyaluronic-acid fillers can be dissolved if needed, which is one reason they&rsquo;re so popular and safe."),
   ("Is there downtime?","Expect some minor swelling or bruising for a few days. Most people return to normal activities right away."),
 ],
 "related":["fillers","botox","morpheus8"],
 "ctah2":"Ready for lips you&rsquo;ll love?",
 "ctapara":"Book a lip filler consultation with our Hudson physicians and design your perfect, natural pout.",
},
# ---------------- CHEEK FILLER ----------------
{
 "slug":"cheek-filler","crumb":"Cheek Filler","area_kw":"cheek enhancement",
 "title":"Cheek Filler in Hudson, OH | Lift &amp; Contour | Serene Med Spa",
 "desc":"Physician-injected cheek filler in Hudson, Ohio at Serene Med Spa. Restore volume, lift, and definition to the mid-face for a naturally refreshed look. Book today.",
 "ogtitle":"Cheek Filler in Hudson, OH","ogdesc":"Restore cheek volume and definition with physician-injected filler in Hudson, Ohio. Book today.",
 "proc_name":"Cheek Filler","proc_alt":"Mid-Face Volumization with Dermal Filler",
 "how":"A board-certified physician injects dermal filler into the cheeks to restore lost volume, lift the mid-face, and enhance contour.","body":"Cheeks, Mid-Face",
 "eyebrow":"Cheek Filler &middot; Hudson, OH","h1":"Cheek Filler in Hudson, Ohio",
 "hero":"Restore youthful lift and definition to your mid-face &mdash; subtly and naturally &mdash; with physician-injected cheek filler.",
 "trust":["Physician-Injected","Natural Lift","Restores Volume","Tailored Contour"],
 "introh2":"Lift and refresh from the mid-face",
 "introlead":"As we age, the cheeks lose volume, which can flatten the mid-face and deepen shadows below. Cheek filler restores that lost support &mdash; subtly lifting and refreshing the whole face.",
 "intropara":"At Serene Med Spa in Hudson, our board-certified physicians place filler strategically to restore natural contour and give a gentle, non-surgical lift. The result looks like you, rested and refreshed &mdash; not overfilled. Results are immediate, build over a couple of weeks, and typically last several months to over a year depending on the product; individual results vary.",
 "treyebrow":"What Cheek Filler Can Do","treh2":"Ways We Enhance",
 "cards":[
   ("Restore Lost Volume","Replenish the fullness that naturally fades with age."),
   ("Non-Surgical Lift","Support the mid-face to gently lift and refresh your appearance."),
   ("Define Contour","Enhance and sculpt the cheekbones for a more structured look."),
   ("Soften Shadows","Reduce the hollows and shadows that can make you look tired."),
   ("Balance the Face","Bring proportion and harmony to your overall profile."),
   ("Subtle or Sculpted","From a natural refresh to more defined cheekbones &mdash; your call."),
 ],
 "steps":_steps(
   "We assess your facial structure and goals, then plan placement for a natural, balanced lift.",
   "Filler is injected with numbing for comfort. Appointments usually take about 30 minutes.",
   "You&rsquo;ll notice a refreshed contour right away, with final results settling over one to two weeks.",
   "Cheek filler often lasts several months to over a year. We&rsquo;ll plan maintenance to keep your look."),
 "whyh2":"Why choose Serene for cheek filler in Hudson",
 "whypara":"Mid-face work is where an experienced injector&rsquo;s eye truly matters. At Serene, your treatment is performed by board-certified physicians who understand facial anatomy and aesthetics, for a natural lift that flatters your features &mdash; right here in Hudson.",
 "faqh2":"Cheek Filler FAQ",
 "faqs":[
   ("Will cheek filler look natural?","Yes &mdash; our physicians place filler to restore your own natural contour. The goal is a refreshed, lifted look, never overfilled."),
   ("How long does it last?","Depending on the product, cheek filler often lasts from several months to over a year. We&rsquo;ll recommend a maintenance plan."),
   ("Does it help more than just the cheeks?","Often, yes. Restoring cheek volume can subtly lift the mid-face and soften the area beneath the eyes."),
   ("Is there downtime?","Some swelling or bruising is possible for a few days. Most people return to their routine right away."),
   ("Is it reversible?","Hyaluronic-acid cheek fillers can be dissolved if needed. We&rsquo;ll review your options at your consultation."),
 ],
 "related":["fillers","botox","morpheus8"],
 "ctah2":"Ready to lift and refresh?",
 "ctapara":"Book a cheek filler consultation with our Hudson physicians for a natural, sculpted result.",
},
# ---------------- UNDER-EYE FILLER ----------------
{
 "slug":"under-eye-filler","crumb":"Under-Eye Filler","area_kw":"under-eye rejuvenation",
 "title":"Under-Eye Filler in Hudson, OH | Tear Trough Treatment | Serene Med Spa",
 "desc":"Physician-injected under-eye (tear trough) filler in Hudson, Ohio at Serene Med Spa. Smooth hollows and soften dark circles for a refreshed, rested look. Book today.",
 "ogtitle":"Under-Eye Filler in Hudson, OH","ogdesc":"Smooth under-eye hollows and shadows with physician-injected tear trough filler in Hudson, Ohio.",
 "proc_name":"Under-Eye Filler","proc_alt":"Tear Trough Filler",
 "how":"A board-certified physician carefully injects hyaluronic-acid filler into the tear trough to smooth hollows and reduce the look of dark shadows.","body":"Under-Eye, Tear Trough",
 "eyebrow":"Under-Eye &amp; Tear Trough &middot; Hudson, OH","h1":"Under-Eye Filler in Hudson, Ohio",
 "hero":"Smooth tired-looking hollows and soften shadows for a brighter, well-rested appearance &mdash; delicately, by physicians.",
 "trust":["Physician-Injected","Delicate &amp; Precise","Brighter &amp; Rested","Natural Results"],
 "introh2":"Look rested, even when you&rsquo;re not",
 "introlead":"Hollows and shadows under the eyes can make you look tired no matter how much sleep you get. Under-eye (tear trough) filler gently restores volume in this delicate area for a smoother, brighter look.",
 "intropara":"The under-eye is one of the most delicate areas to treat, which is exactly why it belongs in experienced physician hands. At Serene Med Spa in Hudson, our board-certified physicians assess whether you&rsquo;re a good candidate and treat conservatively for natural, refreshed results. Results are visible quickly and typically last several months to a year; individual results vary.",
 "treyebrow":"What It Addresses","treh2":"Concerns We Treat",
 "cards":[
   ("Under-Eye Hollows","Restore volume in the tear trough to smooth the transition to the cheek."),
   ("Shadowing &amp; Dark Circles","Soften the shadows that hollows can cast for a brighter look."),
   ("A Tired Appearance","Refresh the eye area so you look more rested and awake."),
   ("Sunken Contour","Gently fill a sunken under-eye for a smoother surface."),
   ("Makeup That Creases","Help concealer sit more smoothly over a fuller under-eye."),
   ("Balanced Refresh","Often paired with cheek support for the most natural outcome."),
 ],
 "steps":_steps(
   "We evaluate your under-eye anatomy and confirm you&rsquo;re a good candidate, then plan a delicate, conservative treatment.",
   "Filler is placed precisely with numbing for comfort. The appointment is quick and gentle.",
   "You&rsquo;ll look brighter soon after, with results refining over one to two weeks.",
   "Under-eye filler typically lasts several months to a year. We&rsquo;ll plan gentle maintenance as needed."),
 "whyh2":"Why choose Serene for under-eye filler in Hudson",
 "whypara":"The tear trough is an advanced, delicate treatment &mdash; results (and safety) depend heavily on the injector&rsquo;s skill. At Serene, this area is treated only by our board-certified physicians, for careful, natural-looking results right here in Hudson.",
 "faqh2":"Under-Eye Filler FAQ",
 "faqs":[
   ("Am I a candidate for under-eye filler?","Not everyone is &mdash; the under-eye is delicate and results depend on your anatomy. Our physicians will assess this carefully at your consultation."),
   ("Will it get rid of dark circles?","It can soften shadows caused by hollows. Pigment-based dark circles may need a different approach, which we&rsquo;ll discuss."),
   ("How long does it last?","Under-eye filler often lasts several months to a year. Because the area is delicate, we treat conservatively and touch up as needed."),
   ("Is there downtime?","Bruising or mild swelling is possible for a few days in this delicate area. We&rsquo;ll share aftercare tips."),
   ("Is it reversible?","Yes &mdash; hyaluronic-acid filler can be dissolved if needed, which adds an extra layer of safety."),
 ],
 "related":["fillers","botox","morpheus8"],
 "ctah2":"Ready to brighten your eyes?",
 "ctapara":"Book an under-eye filler consultation with our Hudson physicians for a rested, refreshed look.",
},
# ---------------- JAWLINE FILLER ----------------
{
 "slug":"jawline-filler","crumb":"Jawline Filler","area_kw":"jawline contouring",
 "title":"Jawline Filler in Hudson, OH | Define &amp; Sculpt | Serene Med Spa",
 "desc":"Physician-injected jawline filler in Hudson, Ohio at Serene Med Spa. Sculpt a defined, contoured jawline and refresh your profile. Book your consultation today.",
 "ogtitle":"Jawline Filler in Hudson, OH","ogdesc":"Define and sculpt your jawline with physician-injected filler in Hudson, Ohio. Book today.",
 "proc_name":"Jawline Filler","proc_alt":"Jawline Contouring with Dermal Filler",
 "how":"A board-certified physician injects dermal filler along the jawline to add definition, sharpen the contour, and enhance the profile.","body":"Jawline, Chin",
 "eyebrow":"Jawline Filler &middot; Hudson, OH","h1":"Jawline Filler in Hudson, Ohio",
 "hero":"A sharper, more defined jawline &mdash; sculpted and contoured without surgery, by our board-certified physicians.",
 "trust":["Physician-Injected","Defined Contour","Non-Surgical","Natural Balance"],
 "introh2":"Definition and structure, no surgery",
 "introlead":"A defined jawline frames the face and conveys balance and structure. Jawline filler enhances and sculpts the contour, sharpening the profile for both women and men.",
 "intropara":"At Serene Med Spa in Hudson, our board-certified physicians use filler to define the jawline, strengthen a soft or receding chin, and smooth the transition into the neck &mdash; all while keeping your look natural. Results are visible immediately and typically last from several months to over a year; individual results vary.",
 "treyebrow":"What Jawline Filler Can Do","treh2":"Ways We Sculpt",
 "cards":[
   ("Sharper Definition","Enhance the jawline for a crisper, more sculpted contour."),
   ("Strengthen the Chin","Add projection and balance to a soft or receding chin."),
   ("Refine the Profile","Improve the side profile and jaw-to-neck transition."),
   ("Frame the Face","A defined jaw brings structure and balance to your features."),
   ("Soften Jowling","Support the lower face to soften early jowl formation."),
   ("For Women &amp; Men","Tailored to create either an elegant or a strong, masculine line."),
 ],
 "steps":_steps(
   "We study your profile and goals, then plan filler placement for a balanced, natural contour.",
   "Filler is injected along the jaw with numbing for comfort. Appointments take about 30&ndash;45 minutes.",
   "You&rsquo;ll see a more defined jawline right away, with final results settling over one to two weeks.",
   "Jawline filler often lasts several months to over a year. We&rsquo;ll plan simple maintenance."),
 "whyh2":"Why choose Serene for jawline filler in Hudson",
 "whypara":"Contouring the jaw takes an understanding of proportion and profile. At Serene, your treatment is performed by board-certified physicians who sculpt with balance in mind, for a defined, natural-looking result right here in Hudson.",
 "faqh2":"Jawline Filler FAQ",
 "faqs":[
   ("What does jawline filler do?","It adds definition and structure to the jawline and chin, sharpening the contour and improving the profile without surgery."),
   ("How much filler will I need?","The jawline is a larger area, so it can take more filler than the lips. We&rsquo;ll estimate this at your consultation based on your goals."),
   ("How long does it last?","Jawline filler often lasts from several months to over a year, depending on the product. Maintenance keeps your contour consistent."),
   ("Is it good for men?","Absolutely &mdash; a defined jawline is one of the most requested treatments for men. We tailor the look accordingly."),
   ("Is there downtime?","Mild swelling or bruising is possible for a few days. Most people return to their routine right away."),
 ],
 "related":["fillers","botox","morpheus8"],
 "ctah2":"Ready to sculpt your profile?",
 "ctapara":"Book a jawline filler consultation with our Hudson physicians for a defined, balanced contour.",
},
# ---------------- SCULPTRA ----------------
{
 "slug":"sculptra","crumb":"Sculptra","area_kw":"collagen-stimulating treatment",
 "title":"Sculptra in Hudson, OH | Collagen-Stimulating Filler | Serene Med Spa",
 "desc":"Sculptra collagen-stimulating treatment in Hudson, Ohio at Serene Med Spa. Gradual, natural volume and firmer-looking skin over time. Physician-led. Book today.",
 "ogtitle":"Sculptra in Hudson, OH","ogdesc":"Gradual, natural collagen-stimulating volume with Sculptra in Hudson, Ohio. Physician-led. Book today.",
 "proc_name":"Sculptra","proc_alt":"Poly-L-Lactic Acid Collagen Stimulator",
 "how":"A board-certified physician injects poly-L-lactic acid, which works with your body to gradually stimulate its own collagen for natural volume and firmer-looking skin.","body":"Face, Cheeks, Temples",
 "eyebrow":"Sculptra &middot; Hudson, OH","h1":"Sculptra in Hudson, Ohio",
 "hero":"A different kind of filler &mdash; Sculptra stimulates your own collagen for gradual, natural volume that builds over time.",
 "trust":["Physician-Led","Stimulates Collagen","Gradual &amp; Natural","Long-Lasting"],
 "introh2":"Rebuild volume, naturally, over time",
 "introlead":"Sculptra isn&rsquo;t a traditional filler &mdash; instead of simply adding volume, it uses poly-L-lactic acid to prompt your skin to produce its own collagen, restoring fullness gradually and subtly.",
 "intropara":"At Serene Med Spa in Hudson, Sculptra is a favorite for patients who want a natural refresh that doesn&rsquo;t look &lsquo;done.&rsquo; Because results build over a series of sessions as new collagen forms, the change is beautifully gradual &mdash; and it can last up to a couple of years. Treatment is always physician-led, and individual results vary.",
 "treyebrow":"What Sculptra Can Do","treh2":"Where It Helps",
 "cards":[
   ("Restore Facial Volume","Gradually replenish fullness lost to aging in the cheeks and face."),
   ("Firmer-Looking Skin","Stimulated collagen supports smoother, firmer-looking skin."),
   ("Soften Deep Folds","Improve the look of deeper facial lines and hollows over time."),
   ("Temple Hollowing","Restore volume to the temples for a smoother upper face."),
   ("A Natural, Gradual Look","Changes appear subtly, so friends notice you &mdash; not the treatment."),
   ("Long-Lasting Results","Results can last up to a couple of years with a full series."),
 ],
 "steps":_steps(
   "We assess your goals and areas of volume loss, then plan a personalized series of Sculptra sessions.",
   "Sculptra is injected with numbing for comfort. Each session typically takes about 30&ndash;45 minutes.",
   "Results build gradually over weeks and months as your body produces new collagen &mdash; natural and subtle.",
   "A full series is usually spaced over a few months, with results that can last up to a couple of years."),
 "whyh2":"Why choose Serene for Sculptra in Hudson",
 "whypara":"Sculptra rewards planning and an artful eye, because results develop over time. At Serene, your treatment is guided by board-certified physicians who map out your series thoughtfully for a natural, gradual refresh &mdash; right here in Hudson.",
 "faqh2":"Sculptra FAQ",
 "faqs":[
   ("How is Sculptra different from regular filler?","Traditional fillers add volume instantly. Sculptra works gradually by stimulating your own collagen, for a subtle, natural change over time."),
   ("How many sessions will I need?","Most people need a series of sessions spaced over a few months. We&rsquo;ll design a plan based on your goals."),
   ("How long does it last?","Because it builds your own collagen, Sculptra results can last up to a couple of years &mdash; longer than many traditional fillers."),
   ("When will I see results?","Results appear gradually over weeks to months, so the change looks natural rather than sudden."),
   ("Is there downtime?","Mild swelling or bruising is possible. We&rsquo;ll also show you a simple massage technique to do at home after treatment."),
 ],
 "related":["fillers","morpheus8","botox"],
 "ctah2":"Ready for a natural, gradual refresh?",
 "ctapara":"Book a Sculptra consultation with our Hudson physicians and rebuild volume the natural way.",
},
# ---------------- CHEMICAL PEELS ----------------
{
 "slug":"chemical-peels","crumb":"Chemical Peels","area_kw":"skin resurfacing peels",
 "title":"Chemical Peels in Hudson, OH | VI Peel &amp; Perfect Derma | Serene Med Spa",
 "desc":"Medical-grade chemical peels in Hudson, Ohio at Serene Med Spa — VI Peel and The Perfect Derma Peel for brighter, clearer, smoother skin. Book your consultation.",
 "ogtitle":"Chemical Peels in Hudson, OH","ogdesc":"Medical-grade VI Peel & Perfect Derma Peel in Hudson, Ohio for brighter, clearer skin. Book today.",
 "proc_name":"Chemical Peel","proc_alt":"Medical-Grade Skin Resurfacing Peel",
 "how":"A medical-grade solution is applied to the skin to exfoliate damaged surface layers and reveal brighter, smoother, more even-toned skin as it renews.","body":"Face, Neck, Chest",
 "eyebrow":"Chemical Peels &middot; Hudson, OH","h1":"Chemical Peels in Hudson, Ohio",
 "hero":"Reveal brighter, clearer, smoother skin with medical-grade peels &mdash; including the VI Peel and The Perfect Derma Peel.",
 "trust":["Medical-Grade","Brighter &amp; Clearer","For Tone &amp; Texture","Physician-Led"],
 "introh2":"Resurface, brighten, renew",
 "introlead":"A chemical peel gently exfoliates the damaged surface layers of the skin, prompting fresh, healthy skin to take their place &mdash; for a brighter, smoother, more even complexion.",
 "intropara":"At Serene Med Spa in Hudson, we offer medical-grade peels including the VI Peel and The Perfect Derma Peel, chosen and customized to your skin and goals. Peels can target dullness, uneven tone, sun damage, fine lines, and breakouts. Your treatment is physician-supervised, and we&rsquo;ll guide you on what to expect; individual results vary.",
 "treyebrow":"What Peels Address","treh2":"Concerns We Treat",
 "cards":[
   ("Dullness","Slough away tired surface skin to reveal a fresh, radiant glow."),
   ("Uneven Tone","Improve the look of sun spots, discoloration, and blotchiness."),
   ("Texture &amp; Roughness","Smooth rough, uneven skin for a softer surface."),
   ("Fine Lines","Soften the look of early fine lines and surface aging."),
   ("Breakouts &amp; Congestion","Help clear and refine acne-prone or congested skin."),
   ("Overall Radiance","Restore a healthy, luminous, refreshed complexion."),
 ],
 "steps":_steps(
   "We assess your skin and choose the right peel and strength for your concerns and skin type.",
   "The peel solution is applied in the office in a quick, comfortable visit.",
   "In the days after, skin may lightly flake or peel as it renews &mdash; then reveals a brighter, smoother surface.",
   "A series of peels, spaced a few weeks apart, delivers the best cumulative results. We&rsquo;ll plan a schedule."),
 "whyh2":"Why choose Serene for chemical peels in Hudson",
 "whypara":"The right peel, at the right strength, for your skin makes all the difference. At Serene, peels are physician-supervised and customized &mdash; so you get real results safely, with clear guidance on aftercare &mdash; right here in Hudson.",
 "faqh2":"Chemical Peel FAQ",
 "faqs":[
   ("Which peel is right for me?","It depends on your skin and goals. We offer options like the VI Peel and The Perfect Derma Peel, and will recommend the best fit at your consultation."),
   ("Will I actually peel?","Light flaking or peeling over a few days is common with medical-grade peels as the skin renews. We&rsquo;ll tell you exactly what to expect."),
   ("How many treatments will I need?","Many people do a series spaced a few weeks apart for cumulative results, then maintain periodically."),
   ("Is there downtime?","Most peels involve a few days of flaking and sensitivity. Sun protection afterward is essential, and we&rsquo;ll guide your aftercare."),
   ("Is it safe for my skin?","We select and customize peels for your skin type. A consultation ensures the treatment is appropriate and safe for you."),
 ],
 "related":["morpheus8","fillers","botox"],
 "ctah2":"Ready to reveal brighter skin?",
 "ctapara":"Book a chemical peel consultation with our Hudson team and refresh your complexion.",
},
# ---------------- LASER FACIAL ----------------
{
 "slug":"laser-facial","crumb":"Laser Facial","area_kw":"laser skin rejuvenation",
 "title":"Laser Facial in Hudson, OH | Glow &amp; Rejuvenation | Serene Med Spa",
 "desc":"Laser facial skin rejuvenation in Hudson, Ohio at Serene Med Spa — brighten tone, refine texture, and restore a healthy glow with little downtime. Book today.",
 "ogtitle":"Laser Facial in Hudson, OH","ogdesc":"Brighten tone and restore a healthy glow with a laser facial in Hudson, Ohio. Little downtime. Book today.",
 "proc_name":"Laser Facial","proc_alt":"Laser Skin Rejuvenation Facial",
 "how":"Gentle laser energy is passed over the skin to target dullness, redness, and uneven tone while stimulating renewal for a brighter, refreshed complexion.","body":"Face, Neck, Chest",
 "eyebrow":"Laser Facial &middot; Hudson, OH","h1":"Laser Facial in Hudson, Ohio",
 "hero":"A luminous, refreshed glow with little to no downtime &mdash; a laser facial that brightens tone and refines the skin&rsquo;s surface.",
 "trust":["Little Downtime","Brighter Tone","Refined Texture","Physician-Led"],
 "introh2":"Glow, refreshed and radiant",
 "introlead":"A laser facial uses gentle laser energy to brighten tone, refine texture, and stimulate your skin&rsquo;s natural renewal &mdash; delivering a healthy, radiant glow with minimal downtime.",
 "intropara":"At Serene Med Spa in Hudson, a laser facial is a wonderful way to refresh dull, uneven skin and keep your complexion looking its best. It suits a range of concerns, from redness and blotchiness to overall radiance, and pairs beautifully with the rest of your skincare plan. Treatment is physician-supervised, and individual results vary.",
 "treyebrow":"What It Improves","treh2":"Concerns We Target",
 "cards":[
   ("Dullness","Awaken tired skin for a fresh, lit-from-within radiance."),
   ("Uneven Tone","Improve the look of redness, blotchiness, and discoloration."),
   ("Texture","Refine and smooth the skin&rsquo;s surface for a softer feel."),
   ("Enlarged Pores","Help refine the appearance of pores as part of a plan."),
   ("Early Aging","Support renewal to keep skin looking healthy and fresh."),
   ("Event-Ready Glow","A radiant refresh with little to no downtime."),
 ],
 "steps":_steps(
   "We evaluate your skin and goals and tailor the laser facial to your complexion.",
   "The treatment is passed gently over the skin in a comfortable, in-office visit.",
   "You may have mild, short-lived warmth or redness, then enjoy a brighter, refreshed glow.",
   "A series of treatments builds the best results. We&rsquo;ll recommend a schedule and simple sun protection."),
 "whyh2":"Why choose Serene for a laser facial in Hudson",
 "whypara":"Laser settings should match your skin, not a one-size-fits-all package. At Serene, laser treatments are physician-supervised and tailored to your complexion for safe, effective results &mdash; right here in Hudson.",
 "faqh2":"Laser Facial FAQ",
 "faqs":[
   ("What is a laser facial?","It&rsquo;s a gentle laser treatment that brightens tone, refines texture, and stimulates renewal for a healthy, radiant glow &mdash; with little downtime."),
   ("Is there downtime?","Most people have only mild, short-lived redness or warmth. We&rsquo;ll give you aftercare and sun-protection guidance."),
   ("How many treatments will I need?","A series usually delivers the best results, then periodic maintenance keeps your glow. We&rsquo;ll tailor a plan."),
   ("Does it hurt?","Most people find it very tolerable and describe a mild warmth. We keep you comfortable throughout."),
   ("Is it right for my skin?","We tailor laser treatments to your skin type and concerns. A consultation ensures it&rsquo;s a good, safe fit for you."),
 ],
 "related":["opus-plasma","harmony-bio-boost","morpheus8"],
 "ctah2":"Ready to glow?",
 "ctapara":"Book a laser facial with our Hudson team and refresh your complexion with radiant results.",
},
# ---------------- MICRONEEDLING & PRP ----------------
{
 "slug":"microneedling","crumb":"Microneedling &amp; PRP","area_kw":"microneedling and PRP",
 "title":"Microneedling &amp; PRP in Hudson, OH | Collagen Renewal | Serene Med Spa",
 "desc":"Microneedling and microneedling with PRP (‘vampire facial’) in Hudson, Ohio at Serene Med Spa. Smooth texture, scars, and fine lines with collagen renewal. Book today.",
 "ogtitle":"Microneedling & PRP in Hudson, OH","ogdesc":"Microneedling & microneedling with PRP in Hudson, Ohio for smoother, renewed skin. Book today.",
 "proc_name":"Microneedling with PRP","proc_alt":"Collagen Induction Therapy &amp; Vampire Facial",
 "how":"Fine needles create controlled micro-channels that trigger the skin&rsquo;s natural repair and collagen production; platelet-rich plasma (PRP) from your own blood can be added to enhance renewal.","body":"Face, Neck, Body",
 "eyebrow":"Microneedling &amp; PRP &middot; Hudson, OH","h1":"Microneedling &amp; PRP in Hudson, Ohio",
 "hero":"Smoother texture, softer scars, and a fresh glow &mdash; microneedling that renews your skin, with the option to boost results using your own PRP.",
 "trust":["Collagen Renewal","Optional PRP Boost","Softens Scars","Physician-Led"],
 "introh2":"Renew your skin from within",
 "introlead":"Microneedling creates tiny, controlled micro-channels that switch on your skin&rsquo;s natural repair process &mdash; boosting collagen to smooth texture, soften scars, and refresh tone. Adding PRP from your own blood can take renewal even further.",
 "intropara":"At Serene Med Spa in Hudson, we offer both microneedling and microneedling with PRP (often called a &lsquo;vampire facial&rsquo;), where we apply platelet-rich plasma drawn from your own blood to amplify healing and glow. Treatment is physician-led, comfortable, and has minimal downtime. A series delivers the best results, and individual results vary.",
 "treyebrow":"What It Improves","treh2":"Concerns We Target",
 "cards":[
   ("Acne Scars","Soften the look of pitted and textured acne scarring over a series."),
   ("Fine Lines","Smooth early fine lines by boosting collagen and elasticity."),
   ("Texture &amp; Pores","Refine rough texture and the appearance of enlarged pores."),
   ("Dullness","Reveal a fresh, healthy glow as the skin renews."),
   ("Uneven Tone","Improve overall tone and clarity with regular treatments."),
   ("PRP Boost","Add your own platelet-rich plasma to enhance healing and results."),
 ],
 "steps":_steps(
   "We assess your skin and goals and decide whether microneedling alone or with PRP is right for you.",
   "After numbing, the microneedling device is passed over the skin; if adding PRP, we draw a small sample and apply it.",
   "Expect mild redness for a day or two, like a light sunburn, then a smoother, fresher look as skin renews.",
   "A series spaced a few weeks apart gives the best results. We&rsquo;ll plan a schedule and aftercare."),
 "whyh2":"Why choose Serene for microneedling in Hudson",
 "whypara":"Microneedling &mdash; especially with PRP &mdash; should be done in a clean, physician-led setting for safety and results. At Serene, your treatment is overseen by board-certified physicians, right here in Hudson.",
 "faqh2":"Microneedling &amp; PRP FAQ",
 "faqs":[
   ("What is microneedling with PRP?","It combines microneedling with platelet-rich plasma drawn from your own blood, applied to the skin to enhance healing, collagen, and glow."),
   ("Does it hurt?","We numb the skin first, so most people are comfortable. You may feel light pressure or vibration during treatment."),
   ("How many sessions will I need?","A series spaced a few weeks apart usually gives the best results, especially for scarring and texture. We&rsquo;ll tailor a plan."),
   ("Is there downtime?","Expect mild redness for a day or two, similar to a light sunburn. Most people return to normal activities quickly."),
   ("What is a &lsquo;vampire facial&rsquo;?","It&rsquo;s a nickname for microneedling with PRP, because it uses components from your own blood to boost your skin&rsquo;s renewal."),
 ],
 "related":["morpheus8","fillers","botox"],
 "ctah2":"Ready to renew your skin?",
 "ctapara":"Book a microneedling consultation with our Hudson team, with or without a PRP boost.",
},
# ---------------- PDO THREAD LIFT ----------------
{
 "slug":"thread-lift","crumb":"PDO Thread Lift","area_kw":"non-surgical lifting",
 "title":"PDO Thread Lift in Hudson, OH | Non-Surgical Lift | Serene Med Spa",
 "desc":"PDO thread lift in Hudson, Ohio at Serene Med Spa — a non-surgical way to lift and firm sagging skin with little downtime. Physician-performed. Book today.",
 "ogtitle":"PDO Thread Lift in Hudson, OH","ogdesc":"Non-surgical PDO thread lift in Hudson, Ohio to lift and firm skin. Physician-performed. Book today.",
 "proc_name":"PDO Thread Lift","proc_alt":"Non-Surgical Thread Lift",
 "how":"A physician places dissolvable PDO threads under the skin to gently lift and reposition sagging tissue while stimulating collagen along the thread.","body":"Face, Neck, Jawline, Brow",
 "eyebrow":"PDO Thread Lift &middot; Hudson, OH","h1":"PDO Thread Lift in Hudson, Ohio",
 "hero":"Lift and firm sagging skin without surgery &mdash; dissolvable PDO threads that reposition tissue and stimulate collagen, with little downtime.",
 "trust":["Non-Surgical","Immediate Lift","Stimulates Collagen","Physician-Performed"],
 "introh2":"A lift &mdash; without the surgery",
 "introlead":"A PDO thread lift uses fine, dissolvable threads placed under the skin to gently lift and support sagging areas, while also stimulating your own collagen along the way &mdash; for a firmer, refreshed look without surgery.",
 "intropara":"At Serene Med Spa in Hudson, PDO thread lifts are performed by our board-certified physicians for patients who want more lift than injectables provide, but aren&rsquo;t ready for surgery. The threads dissolve over time, leaving behind new collagen support. There&rsquo;s an immediate lift plus gradual improvement, with little downtime; individual results vary.",
 "treyebrow":"What It Lifts","treh2":"Areas We Treat",
 "cards":[
   ("Jawline &amp; Jowls","Lift and define a softening jawline and early jowls."),
   ("Mid-Face &amp; Cheeks","Reposition sagging cheek tissue for a subtle lift."),
   ("Brow &amp; Eyes","Gently lift the brow to open up and refresh the eyes."),
   ("Neck","Firm and smooth mild laxity along the neck."),
   ("Collagen Support","Threads stimulate new collagen for lasting firmness."),
   ("Natural, Subtle Lift","A refreshed look that&rsquo;s noticeable but never obvious."),
 ],
 "steps":_steps(
   "We assess your skin laxity and goals and confirm a thread lift is the right option for you.",
   "After numbing, the physician places the dissolvable threads and gently lifts the tissue into position.",
   "You&rsquo;ll see an immediate lift, with results improving as collagen builds over the following weeks.",
   "Threads dissolve over months, leaving collagen support. We&rsquo;ll plan any refreshers and aftercare."),
 "whyh2":"Why choose Serene for a thread lift in Hudson",
 "whypara":"A thread lift is an advanced, in-office procedure that belongs in experienced physician hands. At Serene, thread lifts are performed by board-certified physicians for safe, natural-looking lift &mdash; right here in Hudson.",
 "faqh2":"PDO Thread Lift FAQ",
 "faqs":[
   ("Is a thread lift surgery?","No &mdash; it&rsquo;s a minimally invasive, in-office procedure using dissolvable threads. There&rsquo;s no general anesthesia and far less downtime than a surgical lift."),
   ("How long do results last?","Results often last a year or more. The threads dissolve over time, but the collagen they stimulate helps maintain support."),
   ("Is there downtime?","Expect some swelling, tightness, or bruising for several days. Most people return to normal activities fairly quickly."),
   ("Who is a good candidate?","It&rsquo;s ideal for mild to moderate sagging in people who want more than injectables but aren&rsquo;t ready for surgery. We&rsquo;ll confirm at your consultation."),
   ("Does it hurt?","We numb the area first, so most people are comfortable during the procedure. Some tightness afterward is normal."),
 ],
 "related":["morpheus8","fillers","botox"],
 "ctah2":"Ready to lift &mdash; without surgery?",
 "ctapara":"Book a PDO thread lift consultation with our Hudson physicians for a refreshed, natural lift.",
},
# ---------------- PRP HAIR RESTORATION ----------------
{
 "slug":"prp-hair-restoration","crumb":"Hair Restoration","area_kw":"hair restoration",
 "title":"Hair Restoration in Hudson, OH | PRP &amp; Alma TED | Serene Med Spa",
 "desc":"PRP hair restoration in Hudson, Ohio at Serene Med Spa — using your own platelet-rich plasma to support thicker, healthier hair. Physician-led. Book today.",
 "ogtitle":"PRP Hair Restoration in Hudson, OH","ogdesc":"Support thicker, healthier hair with PRP hair restoration in Hudson, Ohio. Physician-led. Book today.",
 "proc_name":"PRP Hair Restoration","proc_alt":"Platelet-Rich Plasma Hair Treatment",
 "how":"Platelet-rich plasma is concentrated from a small sample of your own blood and injected into the scalp to nourish follicles and support healthier hair growth.","body":"Scalp",
 "eyebrow":"Hair Restoration &middot; Hudson, OH","h1":"Hair Restoration in Hudson, Ohio",
 "hero":"Support thicker, healthier-looking hair using your body&rsquo;s own growth factors &mdash; a natural, physician-led approach to thinning hair.",
 "trust":["Uses Your Own PRP","Non-Surgical","For Men &amp; Women","Physician-Led"],
 "introh2":"Nourish your hair, naturally",
 "introlead":"PRP hair restoration uses platelet-rich plasma &mdash; concentrated from a small sample of your own blood &mdash; to deliver growth factors directly to the scalp, nourishing follicles and supporting healthier, fuller-looking hair.",
 "intropara":"At Serene Med Spa in Hudson, PRP is a popular, non-surgical option for men and women experiencing early thinning. Because it uses your own blood components, it&rsquo;s a natural approach with minimal downtime. We also offer Alma TED &mdash; a comfortable, needle-free acoustic treatment &mdash; and microneedling with PRP for the scalp, so we can tailor the right approach for you. Results build over a series of sessions and with maintenance; treatments work best on active follicles, and individual results vary.",
 "treyebrow":"Who It Helps","treh2":"Good Candidates",
 "cards":[
   ("Early Thinning","Best for early to moderate thinning where follicles are still active."),
   ("Widening Part","Support fuller-looking hair along a widening part."),
   ("Receding Hairline","Nourish follicles along a receding or thinning hairline."),
   ("Men &amp; Women","An option for pattern thinning in both men and women."),
   ("Natural Approach","Uses only components from your own blood &mdash; no medication."),
   ("Combine &amp; Maintain","Pairs with other hair-health strategies for the best outcome."),
 ],
 "steps":_steps(
   "We review your hair-loss history and goals and confirm whether PRP is likely to help you.",
   "We draw a small blood sample, concentrate the PRP, and inject it into the scalp after numbing for comfort.",
   "Results build gradually over a series of sessions as follicles are nourished; consistency matters most.",
   "An initial series is followed by periodic maintenance sessions to support ongoing results."),
 "whyh2":"Why choose Serene for PRP hair restoration in Hudson",
 "whypara":"PRP works best with a proper protocol and realistic expectations. At Serene, treatment is physician-led, with an honest assessment of whether PRP is likely to help you &mdash; right here in Hudson.",
 "faqh2":"PRP Hair Restoration FAQ",
 "faqs":[
   ("How does PRP help hair?","PRP concentrates growth factors from your own blood and delivers them to the scalp, nourishing active follicles to support healthier, fuller-looking hair."),
   ("How many sessions will I need?","Most people start with a series of sessions spaced a few weeks apart, then maintain periodically. We&rsquo;ll tailor a plan."),
   ("Does it work for everyone?","PRP works best on follicles that are still active, so it&rsquo;s most effective for early to moderate thinning. We&rsquo;ll give you an honest assessment."),
   ("Is there downtime?","Very little. Your scalp may be tender for a short time after treatment, and most people return to their day right away."),
   ("Is it safe?","Because PRP uses components from your own blood, it&rsquo;s a natural approach. Treatment is physician-led for safety and comfort."),
 ],
 "related":["alma-ted","morpheus8","weight-loss"],
 "ctah2":"Ready to support healthier hair?",
 "ctapara":"Book a PRP hair restoration consultation with our Hudson team for an honest, physician-led plan.",
},
# ---------------- BODY CONTOURING (EVOLVE) ----------------
{
 "slug":"body-contouring","crumb":"Body Contouring","area_kw":"body contouring and skin tightening",
 "title":"Body Contouring in Hudson, OH | Skin Tightening &amp; Toning | Serene Med Spa",
 "desc":"Non-invasive body contouring and skin tightening in Hudson, Ohio at Serene Med Spa — tone, firm, and refine with no surgery and no downtime. Book today.",
 "ogtitle":"Body Contouring in Hudson, OH","ogdesc":"Non-invasive body contouring & skin tightening in Hudson, Ohio. No surgery, no downtime. Book today.",
 "proc_name":"Body Contouring","proc_alt":"Non-Invasive Skin Tightening &amp; Body Toning",
 "how":"Radiofrequency and other non-invasive energy-based technologies are used to tighten skin, tone muscle, and refine the appearance of targeted areas without surgery.","body":"Abdomen, Thighs, Arms, Buttocks",
 "eyebrow":"Body Contouring &amp; Skin Tightening &middot; Hudson, OH","h1":"Body Contouring in Hudson, Ohio",
 "hero":"Tone, firm, and refine your figure without surgery or downtime &mdash; non-invasive body contouring and skin-tightening treatments, physician-led.",
 "trust":["Non-Invasive","No Downtime","Tighten &amp; Tone","Physician-Led"],
 "introh2":"Refine your figure, no surgery required",
 "introlead":"Our non-invasive body-contouring treatments use energy-based technology to tighten loose skin, tone the underlying area, and refine stubborn spots &mdash; comfortably, without surgery or downtime.",
 "intropara":"At Serene Med Spa in Hudson, we offer a range of body treatments to firm and smooth areas like the abdomen, arms, thighs, and buttocks. Because they&rsquo;re non-invasive, most people relax during treatment and return to their day right away. These treatments complement a healthy lifestyle and pair well with EMSCULPT NEO; results build over a series and individual results vary.",
 "treyebrow":"Where It Helps","treh2":"Areas We Treat",
 "cards":[
   ("Abdomen","Tighten and smooth loose skin and refine the midsection."),
   ("Arms","Firm the upper arms for a more toned appearance."),
   ("Thighs","Smooth and tighten the inner and outer thighs."),
   ("Buttocks","Firm and refine for a smoother, lifted look."),
   ("Skin Laxity","Improve mild skin laxity after weight changes or over time."),
   ("Overall Toning","Refine and firm as part of a healthy-lifestyle plan."),
 ],
 "steps":_steps(
   "We review your goals and target areas and design a body-contouring plan suited to you.",
   "You relax while the device treats the area &mdash; most sessions are comfortable, with a warming sensation.",
   "Results build gradually over the weeks following your sessions as skin firms and tones; results vary.",
   "A series delivers the best results, followed by periodic maintenance to keep your figure refined."),
 "whyh2":"Why choose Serene for body contouring in Hudson",
 "whypara":"Body treatments work best as part of a thoughtful, realistic plan &mdash; not a quick fix. At Serene, your treatments are physician-led and tailored to your goals, with honest guidance on what to expect &mdash; right here in Hudson.",
 "faqh2":"Body Contouring FAQ",
 "faqs":[
   ("Is body contouring a weight-loss treatment?","No. It refines, tones, and tightens targeted areas and complements a healthy lifestyle &mdash; it&rsquo;s not a substitute for weight loss."),
   ("Is there downtime?","Our non-invasive treatments typically have no downtime, so most people return to their normal day right away."),
   ("How many sessions will I need?","A series usually delivers the best results. We&rsquo;ll recommend a plan for your goals and target areas."),
   ("How is this different from EMSCULPT NEO?","EMSCULPT NEO focuses on building muscle and reducing fat, while these treatments emphasize skin tightening and toning. They pair well together."),
   ("When will I see results?","Results build gradually over the weeks after treatment as the skin firms and tones. Individual results vary."),
 ],
 "related":["weight-loss","morpheus8","fillers"],
 "ctah2":"Ready to tighten and tone?",
 "ctapara":"Book a body-contouring consultation with our Hudson team and build a plan around your goals.",
},
# ---------------- IV THERAPY ----------------
{
 "slug":"iv-therapy","crumb":"IV Therapy","area_kw":"IV therapy and hydration",
 "title":"IV Therapy in Hudson, OH | Hydration &amp; Wellness Drips | Serene Med Spa",
 "desc":"IV nutrient therapy and hydration drips in Hudson, Ohio at Serene Med Spa. Replenish, recover, and feel your best with physician-supervised IV wellness. Book today.",
 "ogtitle":"IV Therapy in Hudson, OH","ogdesc":"Hydration and wellness IV drips in Hudson, Ohio. Physician-supervised. Feel your best. Book today.",
 "proc_name":"IV Nutrient Therapy","proc_alt":"IV Hydration &amp; Vitamin Drip",
 "how":"A customized blend of fluids, vitamins, and nutrients is delivered directly into the bloodstream via IV for efficient hydration and replenishment.","body":"Systemic (IV)",
 "eyebrow":"IV Therapy &amp; Hydration &middot; Hudson, OH","h1":"IV Therapy in Hudson, Ohio",
 "hero":"Replenish, rehydrate, and feel your best &mdash; customized IV nutrient drips delivered in a calm, physician-supervised setting.",
 "trust":["Physician-Supervised","Customized Blends","Fast Hydration","Relaxing Setting"],
 "introh2":"Hydration and nutrients, delivered directly",
 "introlead":"IV therapy delivers fluids, vitamins, and nutrients straight into your bloodstream, so your body can use them efficiently &mdash; a popular way to rehydrate, recover, and support overall wellness.",
 "intropara":"At Serene Med Spa in Hudson, our &lsquo;Serene IV Bar&rsquo; offers customized drips to support hydration, recovery, and everyday wellness. You relax in a comfortable setting while a physician-supervised team takes care of you. IV therapy supports general wellness and hydration; it is not a treatment for medical conditions, and we&rsquo;ll help you choose a blend that fits your goals.",
 "treyebrow":"Popular Goals","treh2":"Ways People Use IV Therapy",
 "cards":[
   ("Hydration","Rehydrate quickly and efficiently after travel, heat, or a busy week."),
   ("Recovery","Support recovery and help you bounce back and feel refreshed."),
   ("Energy &amp; Wellness","Replenish key vitamins and nutrients to support everyday vitality."),
   ("Immune Support","Popular blends to support your wellness during busy seasons."),
   ("Beauty &amp; Glow","Nutrient blends chosen to support healthy skin, hair, and nails."),
   ("Custom Blends","We tailor your drip to your goals and how you want to feel."),
 ],
 "steps":_steps(
   "We talk through how you&rsquo;re feeling and your goals, and select or customize the right IV blend for you.",
   "You relax in a comfortable chair while our team places the IV and your drip is delivered, usually in under an hour.",
   "Many people feel refreshed and rehydrated soon after. We&rsquo;ll suggest how often to come based on your goals.",
   "IV therapy can be a one-time boost or part of a regular wellness routine &mdash; whatever suits you."),
 "whyh2":"Why choose Serene for IV therapy in Hudson",
 "whypara":"IV therapy should be delivered in a clean, professional, physician-supervised setting. At Serene, our team takes care of you in a calm, welcoming space, with blends chosen to fit your wellness goals &mdash; right here in Hudson.",
 "faqh2":"IV Therapy FAQ",
 "faqs":[
   ("What is IV therapy?","It delivers fluids, vitamins, and nutrients directly into your bloodstream via IV, for efficient hydration and replenishment to support general wellness."),
   ("How long does a drip take?","Most IV drips take around 30&ndash;60 minutes. You&rsquo;ll relax comfortably while ours team takes care of you."),
   ("How often should I get IV therapy?","That depends on your goals &mdash; some people come for a one-time boost, others make it part of a regular routine. We&rsquo;ll advise you."),
   ("Is it safe?","IV therapy at Serene is physician-supervised. We&rsquo;ll review your health and goals to choose an appropriate blend for you."),
   ("Can IV therapy treat medical conditions?","No &mdash; IV therapy supports general wellness and hydration and is not a treatment for medical conditions. We&rsquo;ll always be clear about what it can and can&rsquo;t do."),
 ],
 "related":["weight-loss","morpheus8","botox"],
 "ctah2":"Ready to replenish and refresh?",
 "ctapara":"Book an IV therapy visit at our Hudson Serene IV Bar and choose a blend that fits your goals &mdash; or try our <a href=\"/hydration-bar/\">Serene Hydration Bar</a> to find your best-match drip in seconds.",
},
# ---------------- HORMONE OPTIMIZATION ----------------
{
 "slug":"hormone-optimization","crumb":"Hormone Optimization","area_kw":"hormone and wellness care",
 "title":"Hormone Optimization in Hudson, OH | Physician-Led Wellness | Serene Med Spa",
 "desc":"Physician-led hormone optimization in Hudson, Ohio at Serene Med Spa. Personalized, medically supervised care to help you feel balanced and your best. Book today.",
 "ogtitle":"Hormone Optimization in Hudson, OH","ogdesc":"Physician-led, personalized hormone optimization in Hudson, Ohio. Feel balanced and your best. Book today.",
 "proc_name":"Hormone Optimization","proc_alt":"Physician-Supervised Hormone Wellness",
 "how":"After evaluation and appropriate lab testing, a physician develops a personalized, medically supervised plan to help optimize hormone balance and overall wellness.","body":"Systemic",
 "eyebrow":"Hormone Optimization &middot; Hudson, OH","h1":"Hormone Optimization in Hudson, Ohio",
 "hero":"Feel more like yourself again &mdash; personalized, physician-led hormone and wellness care built around your labs, symptoms, and goals.",
 "trust":["Physician-Led","Personalized Plans","Lab-Guided","Ongoing Support"],
 "introh2":"Balanced, personalized, physician-led",
 "introlead":"As hormones shift with age, many people notice changes in energy, mood, sleep, and overall wellbeing. Hormone optimization is a personalized, medically supervised approach to help you feel balanced and your best again.",
 "intropara":"At Serene Med Spa in Hudson, hormone optimization begins with a thorough evaluation and appropriate lab testing, so your plan is guided by real data &mdash; not guesswork. Our board-certified physicians design and supervise your care, monitor your progress, and adjust as needed. This is individualized medical care; candidacy, approach, and results depend on your health and are determined with your physician.",
 "treyebrow":"What People Notice","treh2":"Common Goals",
 "cards":[
   ("Energy &amp; Vitality","Many people seek support for low energy and everyday fatigue."),
   ("Mood &amp; Focus","Address changes in mood, motivation, and mental clarity."),
   ("Sleep","Support healthier, more restful sleep patterns."),
   ("Body Composition","Support wellness goals alongside diet, exercise, and lifestyle."),
   ("Libido &amp; Wellbeing","Address changes in libido and overall sense of wellbeing."),
   ("Lab-Guided Care","Decisions are guided by testing and monitored over time."),
 ],
 "steps":_steps(
   "We start with a thorough consultation and appropriate lab work to understand your symptoms and baseline.",
   "Your physician reviews your results and builds a personalized, medically supervised plan &mdash; if appropriate for you.",
   "We monitor how you feel and re-test as needed, adjusting your plan to keep it safe and effective.",
   "Hormone optimization is ongoing care. We provide regular follow-up and support along the way."),
 "whyh2":"Why choose Serene for hormone optimization in Hudson",
 "whypara":"Hormone care should be individualized, lab-guided, and physician-supervised &mdash; never one-size-fits-all. At Serene, your care is led by board-certified physicians who take the time to understand your health and goals, right here in Hudson.",
 "faqh2":"Hormone Optimization FAQ",
 "faqs":[
   ("How do I know if hormone optimization is right for me?","It starts with a consultation and appropriate lab testing. Your physician will review your symptoms and results and advise whether it&rsquo;s appropriate for you."),
   ("Is it physician-supervised?","Yes. At Serene, hormone optimization is designed, prescribed, and monitored by our board-certified physicians as individualized medical care."),
   ("Will you run lab tests?","Yes &mdash; appropriate lab testing guides your plan and helps us monitor your progress and safety over time."),
   ("How soon will I feel a difference?","It varies by person and plan. We set realistic expectations and adjust your care based on how you feel and your follow-up labs."),
   ("What results can I expect?","Results are individual and depend on your health, labs, and plan. Your physician will discuss realistic, personalized expectations with you."),
 ],
 "related":["weight-loss","morpheus8","botox"],
 "ctah2":"Ready to feel like yourself again?",
 "ctapara":"Book a hormone optimization consultation with our Hudson physicians for personalized, lab-guided care.",
},
]
