# -*- coding: utf-8 -*-
PAGES = [
{
 "slug":"emsculpt-neo","crumb":"EMSCULPT NEO",
 "title":"EMSCULPT NEO in Hudson, OH | Build Muscle &amp; Burn Fat | Serene Med Spa",
 "desc":"Non-invasive EMSCULPT NEO body sculpting in Hudson, Ohio. Build muscle and reduce fat with no surgery and no downtime — physician-led care at Serene Med Spa. Book today.",
 "ogtitle":"EMSCULPT NEO Body Sculpting in Hudson, OH",
 "ogdesc":"Build muscle and reduce fat with non-invasive EMSCULPT NEO at Serene Med Spa in Hudson. No surgery, no downtime.",
 "proc_name":"EMSCULPT NEO Body Contouring","proc_alt":"Non-Invasive Muscle Building &amp; Fat Reduction",
 "how":"EMSCULPT NEO combines synchronized radiofrequency heating and high-intensity electromagnetic (HIFEM+) energy to build muscle and reduce fat in targeted areas in a single treatment.",
 "body":"Abdomen, Buttocks, Arms, Thighs, Calves",
 "eyebrow":"EMSCULPT NEO &middot; Body Sculpting &middot; Hudson, OH",
 "h1":"EMSCULPT NEO in Hudson, Ohio",
 "hero":"Build muscle and reduce stubborn fat at the same time &mdash; no surgery, no needles, and no downtime. Physician-led body sculpting at Serene Med Spa.",
 "trust":["Non-Invasive","No Downtime","Build Muscle + Burn Fat","FDA-Cleared Technology"],
 "introh2":"Build muscle and burn fat &mdash; in one treatment",
 "introlead":"EMSCULPT NEO is the only non-invasive body-sculpting treatment that builds muscle and reduces fat at the same time, using synchronized radiofrequency and high-intensity electromagnetic energy.",
 "intropara":"At Serene Med Spa in Hudson, EMSCULPT NEO is a comfortable treatment you can do while you relax &mdash; no surgery, no needles, and no recovery time. It&rsquo;s a favorite for toning the abdomen and lifting the buttocks, as well as sculpting the arms, thighs, and calves. Results build gradually in the weeks following your sessions, and individual results vary.",
 "treyebrow":"Where It Works","treh2":"Areas We Sculpt",
 "cards":[
   ("Abdomen","Strengthen and define the core while reducing fat over the midsection."),
   ("Buttocks","A non-surgical lift &mdash; tone and firm without implants or injections."),
   ("Arms","Sculpt the biceps and triceps for a firmer, more defined upper arm."),
   ("Thighs","Tone the inner and outer thighs as part of a balanced lower-body plan."),
   ("Calves","Build and shape the calves &mdash; an area that&rsquo;s hard to target with exercise alone."),
   ("Flanks","Address the sides of the waist to complement your core results."),
 ],
 "steps":[
   ("Consultation","We review your goals and body-sculpting priorities, then map out the areas and number of sessions that make sense for you."),
   ("Treatment","You relax while the applicator delivers muscle contractions and gentle heating. Most sessions take about 30 minutes."),
   ("Results","Muscle and fat changes develop over the weeks following your sessions. Many people feel stronger and notice more definition over time; results vary."),
   ("Maintenance","We&rsquo;ll suggest a simple schedule of periodic sessions to help you hold and build on your results."),
 ],
 "whyh2":"Why choose Serene for EMSCULPT NEO in Hudson",
 "whypara":"Body sculpting works best as part of a thoughtful plan &mdash; not a one-size-fits-all package. At Serene, your treatment is guided by our board-certified physicians, Dr. Robin Arora and Dr. Shweta Arora, who tailor your sessions to your goals and help you set realistic expectations, right here in Hudson.",
 "faqh2":"EMSCULPT NEO FAQ",
 "faqs":[
   ("How does EMSCULPT NEO work?","It pairs radiofrequency heating with high-intensity electromagnetic energy to build muscle and reduce fat in the treated area at the same time &mdash; without surgery."),
   ("Is the treatment painful?","Most people describe it as an intense workout with a warming sensation. It&rsquo;s well tolerated, and you can relax during the session."),
   ("How many sessions will I need?","A typical plan is a series of sessions spaced over a couple of weeks. We&rsquo;ll recommend a plan for your goals at your consultation."),
   ("Is there any downtime?","No. EMSCULPT NEO is non-invasive, so most people return to their normal day right away."),
   ("Who is a good candidate?","It&rsquo;s a great option for healthy adults looking to tone and strengthen specific areas. We&rsquo;ll confirm it&rsquo;s right for you during your visit."),
 ],
 "related":["morpheus8","weight-loss","fillers"],
 "ctah2":"Ready to sculpt and strengthen?",
 "ctapara":"Book an EMSCULPT NEO consultation with our Hudson team and build a plan around your goals.",
},
{
 "slug":"laser-skin","crumb":"Laser Skin (PICO)",
 "title":"PICO Laser Skin Treatment in Hudson, OH | Pigmentation &amp; Tone | Serene Med Spa",
 "desc":"PICO laser skin treatments in Hudson, Ohio for sun spots, pigmentation, uneven tone, and tattoo removal. Physician-led care at Serene Med Spa. Book your consultation.",
 "ogtitle":"PICO Laser Skin Treatments in Hudson, OH",
 "ogdesc":"Fade sun spots, pigmentation, and uneven tone with advanced PICO laser technology at Serene Med Spa in Hudson.",
 "proc_name":"PICO Laser Skin Treatment","proc_alt":"Picosecond Laser Skin Revitalization",
 "how":"A picosecond laser delivers ultra-short pulses of energy that break up unwanted pigment and stimulate the skin&rsquo;s natural renewal for a clearer, more even tone.",
 "body":"Face, Neck, Chest, Hands, Body",
 "eyebrow":"Laser Skin Revitalization &middot; Hudson, OH",
 "h1":"PICO Laser Skin Treatments in Hudson, Ohio",
 "hero":"Fade sun damage, dark spots, and uneven tone &mdash; and refresh your skin from within &mdash; with advanced PICO laser technology, guided by board-certified physicians.",
 "trust":["Physician-Led","Minimal Downtime","All-Season Skin Renewal","Advanced PICO Technology"],
 "introh2":"Clearer, brighter, more even-toned skin",
 "introlead":"PICO laser technology uses ultra-fast pulses of energy to target unwanted pigment and awaken your skin&rsquo;s natural renewal &mdash; often with less heat and less downtime than older lasers.",
 "intropara":"At Serene Med Spa in Hudson, we use PICO laser treatments to soften sun spots, brown patches, and uneven tone, and to refresh overall texture and radiance. Because every complexion is different, your treatment is planned by our physicians and tailored to your skin and goals. A series of sessions usually delivers the best results, and individual results vary.",
 "treyebrow":"What It Treats","treh2":"Concerns We Target",
 "cards":[
   ("Sun &amp; Age Spots","Break up brown spots and sun damage on the face, hands, chest, and more."),
   ("Uneven Pigmentation","Soften patches of discoloration for a more even, uniform tone."),
   ("Tone &amp; Texture","Refresh rough, dull-looking skin for a smoother, brighter surface."),
   ("Dullness &amp; Radiance","Stimulate renewal to bring back a healthy, lit-from-within glow."),
   ("Enlarged Pores","Refine the look of pores as part of an overall skin-quality plan."),
   ("Tattoo Removal","Gradually fade unwanted ink with picosecond precision over a series of sessions."),
 ],
 "steps":[
   ("Consultation","We assess your skin, discuss your concerns, and design a treatment plan suited to your complexion and goals."),
   ("Treatment","The laser is passed over the treatment area. Most sessions are quick, and we keep you comfortable throughout."),
   ("Recovery","You may notice mild redness or a warm, sun-kissed feeling for a short time. We&rsquo;ll share simple aftercare and sun-protection tips."),
   ("Results","Pigment fades and clarity improves over the days and weeks after each session. A series builds the best, most even results; results vary."),
 ],
 "whyh2":"Why choose Serene for laser skin treatments in Hudson",
 "whypara":"Lasers are powerful tools &mdash; and the right settings for your skin matter. At Serene, your treatment is planned and supervised by our board-certified physicians, Dr. Robin Arora and Dr. Shweta Arora, so your care is both effective and appropriate for your skin, right here in Hudson.",
 "faqh2":"PICO Laser FAQ",
 "faqs":[
   ("What can PICO laser treat?","It&rsquo;s used for sun spots, uneven pigmentation, dullness, overall tone and texture, and tattoo removal. We&rsquo;ll confirm the best plan for your skin at your consultation."),
   ("Is there downtime?","Most people have only mild, short-lived redness. We&rsquo;ll give you aftercare guidance and stress the importance of sun protection."),
   ("How many sessions will I need?","A series of sessions usually produces the best results. The number depends on your concern and skin, which we&rsquo;ll review together."),
   ("Does it hurt?","Most people tolerate it well and describe a quick, snapping sensation. Comfort measures are available."),
   ("Is it right for my skin?","Because settings and suitability vary by skin type and concern, our physicians will evaluate your skin and recommend the safest, most effective approach for you."),
 ],
 "related":["morpheus8","botox","fillers"],
 "ctah2":"Ready for clearer, brighter skin?",
 "ctapara":"Book a laser skin consultation with our Hudson team and get a plan tailored to your complexion.",
},
{
 "slug":"laser-hair-removal","crumb":"Laser Hair Removal",
 "title":"Laser Hair Removal in Hudson, OH | Smooth, Lasting Results | Serene Med Spa",
 "desc":"Laser hair removal in Hudson, Ohio at Serene Med Spa. Smooth, lasting hair reduction on the face and body with physician-led care. Book your consultation today.",
 "ogtitle":"Laser Hair Removal in Hudson, OH",
 "ogdesc":"Smooth, lasting hair reduction on the face and body at Serene Med Spa in Hudson. Physician-led care. Book today.",
 "proc_name":"Laser Hair Removal","proc_alt":"Laser Hair Reduction",
 "how":"Laser energy targets the pigment in hair follicles to reduce unwanted hair over a series of treatments spaced several weeks apart.",
 "body":"Face, Body",
 "eyebrow":"Laser Hair Removal &middot; Hudson, OH",
 "h1":"Laser Hair Removal in Hudson, Ohio",
 "hero":"Say goodbye to shaving and waxing. Smooth, lasting hair reduction on the face and body, comfortably delivered by our Hudson team.",
 "trust":["Comfortable Treatments","Face &amp; Body","Lasting Reduction","Physician-Led Care"],
 "introh2":"Smoother skin, far less upkeep",
 "introlead":"Laser hair removal targets the follicle to reduce unwanted hair over a series of sessions &mdash; so you can spend less time shaving and waxing, and more time enjoying smooth skin.",
 "intropara":"At Serene Med Spa in Hudson, we treat both small and large areas, from the upper lip to the legs and back. Because hair grows in cycles, a series of treatments spaced a few weeks apart gives the best, longest-lasting results. Your plan is guided by our physicians and tailored to your skin and hair; individual results vary.",
 "treyebrow":"Popular Areas","treh2":"Areas We Treat",
 "cards":[
   ("Legs","Full or lower legs &mdash; one of the most popular areas for smooth, lasting results."),
   ("Underarms","Quick to treat and a favorite for ditching daily shaving."),
   ("Bikini &amp; Brazilian","Comfortable, precise treatment for the bikini line and beyond."),
   ("Face &amp; Upper Lip","Gentle treatment for the upper lip, chin, and other facial areas."),
   ("Back &amp; Chest","Great for larger areas that are hard to manage on your own."),
   ("Arms &amp; Underarms","Smooth the forearms and upper arms for an even, polished look."),
 ],
 "steps":[
   ("Consultation","We look at your skin and hair, discuss your goals, and design a treatment plan and schedule that fits you."),
   ("Treatment","The device is passed over the area, delivering pulses of energy with cooling for comfort. Small areas take just minutes."),
   ("Between Sessions","Because hair grows in cycles, you&rsquo;ll return every few weeks so we can treat follicles as they enter the active growth phase."),
   ("Results","Hair grows back finer and sparser over your series. We&rsquo;ll recommend occasional maintenance to keep skin smooth; results vary."),
 ],
 "whyh2":"Why choose Serene for laser hair removal in Hudson",
 "whypara":"Comfort, safety, and the right settings for your skin make all the difference. At Serene, your treatment is overseen by our board-certified physicians, Dr. Robin Arora and Dr. Shweta Arora, so you get effective results in a calm, professional setting right here in Hudson.",
 "faqh2":"Laser Hair Removal FAQ",
 "faqs":[
   ("How many sessions will I need?","Most people need a series of sessions spaced several weeks apart, because hair grows in cycles. We&rsquo;ll give you a personalized estimate at your consultation."),
   ("Does it hurt?","Most people describe a quick snap with each pulse. Built-in cooling helps keep treatment comfortable."),
   ("Is laser hair removal permanent?","It provides long-lasting hair reduction. Many people need occasional maintenance sessions to keep results looking their best."),
   ("What areas can be treated?","From the upper lip and underarms to legs, back, and bikini area. We&rsquo;ll confirm the best plan for you."),
   ("How should I prepare?","Avoid waxing or plucking beforehand, shave the area as directed, and stay out of the sun. We&rsquo;ll give you complete prep instructions."),
 ],
 "related":["morpheus8","botox","fillers"],
 "ctah2":"Ready to put shaving behind you?",
 "ctapara":"Book a laser hair removal consultation with our Hudson team and start your smooth-skin plan.",
},
{
 "slug":"hydrafacial","crumb":"HydraFacial",
 "title":"HydraFacial in Hudson, OH | Deep-Cleanse &amp; Glow | Serene Med Spa",
 "desc":"HydraFacial in Hudson, Ohio at Serene Med Spa. Cleanse, exfoliate, extract, and hydrate for an instant glow with no downtime. Book your HydraFacial today.",
 "ogtitle":"HydraFacial in Hudson, OH",
 "ogdesc":"Cleanse, exfoliate, extract, and hydrate for instant glow with no downtime. HydraFacial at Serene Med Spa in Hudson.",
 "proc_name":"HydraFacial","proc_alt":"Hydradermabrasion Facial",
 "how":"A multi-step device cleanses, exfoliates, gently extracts, and infuses the skin with hydrating and nourishing serums in a single session.",
 "body":"Face, Neck",
 "eyebrow":"HydraFacial &middot; Hudson, OH",
 "h1":"HydraFacial in Hudson, Ohio",
 "hero":"Cleanse, exfoliate, extract, and hydrate &mdash; all in one relaxing treatment that leaves your skin instantly glowing, with zero downtime.",
 "trust":["Instant Glow","No Downtime","All Skin Types","Perfect Before Events"],
 "introh2":"An instant glow, no downtime",
 "introlead":"HydraFacial is a gentle, multi-step facial that cleanses, exfoliates, extracts, and hydrates in one relaxing session &mdash; leaving your skin refreshed, smooth, and glowing.",
 "intropara":"At Serene Med Spa in Hudson, HydraFacial is a favorite for a quick reset and a pre-event glow. It suits nearly every skin type, and there&rsquo;s no downtime &mdash; many people go right back to their day (or their evening out). We can tailor the serums and boosters to your skin&rsquo;s needs, and regular treatments help maintain results over time.",
 "treyebrow":"What&rsquo;s Included","treh2":"The HydraFacial Steps",
 "cards":[
   ("Deep Cleanse","Lift away oil and impurities to prep the skin for a thorough treatment."),
   ("Gentle Exfoliation","Resurface dull, dead skin cells to reveal a smoother, fresher surface."),
   ("Painless Extractions","Clear congestion and debris from pores with gentle, comfortable suction."),
   ("Hydration Boost","Flood the skin with nourishing, hydrating serums for a dewy finish."),
   ("Targeted Boosters","Add condition-specific boosters for brightening, firming, or clarity."),
   ("Event-Ready Glow","Walk out with an immediate, camera-ready radiance &mdash; no recovery needed."),
 ],
 "steps":[
   ("Consultation","We take a quick look at your skin and choose the serums and boosters best suited to your goals."),
   ("Treatment","You relax while the HydraFacial device works through each step. Most treatments take about 30&ndash;45 minutes."),
   ("Results","Skin looks instantly brighter, smoother, and more hydrated &mdash; with no downtime, so you can head straight out."),
   ("Maintenance","Regular HydraFacials, often monthly, help keep your skin clear, hydrated, and glowing over time."),
 ],
 "whyh2":"Why choose Serene for your HydraFacial in Hudson",
 "whypara":"A great facial is about more than a glow &mdash; it&rsquo;s about caring for your skin the right way. At Serene, your treatment happens in a calm, physician-led setting, and we can connect your skincare to the rest of your plan, from injectables to laser, all in one trusted Hudson practice.",
 "faqh2":"HydraFacial FAQ",
 "faqs":[
   ("What is a HydraFacial?","It&rsquo;s a gentle, multi-step facial that cleanses, exfoliates, extracts, and hydrates the skin in one session &mdash; leaving you with an immediate glow."),
   ("Is there any downtime?","None. Most people return to their normal day right away, and skin looks great immediately."),
   ("How often should I get one?","Many people enjoy a HydraFacial monthly to maintain clear, hydrated, glowing skin, but we&rsquo;ll tailor a rhythm to your skin."),
   ("Is it good for sensitive skin?","HydraFacial is gentle and suits most skin types. We&rsquo;ll customize the serums to keep it comfortable for you."),
   ("Can I wear makeup afterward?","Yes &mdash; though many people love their fresh, bare glow and skip it. Your skin will be clean and primed."),
 ],
 "related":["botox","fillers","morpheus8"],
 "ctah2":"Ready for that fresh-facial glow?",
 "ctapara":"Book a HydraFacial with our Hudson team and treat your skin to an instant reset.",
},
{
 "slug":"diamondglow","crumb":"DiamondGlow",
 "title":"DiamondGlow Facial in Hudson, OH | Exfoliate &amp; Infuse | Serene Med Spa",
 "desc":"DiamondGlow facial in Hudson, Ohio at Serene Med Spa. Exfoliate, extract, and infuse nourishing serums for radiant skin with no downtime. Book today.",
 "ogtitle":"DiamondGlow Facial in Hudson, OH",
 "ogdesc":"Exfoliate, extract, and infuse nourishing serums for radiant, hydrated skin with no downtime. DiamondGlow at Serene Med Spa in Hudson.",
 "proc_name":"DiamondGlow Facial","proc_alt":"Diamond Microdermabrasion &amp; Serum Infusion",
 "how":"A diamond-tip device exfoliates and gently extracts debris while simultaneously infusing condition-specific serums deep into the skin.",
 "body":"Face, Neck",
 "eyebrow":"DiamondGlow &middot; Hudson, OH",
 "h1":"DiamondGlow Facial in Hudson, Ohio",
 "hero":"A next-level facial that exfoliates, extracts, and infuses nourishing serums at the same time &mdash; for smoother, brighter, deeply hydrated skin.",
 "trust":["3-in-1 Treatment","Custom Serums","No Downtime","Radiant Results"],
 "introh2":"Exfoliate, extract, and infuse &mdash; all at once",
 "introlead":"DiamondGlow uses a diamond-tip wand to gently resurface the skin while simultaneously infusing condition-specific serums &mdash; so you exfoliate, extract, and nourish in a single step.",
 "intropara":"At Serene Med Spa in Hudson, DiamondGlow is a wonderful way to brighten dull skin, smooth texture, and restore hydration with no downtime. We select serums based on your skin&rsquo;s needs &mdash; whether that&rsquo;s brightening, plumping, or clarifying &mdash; and it pairs beautifully with the rest of your skincare and injectable plan. Regular treatments help maintain that healthy glow.",
 "treyebrow":"What It Improves","treh2":"Concerns We Address",
 "cards":[
   ("Dullness &amp; Texture","Resurface tired, uneven skin for a smoother, more radiant finish."),
   ("Fine Lines","Support plumper, better-hydrated skin that helps soften the look of fine lines."),
   ("Dryness &amp; Dehydration","Infuse deeply nourishing serums for lasting, dewy hydration."),
   ("Uneven Tone","Brighten and even out the complexion with targeted serums."),
   ("Congested Pores","Gently clear buildup and debris for clearer, refined-looking skin."),
   ("Pre-Event Glow","Look luminous and camera-ready with zero downtime."),
 ],
 "steps":[
   ("Consultation","We assess your skin and select the serums that best match your goals for the day."),
   ("Treatment","The diamond-tip wand resurfaces and extracts while infusing serums. Most treatments take about 30&ndash;45 minutes."),
   ("Results","Skin looks instantly brighter, smoother, and more hydrated &mdash; with no downtime, so you can head right out."),
   ("Maintenance","Regular DiamondGlow facials help you maintain radiant, healthy-looking skin over time."),
 ],
 "whyh2":"Why choose Serene for DiamondGlow in Hudson",
 "whypara":"The right serums and a skilled hand turn a good facial into a great one. At Serene, DiamondGlow is delivered in a calm, physician-led setting, and we connect your skincare to the bigger picture &mdash; from laser to injectables &mdash; all in one trusted Hudson practice.",
 "faqh2":"DiamondGlow FAQ",
 "faqs":[
   ("What is DiamondGlow?","It&rsquo;s a 3-in-1 facial that exfoliates, extracts, and infuses condition-specific serums at the same time &mdash; for smoother, brighter, hydrated skin."),
   ("How is it different from a HydraFacial?","Both are excellent, no-downtime facials. DiamondGlow uses a diamond-tip wand and targeted serum infusion; we&rsquo;ll help you choose the best fit for your skin at your visit."),
   ("Is there downtime?","No &mdash; most people return to their day right away with an immediate glow."),
   ("How often should I get one?","Many people enjoy DiamondGlow monthly to maintain radiant, healthy skin. We&rsquo;ll suggest a rhythm for your skin."),
   ("Which serums are used?","We choose from condition-specific serums &mdash; for brightening, hydrating, or clarifying &mdash; based on your skin&rsquo;s needs that day."),
 ],
 "related":["botox","fillers","morpheus8"],
 "ctah2":"Ready to glow?",
 "ctapara":"Book a DiamondGlow facial with our Hudson team and give your skin a radiant reset.",
},
]
