# -*- coding: utf-8 -*-
# Pages added alongside the Mangomint menu rebuild (Sept 2026). Hudson-voice copy;
# the Barboursville build localizes it automatically (bv_localize.py).
def _steps(a,b,c,d): return [("Consultation",a),("Treatment",b),("Results",c),("Maintenance",d)]

PAGES4 = [
# ---------------- UNDER-EYE PRP / PRF ----------------
{
 "slug":"under-eye-prp","crumb":"Under-Eye PRP / PRF","area_kw":"under-eye rejuvenation",
 "title":"Under-Eye PRP &amp; PRF in Hudson, OH | Natural Under-Eye Rejuvenation | Serene Med Spa",
 "desc":"Under-eye PRP and PRF in Hudson, Ohio at Serene Med Spa — use your own platelets to soften dark circles, crepey skin and hollows without filler. Physician-led. Book online.",
 "ogtitle":"Under-Eye PRP &amp; PRF in Hudson, OH","ogdesc":"Brighten and smooth tired under-eyes with your own PRP or PRF in Hudson, Ohio. Physician-led. Book online.",
 "proc_name":"Under-Eye PRP / PRF","proc_alt":"Platelet-Rich Plasma &amp; Platelet-Rich Fibrin Under-Eye Treatment",
 "how":"A small sample of your blood is spun to concentrate platelets (PRP) or a slower-spun platelet-rich fibrin (PRF), which is then injected beneath the under-eye skin to stimulate collagen and improve skin quality.","body":"Under-Eyes, Tear Troughs",
 "eyebrow":"Under-Eye PRP / PRF &middot; Hudson, OH","h1":"Under-Eye PRP &amp; PRF in Hudson, Ohio",
 "hero":"Brighter, smoother under-eyes using your body&rsquo;s own platelets &mdash; a natural option for dark circles, crepey skin and mild hollowing, with no filler.",
 "trust":["Uses Your Own Blood","No Filler","Improves Skin Quality","Physician-Led"],
 "introh2":"A natural approach to tired-looking eyes",
 "introlead":"The under-eye area is thin, delicate and often the first place to show fatigue. PRP (platelet-rich plasma) and PRF (platelet-rich fibrin) concentrate the growth factors in your own blood and place them exactly where the skin needs support &mdash; building collagen and improving texture, tone and thickness over time.",
 "intropara":"At Serene Med Spa in Hudson, we offer both PRP and PRF for the under-eyes. PRF is spun more slowly and without anticoagulant, so it forms a soft fibrin scaffold that releases growth factors gradually &mdash; many patients like it for a longer, more sustained effect. Neither adds volume the way filler does, which is exactly why it suits patients who want a refreshed look without the risk of puffiness. Results build over a series of sessions and individual results vary.",
 "treyebrow":"What It Improves","treh2":"Good Candidates",
 "cards":[
   ("Dark Circles","Improve the thin, shadowed skin that makes circles look darker."),
   ("Crepey Texture","Thicken and smooth fine, crinkly under-eye skin."),
   ("Mild Hollowing","Soften early tear-trough hollows without adding filler."),
   ("Filler-Averse Patients","A natural option if you&rsquo;d rather avoid hyaluronic acid filler."),
   ("Pairs With Filler","Can be combined with under-eye filler or Skinvive for skin quality plus volume."),
   ("Men &amp; Women","Suitable for most skin types and tones."),
 ],
 "steps":_steps(
   "We assess your under-eye concern and decide whether PRP, PRF, filler or a combination will give the most natural result.",
   "A small blood draw is spun in-office; after numbing, the PRP or PRF is placed beneath the under-eye skin with a fine cannula or needle.",
   "Skin quality improves gradually over 4&ndash;8 weeks as collagen builds. Most patients see the best result after a series of 2&ndash;3 sessions.",
   "A maintenance session every 6&ndash;12 months helps sustain the improvement."),
 "whyh2":"Why choose Serene for under-eye PRP in Hudson",
 "whypara":"The under-eye is one of the most technique-sensitive areas of the face. At Serene, PRP and PRF are performed by our physician-led team with cannula technique where appropriate for comfort and safety &mdash; right here in Hudson.",
 "faqh2":"Under-Eye PRP / PRF FAQ",
 "faqs":[
   ("What&rsquo;s the difference between PRP and PRF?","Both come from your own blood. PRP is spun faster and is a liquid concentrate of platelets; PRF is spun slower without additives, forming a gel-like fibrin matrix that releases growth factors more gradually. We&rsquo;ll recommend the right one for you."),
   ("Will it fill my hollows?","PRP and PRF improve skin quality rather than adding volume. For true hollowing, we may pair them with under-eye filler or Skinvive."),
   ("How many sessions do I need?","Most patients do a series of 2&ndash;3 sessions spaced about a month apart, then maintain every 6&ndash;12 months."),
   ("Is there downtime?","Expect mild swelling and possible bruising for a few days. Most people return to normal activities right away."),
   ("How much does it cost?","Under-eye PRP is $400 and PRF is $600 per session. You can book online and your injector will confirm the plan at your visit."),
 ],
 "related":["fillers","botox","morpheus8"],
 "ctah2":"Ready for brighter under-eyes?",
 "ctapara":"Book under-eye PRP or PRF online with our Hudson team, or start with a free consultation.",
},
# ---------------- KENALOG INJECTIONS ----------------
{
 "slug":"kenalog","crumb":"Kenalog Injections","area_kw":"scar &amp; cyst injections",
 "title":"Kenalog Injections in Hudson, OH | Keloid, Scar &amp; Cyst Treatment | Serene Med Spa",
 "desc":"Kenalog (triamcinolone) injections in Hudson, Ohio at Serene Med Spa — physician-performed steroid injections to flatten keloids and raised scars and calm inflamed cysts. $75. Book online.",
 "ogtitle":"Kenalog Injections in Hudson, OH","ogdesc":"Flatten keloids and raised scars and calm inflamed cysts with physician-performed Kenalog injections in Hudson, Ohio. Book online.",
 "proc_name":"Kenalog Injection","proc_alt":"Intralesional Triamcinolone (Steroid) Injection",
 "how":"A small amount of diluted triamcinolone acetonide (Kenalog) is injected directly into a raised scar, keloid or inflamed cyst to reduce inflammation and soften and flatten the tissue.","body":"Face, Ears, Chest, Shoulders, Back",
 "eyebrow":"Kenalog Injections &middot; Hudson, OH","h1":"Kenalog Injections in Hudson, Ohio",
 "hero":"Quick, physician-performed steroid injections to flatten keloids and raised scars and settle painful, inflamed cysts &mdash; usually in a 15-minute visit.",
 "trust":["15-Minute Visit","Physician-Performed","Flattens Raised Scars","$75 per Session"],
 "introh2":"Small injection, big relief",
 "introlead":"Kenalog is the brand name for triamcinolone acetonide, a corticosteroid that has been used for decades to treat raised scars, keloids and inflamed skin lesions. Injected directly into the tissue, it reduces inflammation and slows the overactive collagen that makes scars thick and raised.",
 "intropara":"At Serene Med Spa in Hudson, Kenalog injections are performed by our physician-led team. They&rsquo;re most often used for keloids and hypertrophic scars (including piercing and surgical scars), for large, painful inflamed acne cysts, and as part of a scar-improvement plan alongside microneedling or laser resurfacing. Treatment is fast, typically needs little or no downtime, and can be repeated every 4&ndash;6 weeks until the desired improvement is reached. Individual results vary.",
 "treyebrow":"What We Treat","treh2":"Common Uses",
 "cards":[
   ("Keloids","Soften and flatten thick keloid scars on the ears, chest, shoulders and jawline."),
   ("Hypertrophic Scars","Reduce raised surgical, injury or piercing scars."),
   ("Inflamed Acne Cysts","Calm a large, painful cyst quickly &mdash; often within 24&ndash;48 hours."),
   ("Itchy, Tender Scars","Relieve the itch and tenderness that often come with raised scars."),
   ("Scar-Revision Plans","Pairs with microneedling and laser resurfacing for stubborn scars."),
   ("Alopecia Areata Patches","Physician-assessed intralesional treatment for small patches of hair loss."),
 ],
 "steps":_steps(
   "We examine the scar or lesion, confirm Kenalog is appropriate, and choose the right concentration for the area.",
   "After cleansing (and numbing if needed), a small amount of diluted Kenalog is injected into the tissue. The visit usually takes about 15 minutes.",
   "Cysts typically settle within days. Scars soften and flatten gradually over 2&ndash;6 weeks per session.",
   "Raised scars are usually treated every 4&ndash;6 weeks for a series of 2&ndash;4 sessions, then as needed."),
 "whyh2":"Why choose Serene for Kenalog injections in Hudson",
 "whypara":"Dose and depth matter &mdash; too much steroid can thin surrounding skin. At Serene, injections are performed or supervised by board-certified physicians who tailor the concentration to your scar and skin type, right here in Hudson.",
 "faqh2":"Kenalog Injection FAQ",
 "faqs":[
   ("Does it hurt?","There&rsquo;s a brief sting as the medication goes in, especially in dense scar tissue. We can numb the area first, and the whole visit is quick."),
   ("How many treatments will I need?","An inflamed cyst usually needs one injection. Keloids and hypertrophic scars often need a series of 2&ndash;4 sessions spaced 4&ndash;6 weeks apart."),
   ("Are there side effects?","The most common are temporary lightening or slight thinning of the skin at the injection site and small dimpling if too much is used. Our physicians use conservative, diluted doses to minimize this."),
   ("Will the scar disappear completely?","Kenalog flattens and softens raised scars and reduces redness, itch and tenderness. It doesn&rsquo;t erase a scar entirely; for the best result we may combine it with microneedling or laser."),
   ("How much does it cost?","Kenalog injections are $75 per session (per treated lesion or area). You can book online and we&rsquo;ll confirm the plan at your visit."),
 ],
 "related":["morpheus8","botox","fillers"],
 "ctah2":"Ready to flatten that scar or calm that cyst?",
 "ctapara":"Book a Kenalog injection online with our Hudson team &mdash; most visits take about 15 minutes.",
},
# ---------------- SCULPTRA BBL ----------------
{
 "slug":"sculptra-bbl","crumb":"Sculptra BBL","area_kw":"non-surgical butt lift",
 "title":"Sculptra BBL in Hudson, OH | Non-Surgical Butt Lift | Serene Med Spa",
 "desc":"Sculptra BBL in Hudson, Ohio at Serene Med Spa — a non-surgical butt lift that builds your own collagen for smoother, fuller, lifted contours. No surgery, no implants. Physician-performed.",
 "ogtitle":"Sculptra BBL in Hudson, OH","ogdesc":"Non-surgical butt lift with Sculptra in Hudson, Ohio — fuller, smoother, lifted contours with no surgery or downtime. Physician-performed.",
 "proc_name":"Sculptra BBL","proc_alt":"Non-Surgical Brazilian Butt Lift with Poly-L-Lactic Acid",
 "how":"Sculptra (poly-L-lactic acid) is injected into the buttocks and hip dips where it stimulates your own collagen over several months, gradually adding fullness, lift and smoother skin without surgery or implants.","body":"Buttocks, Hip Dips, Thighs",
 "eyebrow":"Sculptra BBL &middot; Hudson, OH","h1":"Sculptra BBL in Hudson, Ohio",
 "hero":"A non-surgical butt lift that uses your own collagen &mdash; fuller, smoother, lifted contours with no anesthesia, no implants and no recovery weeks.",
 "trust":["No Surgery","Builds Your Own Collagen","Smooths Cellulite &amp; Hip Dips","Physician-Performed"],
 "introh2":"Lift and shape &mdash; without the operating room",
 "introlead":"A Sculptra BBL uses poly-L-lactic acid, the same collagen biostimulator we use in the face, in larger amounts across the buttocks and hip dips. Over the following months it prompts your body to build its own collagen, gradually adding volume, lift and smoother skin texture.",
 "intropara":"At Serene Med Spa in Hudson, Sculptra BBL is performed by our board-certified physicians for patients who want a subtle-to-moderate improvement in shape, hip dips or crepey, dimpled skin without the risks and downtime of surgical fat transfer. Results are gradual and natural-looking &mdash; nobody will know you had anything done &mdash; and typically last around two years. Sculptra is FDA-approved for the face; buttock treatment is an off-label use performed by physicians. Sculptra BBL starts at $6,000 and is planned at a consultation, not booked online, because the number of vials depends on your anatomy and goals.",
 "treyebrow":"What It Improves","treh2":"Good Candidates",
 "cards":[
   ("Hip Dips","Fill the indentation between the hip and thigh for a smoother curve."),
   ("Subtle Volume &amp; Lift","Add gradual, natural fullness and a lifted look to the upper buttocks."),
   ("Cellulite &amp; Dimpling","Collagen thickens the skin to soften dimpling and crepey texture."),
   ("Post-Weight-Loss Laxity","Restore fullness and firmness lost with weight loss or GLP-1 treatment."),
   ("Not Ready for Surgery","For patients who want improvement without anesthesia, scars or weeks of recovery."),
   ("Pairs With EvolveX","Combine with EvolveX or Morpheus8 Body for tightening and toning."),
 ],
 "steps":_steps(
   "Your physician reviews your goals, assesses skin and volume, and maps the treatment plan and number of vials.",
   "After numbing, Sculptra is placed across the planned areas. Sessions take about an hour; most patients need 2&ndash;3 sessions spaced 4&ndash;6 weeks apart.",
   "Volume from the initial water in the product settles within days; the real result builds gradually over 3&ndash;6 months as collagen forms.",
   "Results typically last about two years. A single touch-up session helps maintain the look."),
 "whyh2":"Why choose Serene for Sculptra BBL in Hudson",
 "whypara":"Large-volume Sculptra is an advanced injectable procedure. At Serene, it is planned and performed by board-certified physicians with a conservative, staged approach for smooth, even results &mdash; right here in Hudson.",
 "faqh2":"Sculptra BBL FAQ",
 "faqs":[
   ("How is this different from a surgical BBL?","A surgical BBL transfers your own fat under anesthesia with weeks of recovery. Sculptra BBL is an in-office injectable that builds collagen gradually with essentially no downtime. Results are more subtle than surgery, which is what most of our patients want."),
   ("How many vials will I need?","Most patients use 10 to 20 vials over 2&ndash;3 sessions depending on their anatomy and goals. We&rsquo;ll give you an exact plan and price at your consultation."),
   ("When will I see results?","Collagen builds over 3&ndash;6 months, with improvement continuing after your final session. Early swelling gives a preview that settles within a few days."),
   ("Is there downtime?","Very little. Expect some swelling, tenderness and possible bruising for a few days. We&rsquo;ll ask you to massage the area for 5 days and avoid intense exercise for 48 hours."),
   ("How much does it cost?","Sculptra BBL starts at $6,000 and is priced by the number of vials in your plan. A $500 deposit reserves your first session after your consultation."),
 ],
 "related":["morpheus8","fillers","botox"],
 "ctah2":"Curious about a non-surgical lift?",
 "ctapara":"Book a consultation with our Hudson physicians to map your Sculptra BBL plan.",
},
]
