# -*- coding: utf-8 -*-
# service_cities_data.py — Hudson: service + city landing pages ("Dermal Fillers in Akron, OH").
# Built from Search Console data (28 days to Sept 2026): these are queries where the Hudson site
# already ranks ~30 with high impressions and zero clicks. build_service_cities.py renders them.
# Prices here must match build_pricing.py. Edit copy here, not in the builder.

SC_PAGES = [

# ---------- DERMAL FILLERS — AKRON (121 impressions, 0 clicks) ----------
{
 "slug":"dermal-fillers-akron-oh", "service":"Dermal Fillers", "service_url":"/fillers/",
 "city":"Akron", "city_state":"Akron, OH", "also":["Fairlawn, OH","Tallmadge, OH","Bath, OH","Copley, OH"],
 "title":"Dermal Fillers in Akron, OH | $500/Syringe | Serene Med Spa",
 "desc":"Physician-injected dermal fillers for Akron, OH. Juv&eacute;derm, Restylane and Radiesse, $500 a syringe, 25 minutes up Route 8 in Hudson. Free consultation.",
 "eyebrow":"Dermal Fillers &middot; Serving Akron, OH",
 "h1":"Dermal Fillers for Akron, Ohio",
 "hero":"Juv&eacute;derm, Restylane and Radiesse injected by board-certified physicians &mdash; not a rotating injector &mdash; at $500 a syringe, posted online before you book. We&rsquo;re 25 minutes up Route 8 in downtown Hudson.",
 "drive":"About 25 minutes from downtown Akron",
 "introh2":"Where Akron goes for filler done by a doctor",
 "introlead":"Akron has plenty of places to buy a syringe of filler. What is harder to find is a practice where a board-certified physician does the assessment <em>and</em> the injection, and where the price is on the website before you walk in.",
 "intro":"<p>At Serene Med Spa, Dr. Shweta Arora (anesthesiology, aesthetic medicine) and Dr. Robin Arora (internal medicine, nephrology) own the practice and treat every patient personally. Dermal filler is <strong>$500 per syringe</strong> and three Juv&eacute;derm syringes are <strong>$1,400</strong> &mdash; the same numbers whether you are coming from Highland Square, West Akron, Ellet or Firestone Park.</p><p>Filler is not one product. We carry the full Juv&eacute;derm family plus Restylane and Radiesse, because the right choice depends on where it is going: a soft, flexible gel for lips, a firmer one for jawline and chin, a fine particle for under the eyes, and a collagen-stimulating option like Radiesse for the mid-face. Matching product to anatomy is most of what separates a good result from an obvious one.</p><p>As an <strong>Allergan Platinum</strong> practice, we can also stack All&#275; rewards on Juv&eacute;derm treatments, and filler can be dissolved with hyaluronidase ($150+) if you ever want it reversed &mdash; a conversation worth having <em>before</em> anyone injects you.</p>",
 "price_rows":[("Dermal Filler &mdash; per syringe","$500"),("3 Juv&eacute;derm Syringes","$1,400"),("Lip Filler &mdash; Full Syringe","$500"),("Lip Filler &mdash; Half Syringe (Mini Pout)","$300"),("Cheek, Jawline, Chin or Under-Eye Filler","$500 /syringe"),("Radiesse","$500 /syringe"),("Filler Reversal (hyaluronidase)","$150+")],
 "directions":"<p><strong>From downtown Akron (about 15 miles):</strong> OH-8 North for roughly 12 miles, exit at OH-303 (Streetsboro Rd) and head east. We are at 50 W Streetsboro St, Suite 2, just before the Route 91 light in downtown Hudson.</p><p><strong>From Fairlawn, Copley or Bath:</strong> I-77 North to OH-8 North, then OH-303 East &mdash; about 25 to 30 minutes. <strong>From Ellet or Tallmadge:</strong> OH-91 North straight into Hudson, about 20 minutes.</p>",
 "origin_q":"Akron,+OH",
 "faqs":[
  ("How much do dermal fillers cost near Akron?","Dermal filler is $500 per syringe at Serene Med Spa in Hudson, and three Juv&eacute;derm syringes are $1,400. Lip filler is $500 for a full syringe or $300 for a half-syringe Mini Pout. There is no consultation fee."),
  ("Is there a filler injector in Akron itself?","Our Ohio office is in Hudson, about 25 minutes north of downtown Akron via Route 8. We treat patients from across Akron, Fairlawn, Tallmadge, Copley and Bath. We also have a location in Barboursville, WV."),
  ("Who does the injecting?","Board-certified physicians &mdash; Dr. Shweta Arora and Dr. Robin Arora. They do your consultation, your injection and your follow-up. You will not be handed off to a different injector each visit."),
  ("How long do dermal fillers last?","It depends on the product and the area. Lip filler typically lasts 6 to 12 months; cheek and jawline filler often lasts 12 to 18 months. Areas that move constantly metabolize filler faster. Individual results vary."),
  ("Can I be treated the same day I drive up from Akron?","Usually yes. If you are a good candidate, filler can be placed at the consultation visit so one drive covers both. Tell us when you book and we will schedule enough time."),
  ("What if I do not like the result?","Hyaluronic acid fillers &mdash; Juv&eacute;derm, Restylane and most of what we place &mdash; can be dissolved with hyaluronidase, priced from $150. Radiesse and Sculptra are not reversible, which is part of why the product choice matters."),
  ("Do you take All&#275; points?","Yes. We are an Allergan Partner Privileges Platinum practice, so All&#275; members earn and redeem points on Juv&eacute;derm and Botox treatments here."),
 ],
 "related":[("/fillers/","All Dermal Fillers"),("/lip-filler/","Lip Filler"),("/kybella-akron-oh/","Kybella in Akron"),("/morpheus8-akron-oh/","Morpheus8 in Akron"),("/med-spa-akron-oh/","Med Spa Near Akron")],
},

# ---------- KYBELLA — AKRON (66 impressions, 0 clicks) ----------
{
 "slug":"kybella-akron-oh", "service":"Kybella", "service_url":"/kybella/",
 "city":"Akron", "city_state":"Akron, OH", "also":["Fairlawn, OH","Tallmadge, OH","Bath, OH","Cuyahoga Falls, OH"],
 "title":"Kybella in Akron, OH | $600 a Vial | Serene Med Spa Hudson",
 "desc":"Kybella double-chin treatment for Akron, OH &mdash; $600 a vial, injected by board-certified physicians in Hudson, 25 minutes up Route 8. Free consultation.",
 "eyebrow":"Kybella &middot; Serving Akron, OH",
 "h1":"Kybella for Akron, Ohio",
 "hero":"The only FDA-approved injectable that permanently destroys fat under the chin. $600 a vial, performed by board-certified physicians in Hudson &mdash; a straight shot up Route 8 from Akron.",
 "drive":"About 25 minutes from downtown Akron",
 "introh2":"Permanent, without surgery",
 "introlead":"Kybella is deoxycholic acid &mdash; a molecule your own body already uses to break down dietary fat. Injected under the chin, it destroys fat cells outright. Those cells do not come back.",
 "intro":"<p>That permanence is the appeal, and it is also why the assessment matters. Kybella treats <em>fat</em>. If what is bothering you under the chin is loose skin rather than fullness, Kybella will not fix it &mdash; and a practice that sells you vials anyway has done you no favors. At Serene, a physician examines you first and will tell you plainly if Morpheus8, a thread lift or Ultherapy PRIME is the better answer for your anatomy.</p><p>When Kybella <em>is</em> right, most Akron patients need <strong>2 to 4 sessions</strong> spaced at least a month apart, at <strong>$600 per vial</strong>. Expect real swelling for several days after each session &mdash; this is a treatment to schedule with a quiet week behind it, not before a wedding.</p><p>Both physicians who perform it here are board-certified, and the same doctor sees you through every session, which matters when you are tracking change under your own chin over several months.</p>",
 "price_rows":[("Kybella Fat Dissolver","$600 /vial"),("Typical course (2&ndash;4 sessions)","$1,200&ndash;$2,400"),("Consultation","No charge")],
 "directions":"<p><strong>From downtown Akron (about 15 miles):</strong> OH-8 North roughly 12 miles, exit OH-303 (Streetsboro Rd) east into downtown Hudson. We are at 50 W Streetsboro St, Suite 2, with free parking at the door.</p><p><strong>From Fairlawn, Bath or Copley:</strong> I-77 North to OH-8 North, then OH-303 East, about 25 to 30 minutes.</p>",
 "origin_q":"Akron,+OH",
 "faqs":[
  ("How much does Kybella cost near Akron?","Kybella is $600 per vial at Serene Med Spa in Hudson. Most patients need 2 to 4 sessions spaced at least a month apart, so a full course usually runs $1,200 to $2,400 depending on how much fullness is being treated."),
  ("Is Kybella permanent?","The fat cells Kybella destroys do not regenerate. Significant weight gain afterward can still change how the area looks, because the remaining cells can enlarge."),
  ("How much swelling should I expect?","Meaningful swelling for roughly 3 to 7 days after each session, sometimes longer after the first. Bruising, numbness and firmness under the chin are common and expected. Plan your calendar around it."),
  ("Am I a candidate if my problem is loose skin?","Probably not. Kybella dissolves fat, not skin laxity. At your consultation a physician will tell you honestly whether Kybella, Morpheus8, a PDO thread lift or Ultherapy PRIME fits what you actually have."),
  ("Is there Kybella in Akron?","Our Ohio office is in Hudson, about 25 minutes from downtown Akron via Route 8. We see Kybella patients from across Akron, Fairlawn, Tallmadge and Cuyahoga Falls."),
  ("Does it hurt?","There is burning and stinging during and shortly after the injections. We use ice and topical numbing, and the sensation settles within an hour or so."),
 ],
 "related":[("/kybella/","About Kybella"),("/kybella-cleveland-oh/","Kybella in Cleveland"),("/morpheus8-akron-oh/","Morpheus8 in Akron"),("/dermal-fillers-akron-oh/","Dermal Fillers in Akron"),("/med-spa-akron-oh/","Med Spa Near Akron")],
},

# ---------- SCULPTRA — WARREN (53 impressions, 0 clicks) ----------
{
 "slug":"sculptra-warren-oh", "service":"Sculptra", "service_url":"/sculptra/",
 "city":"Warren", "city_state":"Warren, OH", "also":["Niles, OH","Cortland, OH","Howland, OH","Girard, OH"],
 "title":"Sculptra in Warren, OH | $750 a Vial | Serene Med Spa",
 "desc":"Sculptra collagen stimulator for Warren, OH &mdash; $750 a vial, physician-injected at Serene Med Spa in Hudson, about 45 minutes west via Route 82. Free consult.",
 "eyebrow":"Sculptra &middot; Serving Warren, OH",
 "h1":"Sculptra for Warren, Ohio",
 "hero":"Sculptra does not fill &mdash; it teaches your skin to rebuild its own collagen over several months. $750 a vial, injected by board-certified physicians in Hudson, about 45 minutes west of Warren.",
 "drive":"About 45 minutes from Warren",
 "introh2":"The slow treatment, and why that is the point",
 "introlead":"Sculptra is poly-L-lactic acid. It is not a filler in the usual sense: it does not add volume on the table. It provokes a controlled healing response, and your own fibroblasts lay down new collagen over the months that follow.",
 "intro":"<p>That makes Sculptra a poor choice for anyone who wants to look different on Friday, and an excellent one for anyone who would rather not be asked what they had done. Volume arrives gradually enough that people notice you look well rather than noticing your face.</p><p>It is typically dosed as a <strong>series</strong> &mdash; commonly two to four vials over several months at <strong>$750 per vial</strong> &mdash; and the effect builds for roughly two years. Because it works with your own collagen, results depend partly on your biology, and unlike hyaluronic acid fillers, <strong>Sculptra cannot be dissolved</strong>. That is the trade for its longevity, and it is the reason we are conservative with dosing and spacing.</p><p>Warren patients generally combine the drive with a longer consultation the first time, since mapping a Sculptra plan properly takes more conversation than a syringe of filler does.</p>",
 "price_rows":[("Sculptra","$750 /vial"),("Typical series (2&ndash;4 vials over several months)","$1,500&ndash;$3,000"),("Sculptra BBL (body)","$6,000"),("Consultation","No charge")],
 "directions":"<p><strong>From Warren (about 35 miles):</strong> OH-82 West through Newton Falls and Streetsboro, then OH-303 West into downtown Hudson &mdash; roughly 45 minutes. Alternatively OH-5 West to I-80 West to OH-8 South.</p><p><strong>From Niles, Girard or Howland:</strong> pick up OH-82 West and follow the same route, about 45 to 55 minutes.</p>",
 "origin_q":"Warren,+OH",
 "faqs":[
  ("How much does Sculptra cost near Warren?","Sculptra is $750 per vial at Serene Med Spa in Hudson. Most patients need two to four vials spread over several months, so a typical plan runs $1,500 to $3,000."),
  ("How long before I see results?","Sculptra works gradually. Most people notice change around 6 to 8 weeks and see continued improvement for several months as collagen builds. Results commonly last up to two years."),
  ("How is Sculptra different from Juv&eacute;derm?","Juv&eacute;derm is hyaluronic acid and adds volume immediately; it can also be dissolved. Sculptra stimulates your own collagen over months and cannot be reversed. They solve different problems, and some patients use both."),
  ("Is there a Sculptra injector in Warren?","Our Ohio office is in Hudson, about 45 minutes west of Warren via Route 82. We treat patients from Warren, Niles, Cortland, Howland and Girard."),
  ("Does Sculptra work on the body?","Yes &mdash; Sculptra BBL for the buttocks is offered at $6,000. Body treatment uses considerably more product than facial work, which is reflected in the price."),
  ("Is it worth the drive from Warren?","Sculptra is a series, so you will make the trip more than once. Many Warren patients schedule sessions a few months apart and combine them with other treatments in the same visit. We will plan the schedule around your driving, not ours."),
 ],
 "related":[("/sculptra/","About Sculptra"),("/fillers/","Dermal Fillers"),("/morpheus8/","Morpheus8"),("/thread-lift/","PDO Thread Lift"),("/pricing/","Full Price List")],
},


# ---------- BOTOX & FILLERS — CUYAHOGA FALLS (90 impressions, 0 clicks) ----------
{
 "slug":"botox-cuyahoga-falls-oh", "service":"Botox &amp; Fillers", "service_url":"/botox/",
 "city":"Cuyahoga Falls", "city_state":"Cuyahoga Falls, OH", "also":["Stow, OH","Silver Lake, OH","Munroe Falls, OH","Northampton, OH"],
 "title":"Botox &amp; Fillers in Cuyahoga Falls, OH | $11/Unit | Serene",
 "desc":"Botox $11 a unit and dermal filler $500 a syringe for Cuyahoga Falls, OH &mdash; injected by board-certified physicians in Hudson, about 15 minutes north.",
 "eyebrow":"Botox &amp; Fillers &middot; Serving Cuyahoga Falls, OH",
 "h1":"Botox and Fillers for Cuyahoga Falls, Ohio",
 "hero":"Botox at $11 a unit, Dysport at $3.99, dermal filler at $500 a syringe &mdash; all injected by board-certified physicians. We are about 15 minutes north of the Falls in downtown Hudson.",
 "drive":"About 15 minutes from Cuyahoga Falls",
 "introh2":"Close enough to be your regular place",
 "introlead":"Cuyahoga Falls is near enough to Hudson that the drive stops being a consideration. For a treatment you repeat every three or four months, that matters more than it sounds.",
 "intro":"<p>Botox, Xeomin and Daxxify are <strong>$11 per unit</strong> and Dysport is <strong>$3.99 per Dysport unit</strong> &mdash; those are different scales, so the honest comparison is per treated area, not per unit. A standard frown-line treatment is about 20 units of Botox, or $220. Baby Botox is priced at $220 for 20 units.</p><p>Dermal filler is <strong>$500 a syringe</strong>, with three Juv&eacute;derm syringes at $1,400. We carry the full Juv&eacute;derm family plus Restylane and Radiesse, so the product gets matched to the area rather than to whatever is in the fridge.</p><p>Both physicians &mdash; Dr. Shweta Arora and Dr. Robin Arora &mdash; do their own injecting, and we are an <strong>Allergan Platinum</strong> practice, so All&#275; points earn and redeem here. Prices are published on our <a href=\"/pricing/\">pricing page</a> and are the same for everyone.</p>",
 "price_rows":[("Botox, Xeomin or Daxxify","$11 /unit"),("Dysport","$3.99 /unit"),("Baby Botox","$220 / 20 units"),("Dermal Filler","$500 /syringe"),("3 Juv&eacute;derm Syringes","$1,400"),("Lip Filler &mdash; Full / Half Syringe","$500 / $300"),("Consultation","No charge")],
 "directions":"<p><strong>From Cuyahoga Falls (about 9 miles):</strong> OH-8 North to the OH-303 (Streetsboro Rd) exit, then east into downtown Hudson &mdash; usually 15 to 18 minutes. We are at 50 W Streetsboro St, Suite 2, with free parking outside the door.</p><p><strong>From Silver Lake, Stow or Munroe Falls:</strong> OH-91 North or Hudson Drive north, about 12 to 15 minutes.</p>",
 "origin_q":"Cuyahoga+Falls,+OH",
 "faqs":[
  ("How much is Botox near Cuyahoga Falls?","Botox, Xeomin and Daxxify are $11 per unit at Serene Med Spa in Hudson, and Dysport is $3.99 per Dysport unit. A typical frown-line treatment is about 20 units, or $220. There is no consultation fee."),
  ("Botox or Dysport &mdash; which is cheaper?","They are dosed on different scales, so per-unit prices are not comparable. Dysport generally needs roughly two to three times as many units for the same effect, which puts the cost per area in a similar range. Your physician will recommend based on how you respond, not on price."),
  ("How much is filler in Cuyahoga Falls?","Dermal filler is $500 per syringe, and three Juv&eacute;derm syringes are $1,400. Lip filler is $500 for a full syringe or $300 for a half-syringe Mini Pout."),
  ("How far is it from the Falls?","About 9 miles &mdash; usually 15 to 18 minutes up Route 8 to the Route 303 exit. Parking is free and at the door."),
  ("How long does Botox last?","Most people get three to four months from a treatment. The muscles being treated, your dose and your metabolism all affect it. Individual results vary."),
  ("Can I get Botox the same day as my consultation?","Usually yes. If you are a candidate, Botox and filler can both be done at the consult visit."),
  ("Do you honor All&#275; points?","Yes. We are an Allergan Partner Privileges Platinum practice, so All&#275; members earn and redeem on Botox and Juv&eacute;derm here."),
 ],
 "related":[("/botox/","About Botox"),("/fillers/","Dermal Fillers"),("/med-spa-cuyahoga-falls-oh/","Med Spa Near Cuyahoga Falls"),("/med-spa-stow-oh/","Med Spa Near Stow"),("/pricing/","Full Price List")],
},

# ---------- DERMAL FILLERS — BROOKLYN (47 impressions, 0 clicks) ----------
{
 "slug":"dermal-fillers-brooklyn-oh", "service":"Dermal Fillers", "service_url":"/fillers/",
 "city":"Brooklyn", "city_state":"Brooklyn, OH", "also":["Parma, OH","Old Brooklyn, OH","Brooklyn Heights, OH","Independence, OH"],
 "title":"Dermal Fillers in Brooklyn, OH | $500/Syringe | Serene Med Spa",
 "desc":"Dermal fillers for Brooklyn, OH and the Parma area &mdash; Juv&eacute;derm, Restylane and Radiesse at $500 a syringe, injected by physicians in Hudson. Free consult.",
 "eyebrow":"Dermal Fillers &middot; Serving Brooklyn, OH",
 "h1":"Dermal Fillers for Brooklyn, Ohio",
 "hero":"Juv&eacute;derm, Restylane and Radiesse at $500 a syringe, injected by board-certified physicians. About 35 minutes southeast of Brooklyn, with free parking at the door.",
 "drive":"About 35 minutes from Brooklyn",
 "introh2":"Worth the drive from the west side",
 "introlead":"Brooklyn and Parma patients have no shortage of options closer to home. The ones who make the drive to Hudson tend to be looking for two specific things: a physician doing the injecting, and a price they knew before they arrived.",
 "intro":"<p>Dermal filler is <strong>$500 per syringe</strong> here, and three Juv&eacute;derm syringes are <strong>$1,400</strong>. That is published on our <a href=\"/pricing/\">pricing page</a> and does not change based on who is asking.</p><p>Dr. Shweta Arora and Dr. Robin Arora own the practice and perform the injections themselves. We carry the full Juv&eacute;derm range alongside Restylane and Radiesse, which means the product can be chosen for the anatomy &mdash; a soft gel for lips, something firmer for jawline and chin, a fine particle for the under-eye hollow, and Radiesse when the goal is structure plus collagen stimulation.</p><p>Hyaluronic acid fillers are reversible with hyaluronidase, priced from $150. We would rather discuss that at the consultation than after a result you are unhappy with.</p>",
 "price_rows":[("Dermal Filler &mdash; per syringe","$500"),("3 Juv&eacute;derm Syringes","$1,400"),("Lip Filler &mdash; Full Syringe","$500"),("Lip Filler &mdash; Half Syringe (Mini Pout)","$300"),("Cheek, Jawline, Chin or Under-Eye Filler","$500 /syringe"),("Radiesse","$500 /syringe"),("Filler Reversal (hyaluronidase)","$150+")],
 "directions":"<p><strong>From Brooklyn (about 28 miles):</strong> I-480 East to I-271 South, then exit at OH-303 (Streetsboro Rd) and head east into downtown Hudson &mdash; roughly 35 minutes outside rush hour.</p><p><strong>From Parma or Independence:</strong> I-77 South to I-271 South, then OH-303 East, about 30 to 35 minutes.</p>",
 "origin_q":"Brooklyn,+OH",
 "faqs":[
  ("How much do fillers cost near Brooklyn, OH?","Dermal filler is $500 per syringe at Serene Med Spa in Hudson, with three Juv&eacute;derm syringes at $1,400. Lip filler is $500 full or $300 for a half-syringe Mini Pout. Consultations are free."),
  ("Is there a Serene location on the west side?","No &mdash; our Ohio office is in Hudson, about 35 minutes from Brooklyn via I-480 and I-271. We also have a location in Barboursville, WV."),
  ("Who performs the injections?","Board-certified physicians, Dr. Shweta Arora and Dr. Robin Arora. The same doctor handles your consultation, treatment and follow-up."),
  ("Can filler be undone?","Hyaluronic acid fillers such as Juv&eacute;derm and Restylane can be dissolved with hyaluronidase, from $150. Radiesse and Sculptra cannot, which is why product selection is part of the consultation."),
  ("Can I do everything in one visit?","Usually yes. If you are a candidate, filler is placed at the consultation visit, so the drive from Brooklyn covers both. Mention it when you book so we allow the time."),
  ("How long will it last?","Typically 6 to 12 months for lips and 12 to 18 months for cheeks and jawline, depending on the product and how much the area moves. Individual results vary."),
 ],
 "related":[("/fillers/","All Dermal Fillers"),("/lip-filler-brooklyn-oh/","Lip Filler in Brooklyn"),("/kybella-cleveland-oh/","Kybella in Cleveland"),("/pdo-thread-lift-lakewood-oh/","PDO Thread Lift in Lakewood"),("/pricing/","Full Price List")],
},

# ---------- LIP FILLER — BROOKLYN (46 impressions, 0 clicks) ----------
{
 "slug":"lip-filler-brooklyn-oh", "service":"Lip Filler", "service_url":"/lip-filler/",
 "city":"Brooklyn", "city_state":"Brooklyn, OH", "also":["Parma, OH","Old Brooklyn, OH","Brooklyn Heights, OH","Lakewood, OH"],
 "title":"Lip Filler in Brooklyn, OH | $500 Full, $300 Half | Serene",
 "desc":"Lip filler for Brooklyn, OH &mdash; $500 a full syringe or $300 for a half-syringe Mini Pout, injected by board-certified physicians in Hudson. Free consultation.",
 "eyebrow":"Lip Filler &middot; Serving Brooklyn, OH",
 "h1":"Lip Filler for Brooklyn, Ohio",
 "hero":"Volbella, Juv&eacute;derm Ultra XC and Restylane Kysse, placed by board-certified physicians. $500 for a full syringe, $300 for a half-syringe Mini Pout.",
 "drive":"About 35 minutes from Brooklyn",
 "introh2":"Proportion first, volume second",
 "introlead":"Most lip filler that looks obviously done is not over-filled so much as wrongly filled &mdash; volume placed where the anatomy did not ask for it. The fix is not less product. It is a plan.",
 "intro":"<p>At Serene, lip treatment starts with what your lips actually do: how the upper lip sits against the lower, where the vermillion border has flattened, whether the corners have turned down. Then the product is matched to that. <strong>Volbella</strong> is soft and subtle for definition and fine lip lines, <strong>Juv&eacute;derm Ultra XC</strong> carries more structure, and <strong>Restylane Kysse</strong> is chosen for flexible movement.</p><p>A full syringe is <strong>$500</strong>. A half syringe &mdash; our <strong>Mini Pout</strong> &mdash; is <strong>$300</strong>, and it is genuinely the right starting point for most first-timers. You can always add. Taking it away means dissolving it.</p><p>Both physicians inject personally, and hyaluronidase is available from $150 if you ever want the filler reversed.</p>",
 "price_rows":[("Lip Filler &mdash; Full Syringe (1 mL)","$500"),("Lip Filler &mdash; Half Syringe (0.5 mL, Mini Pout)","$300"),("Filler Reversal (hyaluronidase)","$150+"),("Consultation","No charge")],
 "directions":"<p><strong>From Brooklyn (about 28 miles):</strong> I-480 East to I-271 South, exit OH-303 (Streetsboro Rd) east into downtown Hudson &mdash; roughly 35 minutes outside rush hour. Free parking outside Suite 2.</p><p><strong>From Parma, Old Brooklyn or Lakewood:</strong> I-480 East to I-271 South and the same OH-303 exit, about 35 to 45 minutes.</p>",
 "origin_q":"Brooklyn,+OH",
 "faqs":[
  ("How much is lip filler near Brooklyn, OH?","A full syringe is $500 and a half-syringe Mini Pout is $300 at Serene Med Spa in Hudson. There is no consultation fee."),
  ("Should I start with a full or half syringe?","Most first-time patients do better starting with the half-syringe Mini Pout at $300. It is easier to add more later than to dissolve and start over."),
  ("How long does lip filler last?","Usually 6 to 12 months. Lips move constantly, so they metabolize filler faster than cheeks or jawline. Individual results vary."),
  ("How much swelling is normal?","Lips swell more than any other area. Expect significant swelling for 24 to 48 hours and a settled result at about two weeks. Do not judge your lips on day one, and do not book them right before an event."),
  ("Can lip filler be dissolved?","Yes. All three products we use for lips are hyaluronic acid and can be reversed with hyaluronidase, from $150."),
  ("Who does the injecting?","Board-certified physicians &mdash; Dr. Shweta Arora and Dr. Robin Arora &mdash; not a rotating injector."),
 ],
 "related":[("/lip-filler/","About Lip Filler"),("/dermal-fillers-brooklyn-oh/","Dermal Fillers in Brooklyn"),("/fillers/","All Dermal Fillers"),("/pdo-thread-lift-lakewood-oh/","PDO Thread Lift in Lakewood"),("/pricing/","Full Price List")],
},


# ---------- KYBELLA — CLEVELAND (47 impressions, 0 clicks) ----------
{
 "slug":"kybella-cleveland-oh", "service":"Kybella", "service_url":"/kybella/",
 "city":"Cleveland", "city_state":"Cleveland, OH", "also":["Independence, OH","Brecksville, OH","Beachwood, OH","Solon, OH"],
 "title":"Kybella in Cleveland, OH | $600 a Vial | Serene Med Spa",
 "desc":"Kybella double-chin treatment for Cleveland, OH &mdash; $600 a vial, injected by board-certified physicians at Serene Med Spa in Hudson, about 30 minutes south.",
 "eyebrow":"Kybella &middot; Serving Cleveland, OH",
 "h1":"Kybella for Cleveland, Ohio",
 "hero":"The only FDA-approved injectable that permanently destroys submental fat. $600 a vial, performed by board-certified physicians about 30 minutes south of downtown Cleveland.",
 "drive":"About 30 minutes from downtown Cleveland",
 "introh2":"A physician assessment before anyone sells you vials",
 "introlead":"Kybella destroys fat cells permanently. That is a genuine advantage, and it is also why the wrong candidate pays for a treatment that was never going to work.",
 "intro":"<p>Under-chin fullness has more than one cause. It can be fat, which Kybella treats. It can be lax skin, which Kybella does not. It can be a low-set hyoid or a recessed chin, in which case the answer might be filler or nothing at all. At Serene a physician examines you and says which one you have &mdash; including when the answer is that Kybella is not your treatment.</p><p>When it is indicated, expect <strong>2 to 4 sessions</strong> at least a month apart, at <strong>$600 per vial</strong>. Swelling after each session is substantial and lasts several days; Cleveland patients usually schedule around a quiet weekend.</p><p>Both physicians who perform Kybella here are board-certified and see you through the full course, which matters when you are judging gradual change over several months.</p>",
 "price_rows":[("Kybella Fat Dissolver","$600 /vial"),("Typical course (2&ndash;4 sessions)","$1,200&ndash;$2,400"),("Consultation","No charge")],
 "directions":"<p><strong>From downtown Cleveland (about 26 miles):</strong> I-77 South to I-271 South, exit OH-303 (Streetsboro Rd) east into downtown Hudson &mdash; roughly 30 minutes outside rush hour.</p><p><strong>From Beachwood or Solon:</strong> I-271 South to OH-303 East, about 20 to 25 minutes. <strong>From Independence or Brecksville:</strong> I-77 South to OH-303 East, about 25 minutes.</p>",
 "origin_q":"Cleveland,+OH",
 "faqs":[
  ("How much is Kybella in the Cleveland area?","Kybella is $600 per vial at Serene Med Spa in Hudson. A full course is usually 2 to 4 sessions, so $1,200 to $2,400 depending on how much fullness is being treated."),
  ("How far is Hudson from Cleveland?","About 26 miles &mdash; roughly 30 minutes from downtown via I-77 and I-271, and 20 to 25 minutes from Beachwood or Solon."),
  ("Is the fat loss permanent?","The destroyed fat cells do not come back. Substantial weight gain later can still change the area, because the remaining cells enlarge."),
  ("What if my issue is loose skin rather than fat?","Then Kybella is the wrong treatment and we will tell you so. Morpheus8, a PDO thread lift or Ultherapy PRIME address laxity; Kybella does not."),
  ("How long is the downtime?","Plan on noticeable swelling for 3 to 7 days after each session, plus possible bruising, numbness and firmness. Most people work through it, but it is visible."),
  ("Who performs it?","Board-certified physicians &mdash; Dr. Shweta Arora and Dr. Robin Arora."),
 ],
 "related":[("/kybella/","About Kybella"),("/kybella-akron-oh/","Kybella in Akron"),("/med-spa-solon-oh/","Med Spa Near Solon"),("/morpheus8/","Morpheus8"),("/pricing/","Full Price List")],
},

# ---------- PDO THREAD LIFT — LAKEWOOD (45 impressions, 0 clicks) ----------
{
 "slug":"pdo-thread-lift-lakewood-oh", "service":"PDO Thread Lift", "service_url":"/thread-lift/",
 "city":"Lakewood", "city_state":"Lakewood, OH", "also":["Rocky River, OH","Westlake, OH","Cleveland, OH","Brooklyn, OH"],
 "title":"PDO Thread Lift in Lakewood, OH | From $500 | Serene Med Spa",
 "desc":"PDO thread lift for Lakewood, OH &mdash; dissolvable threads for the jawline, cheeks and brow, from $500, performed by board-certified physicians in Hudson.",
 "eyebrow":"PDO Thread Lift &middot; Serving Lakewood, OH",
 "h1":"PDO Thread Lift for Lakewood, Ohio",
 "hero":"Dissolvable threads that lift the jawline, cheeks and brow without surgery &mdash; and leave new collagen behind as they dissolve. From $500, performed by board-certified physicians.",
 "drive":"About 40 minutes from Lakewood",
 "introh2":"Between filler and a facelift",
 "introlead":"A thread lift occupies the gap that filler cannot fill and surgery overshoots: real repositioning of tissue, done in an office, with days of recovery rather than weeks.",
 "intro":"<p>Barbed PDO threads are passed under the skin and anchored, lifting the tissue along a vector your physician chooses. The threads themselves dissolve over several months. What remains is the collagen your body laid down along their path, which is why results outlast the material.</p><p>A face lift with threads starts at <strong>$500</strong>. This is not a permanent result &mdash; expect roughly 12 to 18 months depending on how much lift was placed and how your tissue behaves &mdash; and it is not a substitute for a surgical lift if that is genuinely what your anatomy needs. A physician will tell you which category you are in.</p><p>Threads are technique-dependent in a way few aesthetic treatments are. At Serene, both physicians place them personally, and we are candid at the consultation when someone would be better served by Ultherapy PRIME, Morpheus8, or a surgeon.</p>",
 "price_rows":[("PDO Thread Face Lift","$500+"),("Consultation","No charge"),("Often combined with filler","$500 /syringe"),("Often combined with Morpheus8","$800 /tx")],
 "directions":"<p><strong>From Lakewood (about 33 miles):</strong> I-90 East to I-77 South, then I-271 South and the OH-303 (Streetsboro Rd) exit east into downtown Hudson &mdash; roughly 40 minutes outside rush hour.</p><p><strong>From Rocky River or Westlake:</strong> I-480 East to I-271 South, then OH-303 East, about 45 minutes.</p>",
 "origin_q":"Lakewood,+OH",
 "faqs":[
  ("How much does a PDO thread lift cost near Lakewood?","A PDO thread face lift starts at $500 at Serene Med Spa in Hudson. Final cost depends on how many threads are needed and which areas are lifted; your physician will quote it at the free consultation."),
  ("How long does a thread lift last?","Typically 12 to 18 months. The threads dissolve within months, but the collagen they stimulate persists longer. Individual results vary."),
  ("Is it painful?","Local anesthetic is used at the entry points. Most patients describe pressure and tugging rather than pain. Soreness and tightness for several days afterward are normal."),
  ("What is the downtime?","Most people return to normal activity within a day or two, with possible bruising, swelling and a tight or puckered look that settles over one to two weeks. Avoid strenuous exercise and facial massage while you heal."),
  ("Thread lift or facelift?","Threads reposition tissue modestly and suit mild to moderate laxity. If you have significant skin excess, a surgical lift will give a better and far more durable result &mdash; and we will say so rather than sell you threads."),
  ("Is it worth driving from Lakewood?","That is your call to make. It is about 40 minutes, and threads are a single-session treatment rather than a series, so most Lakewood patients make the trip once for the consult and once for treatment &mdash; or combine both in a single visit."),
 ],
 "related":[("/thread-lift/","About PDO Thread Lift"),("/ultherapy/","Ultherapy PRIME"),("/morpheus8/","Morpheus8"),("/lip-filler-brooklyn-oh/","Lip Filler in Brooklyn"),("/pricing/","Full Price List")],
},

# ---------- MORPHEUS8 — AKRON (60 impressions "near me", 0 clicks) ----------
{
 "slug":"morpheus8-akron-oh", "service":"Morpheus8", "service_url":"/morpheus8/",
 "city":"Akron", "city_state":"Akron, OH", "also":["Cuyahoga Falls, OH","Fairlawn, OH","Stow, OH","Tallmadge, OH"],
 "title":"Morpheus8 in Akron, OH | $800 or 3 for $2,100 | Serene",
 "desc":"Morpheus8 RF microneedling for Akron, OH &mdash; $800 a treatment or three for $2,100, performed by board-certified physicians in Hudson, 25 minutes up Route 8.",
 "eyebrow":"Morpheus8 &middot; Serving Akron, OH",
 "h1":"Morpheus8 for Akron, Ohio",
 "hero":"Radiofrequency microneedling that tightens and remodels from the inside out &mdash; face, neck and body. $800 a treatment, or three for $2,100.",
 "drive":"About 25 minutes from downtown Akron",
 "introh2":"Tightening that reaches the layer that matters",
 "introlead":"Ordinary microneedling injures the surface and lets healing do the rest. Morpheus8 adds radiofrequency energy delivered at a controlled depth, so the remodeling happens in the deeper dermis and subdermal fat where laxity actually lives.",
 "intro":"<p>That depth control is what makes it versatile. Set shallow, it addresses texture, pores and acne scarring. Set deeper, it contracts the fibrous layer under the skin &mdash; which is why it is used along the jawline and under the chin, and why it works on the abdomen and knees as well as the face.</p><p>A treatment is <strong>$800</strong>, and a <strong>series of three is $2,100</strong>. Three is the usual recommendation, spaced about a month apart, with results continuing to build for several months afterward as collagen remodels. MorpheusV for remodeling is $800, and Morpheus8 for hyperhidrosis is $600.</p><p>Downtime is modest &mdash; typically a sunburn-like redness and mild grid-pattern texture for two to four days. Akron patients commonly book Friday afternoons for that reason.</p>",
 "price_rows":[("Morpheus8 RF","$800 /tx"),("Morpheus8 RF &mdash; Series of 3","$2,100"),("MorpheusV (Remodeling)","$800"),("Morpheus8 Hyperhidrosis","$600"),("Consultation","No charge")],
 "directions":"<p><strong>From downtown Akron (about 15 miles):</strong> OH-8 North roughly 12 miles to the OH-303 (Streetsboro Rd) exit, then east into downtown Hudson. Free parking outside Suite 2.</p><p><strong>From Fairlawn, Bath or Copley:</strong> I-77 North to OH-8 North, then OH-303 East, about 25 to 30 minutes.</p>",
 "origin_q":"Akron,+OH",
 "faqs":[
  ("How much is Morpheus8 near Akron?","Morpheus8 is $800 per treatment at Serene Med Spa in Hudson, or $2,100 for a series of three. MorpheusV is $800 and Morpheus8 for hyperhidrosis is $600."),
  ("How many treatments do I need?","Three, about a month apart, is the usual recommendation. Results continue developing for several months after the final session as collagen remodels. Individual results vary."),
  ("What is the downtime?","Typically two to four days of redness resembling a sunburn, sometimes with a faint grid pattern and mild swelling. Most people are presentable with makeup the next day."),
  ("Does it hurt?","Topical numbing is applied first, and most patients tolerate it well &mdash; described as heat and pressure. Deeper settings on the jawline and neck are more intense than facial settings."),
  ("Can Morpheus8 be used on the body?","Yes. The abdomen, arms, thighs and knees are all commonly treated, and MorpheusV is used for remodeling. Body areas take longer and may need more sessions."),
  ("Is it safe for darker skin tones?","Radiofrequency energy is not absorbed by pigment the way laser light is, which makes Morpheus8 a comparatively safe option across skin types. Your physician will confirm at your consultation."),
 ],
 "related":[("/morpheus8/","About Morpheus8"),("/kybella-akron-oh/","Kybella in Akron"),("/dermal-fillers-akron-oh/","Dermal Fillers in Akron"),("/ultherapy/","Ultherapy PRIME"),("/med-spa-akron-oh/","Med Spa Near Akron")],
},

# ---------- MEN'S HEALTH — HUDSON (37 impressions, 0 clicks, no page targeting it) ----------
{
 "slug":"mens-health-hudson-oh", "service":"Men's Health", "service_url":"/mens-sexual-wellness/",
 "city":"Hudson", "city_state":"Hudson, OH", "also":["Stow, OH","Akron, OH","Aurora, OH","Twinsburg, OH"],
 "title":"Men's Health Clinic in Hudson, OH | Serene Med Spa",
 "desc":"Physician-led men's health in Hudson, OH &mdash; sexual wellness, hormone optimization, medical weight loss, IV therapy and aesthetics, all under one roof. Discreet.",
 "eyebrow":"Men's Health &middot; Hudson, OH",
 "h1":"Men's Health Clinic in Hudson, Ohio",
 "hero":"Sexual wellness, hormone optimization, medical weight loss and aesthetics &mdash; handled by board-certified physicians in a private office in downtown Hudson, not a franchise storefront.",
 "drive":"In downtown Hudson &mdash; free parking at the door",
 "introh2":"One physician, the whole picture",
 "introlead":"Most men who come in for one thing turn out to have a second thing connected to it. Energy, weight, sleep, libido and mood are not separate complaints, and treating them in separate buildings rarely works well.",
 "intro":"<p>Serene is physician-owned. Dr. Robin Arora is board-certified in internal medicine, nephrology and hypertension, and addiction medicine; Dr. Shweta Arora is board-certified in anesthesiology with certification in aesthetic medicine. That means the man who reviews your labs is a physician, and the plan accounts for your blood pressure, your kidneys and your medication list &mdash; not just the symptom you booked for.</p><p>What we treat: <strong>sexual wellness</strong>, including Alma Duo acoustic wave therapy ($500 per treatment) and the P-Shot; <strong>hormone optimization</strong> with Bi&ouml;te pellet therapy, as certified Bi&ouml;te providers; <strong>medical weight loss</strong> with physician-supervised injectable programs at $149 a visit; <strong>IV therapy and NAD+</strong> from $149; and aesthetics for men, from Botox at $11 a unit to laser hair removal and Morpheus8.</p><p>Visits are private, prices are published, and nothing gets sold to you in the room.</p>",
 "price_rows":[("Sexual Wellness Consultation","No charge"),("Alma Duo Acoustic Wave","$500 /tx"),("Medical Weight Loss","$149 /visit"),("Bi&ouml;te Hormone Optimization","From $405"),("IV Therapy &amp; NAD+","From $149"),("Botox (including shoulder slimming)","$11 /unit"),("Gonadorelin (Rx) &mdash; men on testosterone therapy","$109 /mo")],
 "directions":"<p>We are at <strong>50 W Streetsboro St, Suite 2</strong> on Route 303 in downtown Hudson, a street-level office with free parking directly outside &mdash; no garage, no meters, no shared waiting room with a retail counter.</p><p><strong>From Stow or Cuyahoga Falls:</strong> OH-91 or Hudson Drive north, 12 to 18 minutes. <strong>From Akron:</strong> OH-8 North to OH-303 East, about 25 minutes. <strong>From Twinsburg or Aurora:</strong> 10 to 15 minutes.</p>",
 "origin_q":"Hudson,+OH",
 "faqs":[
  ("Is there a men's health clinic in Hudson, Ohio?","Yes. Serene Med Spa at 50 W Streetsboro St, Suite 2 in downtown Hudson offers physician-led men's health &mdash; sexual wellness, hormone optimization, medical weight loss, IV therapy and aesthetics."),
  ("Are visits private?","Yes. Consultations are one-on-one with a physician in a private treatment room, and scheduling can be arranged around your work day. Call (330) 460-5915 if you would prefer to discuss anything before booking."),
  ("What does men's sexual wellness involve?","It starts with a physician consultation at no charge. Depending on findings, options include Alma Duo acoustic wave therapy at $500 per treatment and the P-Shot. Your history, medications and cardiovascular risk are part of that assessment."),
  ("Do you handle hormone optimization?","Yes &mdash; we are certified Bi&ouml;te providers and offer pellet therapy from $405. Lab work guides dosing, and follow-up is with the same physician."),
  ("Do you offer medical weight loss for men?","Yes. Physician-supervised injectable weight-loss programs are $149 a visit with monthly check-ins. Because Dr. Arora is a nephrologist, the plan is built around your kidney function, blood pressure and current medications."),
  ("Do men get Botox here?","Regularly. Botox is $11 a unit, and shoulder slimming Botox is priced the same. Laser hair removal, Morpheus8 and laser resurfacing are all commonly requested by male patients."),
  ("Who will I see?","A board-certified physician &mdash; Dr. Robin Arora or Dr. Shweta Arora. Not a nurse-run protocol, and not a different provider each visit."),
 ],
 "related":[("/mens-sexual-wellness/","Men's Sexual Wellness"),("/hormone-optimization/","Hormone Optimization"),("/medical-weight-loss/","Medical Weight Loss"),("/iv-therapy/","IV Therapy &amp; NAD+"),("/pricing/","Full Price List")],
},

]
